### ISSUE TITLE
Error when using react-native-version

### ISSUE THREAD

**Issue by dimashpt** [Instabug/Instabug-React-Native#1000]
### Steps to Reproduce the Problem
1. Use react-native-version for bumping project version
2. Find error located in sourcemaps.sh:
```
[RNV] Versioning iOS...
[RNV] SyntaxError: Expected "\"", "\\'", "\\\"", "\\n", or [^\\"] but "\\" found.
```
### Expected Behavior
The sourcemaps.sh should not contains backslashes

https://github.com/Instabug/Instabug-React-Native/blob/2b0a20dde5cc6285b6e6a316d51b650a375ff5e6/ios/sourcemaps.sh

### Actual Behavior
```
[RNV] Versioning iOS...
[RNV] SyntaxError: Expected "\"", "\\'", "\\\"", "\\n", or [^\\"] but "\\" found.
```

### SDK Version

11.12.0

### React Native, iOS and Android Versions
0.71.11

### Device Model

All iOS device

**Comment by a7medev** [comment]
Hi @dimashpt! Thanks for reporting this issue.
After looking into it, it looks like it's not an issue with our `sourcemaps.sh` script. There should be no problem with having backslashes in a shell script, it's just that the parser react-native-version uses fails to parse the file when it contains backslashes.
I have found the issue reported on their GitHub repo as well (stovmascript/react-native-version#52), it was also reported on the parser's GitHub repo (NativeScript/pbxproj-dom#9).
