### ISSUE TITLE
Is there any way handle the Beta Welcome Message , like is there any handler for the 'done' button. To do action after clicking on this button

### ISSUE THREAD

**Issue by vaishnav-197** [Instabug/Instabug-React-Native#1023]
## Steps to Reproduce the Problem
This is just an enquiry
Open the Instabug Beta Welcome Message
Swipe to the last screen.
i do want to do some action after the beta message is dismissed

##### SDK Version

11.3.0
### React Native, iOS and Android Versions
RN - 0.67.5

**Comment by abdelhamid-f-nasser** [comment]
Hi @vaishnav-197 👋 , 

I'll check it and will promptly provide you with information about this.

**Comment by vaishnav-197** [comment]
Thanks @abdelhamid-f-nasser
