### ISSUE TITLE
iOS build failing in release mode

### ISSUE THREAD

**Issue by singhayush1403** [Instabug/Instabug-React-Native#1025]
▸ The following build commands failed:
▸ 	PhaseScriptExecution [CP-User]\ [instabug-reactnative]\ Upload\ Sourcemap /Users/expo/Library/Developer/Xcode/DerivedData/Schmooze-gdykegqojmrupjbaxrsvqotguxmb/Build/Intermediates.noindex/ArchiveIntermediates/Schmooze/IntermediateBuildFilesPath/Schmooze.build/Release-iphoneos/Schmooze.build/Script-4DC76788F063022455DA75A1.sh (in target 'Schmooze' from project 'Schmooze')

### Steps to Reproduce the Problem
Xcode iOS Build
### Expected Behavior
Build succeeds
### Actual Behavior
Build Fails
### Instabug integration code

  Instabug.init({
    token: APP_TOKEN,
    invocationEvents: [InvocationEvent.shake],
    debugLogsLevel: LogLevel.debug,
  });

### SDK Version

instabug-reactnative: 11.13.0

### React Native, iOS and Android Versions
react-native: 0.71.7

iOS Deployment Target: 14.0

**Comment by BG687** [comment]
I am having the same issue

**Comment by BG687** [comment]
@singhayush1403 Did you end up finding a workaround for this issue?

**Comment by rush2di** [comment]
Has anyone been able to find a solution ? I am having the same issue as well
