### ISSUE TITLE
Custom fingerprint

### ISSUE THREAD

**Issue by gabrielmoreira-nn** [Instabug/Instabug-React-Native#1037]
I couldn't find any way in the code to send a custom fingerprint when reporting an error that occurs in the JS.

We've integrated some native libraries that send various errors from native to JS, and these errors are handled when possible, exclusively in the JS layer. These errors will always have the same stack trace in the JS since they originate from the native bridge for the same operation. However, the actual errors that occur can be entirely different from each other. 
We shouldn't group them together.

How can we address this?

**Comment by a7medev** [comment]
Hi @gabrielmoreira-nn! Thanks for reporting this issue. We are currently discussing possible solutions to this issue and I will update you once we have something to share.

**Comment by gabrielmoreira-nn** [comment]
@a7medev Do you see any quick or dirty workaround I could use until you find a proper approach?

**Comment by gabrielmoreira-nn** [comment]
@a7medev Thanks! but in some cases, those are libraries we don't maintain the native code, and we use it through the JS side. 

It would be much easier to have a way to ungroup errors for a specific stack trace location through the UI.

I understand that the default behavior makes sense, to group it based on stack trace, but for many codebases, it might be wrong. I suspect that many Instabug customers didn't notice this problem on their accounts, or worse they just stopped trusting the dashboard occurrences count. I saw both of these symptoms happening in the organization I work for.

**Comment by a7medev** [comment]
@gabrielmoreira-nn Yes, I get what you mean. We already have support for adding a custom grouping string on the native side, so it's a matter of bringing that to React Native and we are planning to work on it in an upcoming cycle. I will update you once we have something to share 🙏🏼
