### ISSUE TITLE
Customise strings on Survey Welcome Screen

### ISSUE THREAD

**Issue by leethree** [Instabug/Instabug-React-Native#1040]
How do I customise this screen as mentioned in your documentation?

![image](https://github.com/Instabug/Instabug-React-Native/assets/648142/cac15ff6-4114-4765-afe0-ffaa6ae7a5ee)

https://docs.instabug.com/docs/react-native-customizing-survey-behavior#showing-a-welcome-screen

I tried to look for it in the [override string values](https://docs.instabug.com/docs/react-native-locale#overriding-string-values) but I couldn't find the corresponding keys.

**Comment by leethree** [comment]
not stale

**Comment by abdelhamid-f-nasser** [comment]
Hello @leethree 👋 , I apologize for the late reply, I'll check this out and will get back to you with more info as soon as possible.
