### ISSUE TITLE
Error loading JS bundle when running on Android

### ISSUE THREAD

**Issue by haozhutw** [Instabug/Instabug-React-Native#1161]
A build error is introduced since 12.7.0, please see screenshot below.

![Screenshot_1709550396](https://github.com/Instabug/Instabug-React-Native/assets/66658218/e20f6096-e326-423e-806a-67eebb058de6)

Did you test the library before you publish the new version?

### SDK Version

"instabug-reactnative": "12.7.0",

### Device Model

Android simulator

### [Optional] Project That Reproduces the Issue

just upgrade instabug-reactnative to 12.7.0, build on Android simulator successfully and then failed to load the js bundle because of this error 

```
error node_modules/instabug-reactnative/src/modules/Instabug.ts: Unexpected token: operator (?) in file node_modules/instabug-reactnative/src/modules/Instabug.ts at 52:36. Run CLI with --verbose flag for more details.
```

This is the screenshot of the code in `instabug-reactnative`

<img width="641" alt="Screenshot 2024-03-04 at 19 09 42" src="https://github.com/Instabug/Instabug-React-Native/assets/66658218/ef204f22-d482-4289-83e9-f11dd6a5cdde">

**Comment by ahmedAlaaInstabug** [comment]
Hello @haozhutw  👋 , I'll check this out and will get back to you with more info as soon as possible.

**Comment by ahmedAlaaInstabug** [comment]
hello @haozhutw  👋, Can you please provide the node version you used ?

**Comment by haozhutw** [comment]
> hello @haozhutw 👋, Can you please provide the node version you used ?

node version: v18.19

I downgrade the instabug-reactnative to v12.6.0, no error occurs.

**Comment by haozhutw** [comment]
Maybe ??= is too advanced for some old environment, can you make it compatible like this?

```
if (!config.networkInterceptionMode) {
    config.networkInterceptionMode = NetworkInterceptionMode.javascript;
}
```

**Comment by ahmedAlaaInstabug** [comment]
hello @haozhutw can you please try this version and let us know if it fixes your issue?


### Installation

You can install the snapshot through NPM:

```sh
npm install https://github.com/Instabug/Instabug-React-Native\#snapshot/fix-init-function-error-on-old-node-version
```

or Yarn:

```sh
yarn add https://github.com/Instabug/Instabug-React-Native\#snapshot/fix-init-function-error-on-old-node-version
```

**Comment by gvillenave** [comment]
@ahmedAlaaInstabug I see that the PR with the fix was merged, but it doesn't seem that a new version was released with that fix? Can this be prioritized?
FWIW, it's not due to using an old version of TypeScript, this reproduces on 5.4.3. I've found other reports indicating that the nullish coalescing operator might not be currently supported by the React Native bundler.

**Comment by leethree** [comment]
We are seeing this issue. It's not supported syntax in React Native. It has nothing to do with Typescript version or Node version.
