### ISSUE TITLE
 App hang on iOS physical device when Instabug enabled specifically double tap to navigating from one screen to another screen.

### ISSUE THREAD

**Issue by quangcao-offerup** [Instabug/Instabug-React-Native#1163]
### Steps to Reproduce the Problem
Double tap on a one screen to navigate to another screen with instabug enabled 
### Expected Behavior
Navigate to another screen w/o delay or app hang
### Actual Behavior
After couple of double tap, there is app hang would cause the app delay in debug build. in prod build, we can see it crash due to apphang taking too long. 
### Instabug integration code
```
import type InstabugType from 'instabug-reactnative';
import type { WelcomeMessageMode, InvocationEvent } from 'instabug-reactnative';

type InternalInstabugType = typeof InstabugType & {
  WelcomeMessageMode: typeof WelcomeMessageMode;
  InvocationEvent: typeof InvocationEvent;
};

let InternalInstabug: InternalInstabugType | null = null;
const RNInstabug = require('instabug-reactnative').default as InternalInstabugType;

InternalInstabug = RNInstabug;

InternalInstabug.WelcomeMessageMode = require('instabug-reactnative')
  .WelcomeMessageMode as InternalInstabugType['WelcomeMessageMode'];

InternalInstabug.InvocationEvent = require('instabug-reactnative')
  .InvocationEvent as InternalInstabugType['InvocationEvent'];

const Instabug = InternalInstabug;

export const useCrashReporting = () => {
  useEffect(() => {
        Instabug.init({
          token: Config.INSTABUG_APP_TOKEN,
          invocationEvents: [Instabug.InvocationEvent.shake],
        });
  }, []);
};

```
### SDK Version
"instabug-reactnative": "12.4",

### React Native, iOS and Android Versions
"react-native": "0.70.13",
"@react-navigation/native": "6.1.6",
"@react-navigation/stack": "6.3.16",

### Device Model
Iphone 14 Pro.
iOS 17.3.1. 

Iphone 13 pro
iOS 16.1.1

### trace
<img width="1073" alt="Screenshot 2024-03-05 at 11 24 13 AM" src="https://github.com/Instabug/Instabug-React-Native/assets/67335742/b4abe231-7740-44e4-8f98-d4622d7ddb03">

**Comment by sofian-sunny** [comment]
Also facing crash on iOS devices 
SessionReplaySyncManager.sync()
SIGSEGV: Crash due to signal: SIGSEGV(SEGV_ACCERR) at 8000000000000008

**Comment by ahmedAlaaInstabug** [comment]
hello @quangcao-offerup 👋 ,  Thanks for reporting this issue,
Can you please provide Instabug integration code since the attached code is for sentry ?

**Comment by quangcao-offerup** [comment]
@ahmedAlaaInstabug corrected. Thanks.

**Comment by ahmedAlaaInstabug** [comment]
hi @quangcao-offerup 👋 , this issue has been fixed in version 12.6,  can you please try the latest version v12.8, and let us know if it fixes your issue.

**Comment by quangcao-offerup** [comment]
Hi @ahmedAlaaInstabug after the upgraded to 12.8, it's still able to  repro consistently on my iOS 17.3.1. Iphone 14 Pro.

**Comment by ahmedAlaaInstabug** [comment]
hi @quangcao-offerup , can you please share a sample of double tap implmentation  that you use ?, since i can't re-produce the issue

**Comment by quangcao-offerup** [comment]
Hi @ahmedAlaaInstabug after double checking, it turns out issue from our legacy implementation, not instabug issue. Taking that legacy piece out would fix the issue. I'm closing this now. Thanks
