### ISSUE TITLE
Unable to capture Unhandled Promise Rejection in Crashes

### ISSUE THREAD

**Issue by longnguyen2508** [Instabug/Instabug-React-Native#1165]
### Steps to Reproduce the Problem

- Clone project
- Run example project
- Modify `token` in App.tsx
- Press `Reject an Unhandled Promise`
- Check Crashes on Instabug
- There is no error message named `Unhandled Promise Rejection from Instabug Test App`

### Expected Behavior

- Could log unhandled errors in Crashes

### Actual Behavior

- Could not log unhandled errors in Crashes

### SDK Version

> instabug-reactnative: ^12.8.0

### React Native, iOS and Android Versions

> react-native: 0.72.3
> iOS: 17.2

### Device Model

> iPhone 15 Pro (simulator)

**Comment by ahmedAlaaInstabug** [comment]
hello @longnguyen2508  👋 , Fatal Crashes can only be tested in release mode

**Comment by longnguyen2508** [comment]
@longnguyen2508 Oh, thank you. I will test it again.
