### ISSUE TITLE
Play Core library used in sdk is incompatible with targetSdkVersion 34 

### ISSUE THREAD

**Issue by vinaygregoryjohn183** [Instabug/Instabug-React-Native#1237]
Got the following email from Play Console:
Update your Play Core Maven dependency to an Android 14 compatible version! Your current Play Core library is incompatible with targetSdkVersion 34 (Android 14), which introduces a backwards-incompatible change to broadcast receivers to improve user security. As a reminder, from August 31, Google Play requires all new app releases to target Android 14. Update to the latest Play Core library version dependency to avoid app crashes: https://developer.android.com/guide/playcore#playcore-migration

**The sdk is currently using the com.google.android.play:core-common:2.0.2 library which seems to be incompatible with  targetSdkVersion 34 (Android 14).**

### SDK Version
13.1.1

### React Native, Android Versions
Android 14

**Comment by manasbatchservice** [comment]
+1

**Comment by iamFarukh** [comment]
We are also getting the same warning from play store, 
team, please fix this ASAP.

**Comment by vinaygregoryjohn183** [comment]
Any update?

**Comment by manasbatchservice** [comment]
Getting same warning from google any update?

**Comment by vinaygregoryjohn183** [comment]
No updates... @manasbatchservice You are sure that it is this particular package causing the Google play warning right?

**Comment by manasbatchservice** [comment]
Yes @vinaygregoryjohn183 

Run the following command to check all the dependencies listed in the app, and check which one has the com.google.android.play:core dependency, by exporting all the dependencies to a text file dependencies.txt

`./gradlew app:dependencies > dependencies.txt`

**Comment by iamFarukh** [comment]
Yes, our mobile app, we are also facing same issue, please fix this ASAP.

**Comment by vinaygregoryjohn183** [comment]
if anyone finds a solution please comment it out here

**Comment by vinaygregoryjohn183** [comment]
any updates anyone?

**Comment by aj-spanio** [comment]
Still looking for a fix here
