### ISSUE TITLE
Warning on 13.3.0: "IBG-RN: The response body for the network request with URL..."

### ISSUE THREAD

**Issue by leonardorib** [Instabug/Instabug-React-Native#1268]
After upgrading to 13.3.0, I'm getting this warning (console.warn) in the development build on both Android and iOS every time Instabug is initialized:

```
IBG-RN: The response body for the network request with URL http://192.168.1.141:8081/symbolicate has been omitted because the content type  isn't supported.
```

Is this expected?

It didn't affect functionality. It's just annoying. Feels like a console.warn that shouldn't be there I guess?

### Steps to Reproduce the Problem
1. Upgraded to 13.3.0
2. Run the development build of the app and init instabug

### Expected Behavior
Shouldn't repeatedly see this warning or should be able to hide it based on the log levels.

### Actual Behavior
Warning keeps showing up.

### Instabug integration code

I made sure all instabug features are commented out. So it really comes down to the initialization:

```typescript
Instabug.init({
    token: config('instabug.token'),
    invocationEvents: [
      config('env') === 'dev'
        ? InvocationEvent.twoFingersSwipe
        : InvocationEvent.shake,
    ],
  });
```

Simply initializing it will trigger the warn. I also tried using `debugLogsLevel: LogLevel.none` but still getting the warn.

### SDK Version

13.3.0

### React Native, iOS and Android Versions

RN 0.73.8 / iOS 17.5.1 / Android 14

### Device Model

iPhone 13 / Samsung Galaxy m52

**Comment by xanderdeseyn** [comment]
Have you found a solution to this? We are running into the same problem.

**Comment by gcottrell1** [comment]
also seeing this. anyone able to take a look?
