### ISSUE TITLE
ANR after Threading violation on Android > 13

### ISSUE THREAD

**Issue by PEvgeniya** [Instabug/Instabug-React-Native#1296]
Hello!
We have a page with Instabug survey triggered on leaving it. Page is accessible via deep link. 
When we arrive on the page when it's already existing (navigate with deep link twice) it should show Instabug survey, which is a case for iOS and Android <13. But on Android 14 it's almost always an ANR crash 

### Expected Behavior
Survey is shown

### Actual Behavior
App is crashed on Android 13 and 14 with ANR Reason: Input dispatching timed out.
iOS works fine, old Android devices also.

We noticed also a Threading violation warning: 
<img width="1055" alt="image" src="https://github.com/user-attachments/assets/44cbfe6d-27b7-4bd7-b8a9-235e56ed3152">

We are a bit puzzled with this since it's mentioned in Instabug-Android that these two calls should be done from background thread: 
![image](https://github.com/user-attachments/assets/2fd19e6a-a7ee-4e3a-ba91-81cb747fc34c)

### SDK Version

"instabug-reactnative": "^13.1.1"

### React Native, iOS and Android Versions
"react-native": "0.74.5"
Android 13, 14

### Device Model

Most of device Android 14, i.e. Samsung Galaxy S24 Plus 

### [Optional] Project That Reproduces the Issue

--

**Comment by PEvgeniya** [comment]
The issue is still here
We would try to trigger crash report on instabug dashboard and will provide the info.

**Comment by krushita042023** [comment]
@PEvgeniya, Any update?
