### ISSUE TITLE
Cannot build Android project with SDK 14.0.0

### ISSUE THREAD

**Issue by leethree** [Instabug/Instabug-React-Native#1327]
### Steps to Reproduce the Problem

Upgrade to instabug-reactnative 14.0.0

### Expected Behavior

Build Android correctly

### Actual Behavior

Android gradle failed because of dependency issues

```
FAILURE: Build failed with an exception.
* What went wrong:
Could not determine the dependencies of task ':intercom_intercom-react-native:compileReleaseJavaWithJavac'.
> Could not resolve all task dependencies for configuration ':intercom_intercom-react-native:releaseCompileClasspath'.
   > Could not resolve com.google.firebase:firebase-messaging:20.2.+.
     Required by:
         project :intercom_intercom-react-native
      > Failed to list versions for com.google.firebase:firebase-messaging.
         > Unable to load Maven meta-data from https://mvn.instabug.com/nexus/repository/instabug-internal/com/google/firebase/firebase-messaging/maven-metadata.xml.
            > Could not GET '[https://mvn.instabug.com/nexus/repository/instabug-internal/com/google/firebase/firebase-messaging/maven-metadata.xml'](https://mvn.instabug.com/nexus/repository/instabug-internal/com/google/firebase/firebase-messaging/maven-metadata.xml). Received status code 401 from server: Unauthorized
```

The added maven repository is internal and it messed up our root project dependencies.

Because we don't have access to instabug-interal, this is incorrectly added to ALL the projects during build process by the following change in v14.0.0:

https://github.com/Instabug/Instabug-React-Native/blob/6692f7b5d8ada49827427ad553ca7836d6a3bd85/android/build.gradle#L83-L95

https://github.com/Instabug/Instabug-React-Native/commit/0a8d8b91aefb3a87a20968b5c84cba98ac9f2d03

Please revert the above change.

### Instabug integration code

Not relevant

### SDK Version

v14.0.0

### Device Model

Not relevant

**Comment by leethree** [comment]
No it could happen to any dependency, because Instabug overwritten `rootProject.allprojects` and thus messed up the maven repository for other dependencies. 

https://github.com/Instabug/Instabug-React-Native/blob/6692f7b5d8ada49827427ad553ca7836d6a3bd85/android/build.gradle#L83

**Comment by mehri-anikanova** [comment]
having the same issue with `14.0.0`

**Comment by ahmedAlaaInstabug** [comment]
@mehri-anikanova @leethree  can you please try this snapshot ?

Your snapshot has been generated! 🚀

Installation
You can install the snapshot through NPM:

`npm install instabug-reactnative@14.0.0-1330838-SNAPSHOT`
or Yarn:

`yarn add instabug-reactnative@14.0.0-1330838-SNAPSHOT`

**Comment by leethree** [comment]
yes removing the `rootProject.allprojects` section solves the issue.

**Comment by kelvin-l-swyftx** [comment]
Same issue happens when upgrade the sdk to `instabug-reactnative@14.1.0`

```
FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':app:compileProdDebugJavaWithJavac'.
> Could not resolve all task dependencies for configuration ':app:prodDebugCompileClasspath'.
   > Could not resolve com.braze:android-sdk-ui:30.0.+.
     Required by:
         project :app
      > Failed to list versions for com.braze:android-sdk-ui.
         > Unable to load Maven meta-data from https://mvn.instabug.com/nexus/repository/instabug-internal/com/braze/android-sdk-ui/maven-metadata.xml.
            > Could not GET 'https://mvn.instabug.com/nexus/repository/instabug-internal/com/braze/android-sdk-ui/maven-metadata.xml'. Received status code 401 from server: Unauthorized
````
