### ISSUE TITLE
Welcome Message Mode not disabling

### ISSUE THREAD

**Issue by deelo55** [Instabug/Instabug-React-Native#1329]
### Expected Behavior
Welcome message mode does not get shown

### Actual Behavior
Welcome message mode is shown 

### Instabug integration code

```
export function useInstabug() {
  useEffect(() => {
    Instabug.setWelcomeMessageMode(WelcomeMessageMode.disabled); // Disable welcome message
    Instabug.init({
      token: process.env.EXPO_PUBLIC_INSTABUG_TOKEN as string,
      invocationEvents: [InvocationEvent.shake, InvocationEvent.screenshot],
    });
    BugReporting.setReportTypes([ReportType.bug, ReportType.feedback]);
  }, []);
}
```

### SDK Version
"instabug-reactnative": "14.0.0-1326154-SNAPSHOT",

### Device Model
iPhone 15

**Comment by ahmedAlaaInstabug** [comment]
Hi @deelo55 , Thanks for reporting this issue. Can you please try to call **setWelcomeMessageMode** method after the **init** method?
