### ISSUE TITLE
clearLogs is missing from JS API

### ISSUE THREAD

**Issue by esprehn** [Instabug/Instabug-React-Native#147]
There's no clearLogs method here, though it's mentioned in all the comments:
https://github.com/Instabug/instabug-reactnative/blob/master/index.js

But it does exist in the java code here:
https://github.com/Instabug/instabug-reactnative/blob/d1b9d41008d30ad0222fee56a9296d27f4dd8c6c/android/src/main/java/com/instabug/reactlibrary/RNInstabugReactnativeModule.java#L751

Seems it's missing for iOS though:
https://github.com/Instabug/instabug-reactnative/blob/d1b9d41008d30ad0222fee56a9296d27f4dd8c6c/ios/RNInstabug/InstabugReactBridge.m

**Comment by salmatarzi** [comment]
@esprehn Thank you for noticing this, we'll make sure to add it in our next release, and I'll keep you posted! 🙏🏽

**Comment by salmamali** [comment]
This is added in version 8.0.9.
