### ISSUE TITLE
Redux integration

### ISSUE THREAD

**Issue by RobertSasak** [Instabug/Instabug-React-Native#151]
I am currently looking into redux integration. I would like to include all redux state changes into crash report. Has anybody deal with similar problem?

**Comment by HeshamMegid** [comment]
Very sorry for the late reply, we've been planning to test this and create a quick sample for it but unfortunately, we got busy with other issues.

Have you been able to get redux state changes into the crash report or do you still need help with it?

**Comment by HeshamMegid** [comment]
Closing the issue for now. Please feel free to reopen if you still need help.

**Comment by salmamali** [comment]
@RobertSasak A possible way to include state changes in a crash report is by adding `Instabug.logDebug(this.props.state)` in the `render` method of all your app's container classes. And of course you will get the state as shown below
```
mapStateToProps(state) {
    return {
       state: state
    }
}

```
