### ISSUE TITLE
Does this really `requiresMainQueueSetup` on iOS?

### ISSUE THREAD

**Issue by jamesreggio** [Instabug/Instabug-React-Native#174]
It's not clear to me why Instabug can't be initialized in the background. In fact, I've been using a branch for three months with `requiresMainQueueSetup` set to `return NO` without any issue.

Allowing background setup helps to cut down on app startup times, and because Instabug brings in some hefty native frameworks, removing main queue setup reduced our app launch time by about 150ms on an iPhone 6. (Every 100ms matters, especially when using many external dependencies.)

It would be great if you could investigate and consider whether this could safely be set to `NO`.

**Comment by Korazy** [comment]
Hey @jamesreggio 

Thanks for reaching out. We'll look into this for you :)

**Comment by jamesreggio** [comment]
Thanks @Korazy!

**Comment by rdiaa** [comment]
@jamesreggio 
Yes, we need it, as we need to capture some information related to the view hierarchy, so it needs to run on the main thread

**Comment by jamesreggio** [comment]
Thanks @rdiaa.

`requiresMainQueueSetup` should only be necessary if you interact with UIKit _during_ module setup. This means that it's only necessary if you access the view hierarchy inside of `constantsToExport`, `supportedEvents`, or `initWithBridge:` (which this module doesn't even implement).

All methods that are called _after_ setup will be run on whatever is returned by `methodQueue`, which you've rightfully set to be the main queue.

So, knowing this, I'm quite confident that `requiresMainQueueSetup` can be `NO` since you're not touching anything in the view hierarchy during those setup methods. As I said earlier, I've been using a fork of the code for many months now with `requiresMainQueueSetup` already set to `NO` and I haven't experienced a single issue.

How do you feel about disabling it?

**Comment by HeshamMegid** [comment]
@jamesreggio this does make sense. We'll be changing `requiresMainQueueSetup` to `NO` and including it in the next release. Will let you know once it's available.

**Comment by jamesreggio** [comment]
Thanks @HeshamMegid!

**Comment by salmamali** [comment]
This is now changed in version 8.0.9.
