### ISSUE TITLE
Instabug.framework: No such file or directory

### ISSUE THREAD

**Issue by FloSugar** [Instabug/Instabug-React-Native#188]
Followed the steps https://github.com/Instabug/instabug-reactnative#installation but still getting 
`error: [APP_PATH]/ios/node_modules/instabug-reactnative/ios/Instabug.framework: No such file or directory`

I tried also to unlink/relink ([here](https://github.com/Instabug/instabug-reactnative#upgrading-from-20x-and-from-803)) but still getting the same error when building in Xcode.

from my package.json: 

    "instabug-reactnative": "^8.0.6",
    "react-native": "0.53.3",

**Comment by salmatarzi** [comment]
@FloSugar Can you please check if this path does indeed exist locally on the file system or not?

**Comment by FloSugar** [comment]
The file does exist, yet !

<img width="843" alt="capture d ecran 2018-08-08 a 18 18 05" src="https://user-images.githubusercontent.com/5587278/43850169-7cd57012-9b37-11e8-95de-438eebae6b89.png">

**Comment by salmatarzi** [comment]
@FloSugar The path in the error that you shared states that the node_modules are inside the ios directory of the app. Did you perhaps npm install the package from the ios directory?

**Comment by FloSugar** [comment]
I have no idea why the node_modules are located to this directory, but as you can see on my screen : there is no `nodes_modules` folder inside my ios directory.

I did the installation again from the beginning and I'm still getting the same error.

**Comment by rdiaa** [comment]
@FloSugar We meant the ios directory that is prior the node_modules directory (the one that has your iOS project in it), not the one inside the instabug-reactnative directory. 

Can you tell me when exactly does this error appear? After you npm install, link and then run?

**Comment by FloSugar** [comment]
You're right, sorry. But the answer stays the same. My node_modules is located at the root of my app folder and only there.

> Can you tell me when exactly does this error appear? After you npm install, link and then run?

Exactly in that order.

**Comment by salmatarzi** [comment]
@FloSugar Can you try clearing your Derived Data and if this doesn't solve it, can you send us a sample app that has this problem on it, so that we can debug it further?

**Comment by FloSugar** [comment]
I did clean and it doesn't change anything unfortunately. It's complicated for me to send you a sample app at this time :(

**Comment by rdiaa** [comment]
@FloSugar 

I'm so sorry that you are facing this, I will check if there's something we can do form our side to get things fixed on your side.

**Comment by rdiaa** [comment]
@FloSugar 

Can you please check the sample app attached? You will need to run: "npm install" first before running the app
[SampleApp.zip](https://github.com/Instabug/Instabug-React-Native/files/2293309/SampleApp.zip)

**Comment by rdiaa** [comment]
@FloSugar 
did you check the sample app? Is everything working on your end?

**Comment by rdiaa** [comment]
@FloSugar 
Perfect, I will be waiting for your feedback

**Comment by rdiaa** [comment]
@FloSugar 
Did you manage to create the sample app?

**Comment by rdiaa** [comment]
@FloSugar 
Hope you are fine. Did you manage to create the sample app so we can start our investigation?

**Comment by rdiaa** [comment]
@hugo-retro I will be waiting for your feedback. 
@FloSugar  did you manage to check the sample app attached? is everything working fine?

**Comment by ddereszewski** [comment]
The same issue. 
React Native 0.56, latest version of your project. Maybe you can provide instruction for manual installation.

**Comment by HeshamMegid** [comment]
We have updated instructions at https://github.com/Instabug/Instabug-React-Native#installation

Please give it a try and reopen this issue if you're still having the same problem.
