### ISSUE TITLE
invoke() sometimes doesn't do anything on Android

### ISSUE THREAD

**Issue by gtchance** [Instabug/Instabug-React-Native#189]
`BugReporting.invoke()` _usually_ doesn't show anything on Android. 

For some builds it works normally. I've tested on multiple devices and emulators all on different versions. I can't narrow it down to a specific version of android.
I thought it could have something to do with the fact that I also use Fabric, but I tried with Fabric disabled. 

It appears `com.instabug.library.b.a().b(Feature.INSTABUG)` is returning `DISABLED`. 

I followed all the steps for Android integration.

```
"instabug-reactnative": "8.0.6",
"react": "16.3.1",
"react-native": "0.55.4",
```

**Comment by gtchance** [comment]
This is what I have in `getPackages()`:

```
new RNInstabugReactnativePackage.Builder(buildEnvironment.equals("MY_TOKEN",
                        MainApplication.this)
                        .setInvocationEvent("shake")
                        .setPrimaryColor("#1D82DC")
                        .build()
```

**Comment by rdiaa** [comment]
@gtchance 
Sorry for the late reply, I 'm checking it and will get back to you

**Comment by nikhilvavs** [comment]
Same issue here, BugReporting.invokeWithInvocationModeAndOptions eventually calls BugReporting.invoke() and this doesn't seem to work in release builds. In Debug builds, it is working properly.
As @gtchance mentioned, calling Instabug.enable() on app start solves this but not sure why this is needed.

**Comment by salmatarzi** [comment]
@gtchance @nikhilvavs Can you manage to send us a sample app that has this issue on, as we can't seem to reproduce it?

**Comment by rdiaa** [comment]
@nikhilvavs @gtchance 

Please feel free to reach out to us, if you ran into this issue.
