### ISSUE TITLE
BugReporting.invokeWithInvocationModeAndOptions not working

### ISSUE THREAD

**Issue by gcottrell1** [Instabug/Instabug-React-Native#190]
In my app:

```
import * as Instabug from 'instabug-reactnative';

Instabug.BugReporting.invokeWithInvocationModeAndOptions(Instabug.BugReporting.invocationMode.newFeedback, 0);
```

error: 
```
Instabug.invokeWithInvocationModeAndOptions is not a function
```

This is coming from:
https://github.com/Instabug/instabug-reactnative/blob/7d73a0a7bd7e248d84a991309983aad7308cffc9/modules/BugReporting.js#L48

When I change this to: `Instabug.invokeWithInvocationMode(invocationMode, invocationOptions);` it works as expected.

If this is the correct solution then I will submit a PR.

**Comment by rdiaa** [comment]
@gcottrell1 
we checked it and found that the `invokeWithInvocationModeAndOptions` is the right one, the only thing wrong in the mentioned API that you put 0 it should be an empty array as below:
 Instabug.BugReporting.invokeWithInvocationModeAndOptions(Instabug.BugReporting.invocationMode.newFeedback, []);

Please check it and update me

**Comment by gcottrell1** [comment]
@rdiaa  
passing an empty array in as the options still gives the error that `Instabug.invokeWithInvocationModeAndOptions` is not a function.

I passed in 0 as when using `Instabug.invokeWithInvocationMode`, if I pass in an empty array I get the error:
 ```
Expected NSNumber or NSString for IBGBugReportingInvocationOption, received NSMutableArray: ()
```

I did not want to select any of the options from the `BugReporting.invocationOptions` enum, passing in 0 worked as expected, and passing in 1 hides the email field, 2 makes the email field optional as expected from the enum.

**Comment by salmatarzi** [comment]
@gcottrell1 Can you tell me which version of instabug-reactnative are you using?

**Comment by gcottrell1** [comment]
@salmatarzi I’m using 8.0.0

**Comment by gcottrell1** [comment]
@salmatarzi @rdiaa, I have updated to 8.0.8 and am still having the issue on iOS simulator. I think this (https://github.com/Instabug/instabug-reactnative/commit/e26887acd89af752f0e3e262b4cf54a0c7a6c76b) was supposed to fix the issue I'm seeing, but I'm still seeing that `invokeWithInvocationModeAndOptions` is not a function

**Comment by gcottrell1** [comment]
@rdiaa @salmatarzi  any update?

**Comment by rdiaa** [comment]
@gcottrell1 
Can you please check this sample app? you need to run: "npm install" first before running the app.
[SampleApp.zip](https://github.com/Instabug/Instabug-React-Native/files/2294072/SampleApp.zip)

**Comment by rdiaa** [comment]
@gcottrell1 

This is a sample app where you will find instabug initialized correctly and you will find the API working

**Comment by gcottrell1** [comment]
thanks, I have now got this working 👍🏻

**Comment by rdiaa** [comment]
@gcottrell1  

Glad to hear that, We are always here for help if you have any questions
