### ISSUE TITLE
Errors when validating an iOS release build after upgrading to 8.0.0

### ISSUE THREAD

**Issue by matteodanelli** [Instabug/Instabug-React-Native#199]
### Steps to Reproduce the Problem
Update Instabug v8.0.10
Build app and try to upload into ItunesConnect

### Expected Behavior
Upload success

### Actual Behavior
The following error appears: 
_"Unsupported Architectures. The executable for MyApp.app/Frameworks/Instabug.framework contains unsupported architectures '[x86_64, i386]'."
"Invalid Mach-O Format. The Mach-O in bundle "MyApp.app/Frameworks/Instabug.framework" isn’t consistent with the Mach-O in the main bundle. The main bundle Mach-O contains armv7(bitcode) and arm64(bitcode), while the nested bundle Mach-O contains X86_64ALL(machine code). Verify that all of the targets for a platform have a consistent value for the ENABLE_BITCODE build setting."
"Invalid Segment Alignment. The app binary at 'MyApp.app/Frameworks/Instabug.framework/Instabug' does not have proper segment alignment. Try rebuilding the app with the latest Xcode version."
"The binary is invalid. The encryption info in the LC_ENCRYPTION_INFO load command is either missing or invalid, or the binary is already encrypted. This binary does not seem to have been built with Apple's linker."_

Any idea about to solve? It seems that Instabug has included architecture for both Simulator and Devices.

**Comment by matteodanelli** [comment]
I've solved putting a new build phases which launch Instabug.framework/strip_framework.sh script, as described [here](https://docs.instabug.com/docs/react-native-integration#section-ios)

**Comment by Korazy** [comment]
@matteodanelli could you do the following?
In your project navigator in XCode, select Build Phases → add New Run Script Phase → rename to run script phase to Strip Frameworks → add the following lines to your script.
`bash "${BUILT_PRODUCTS_DIR}/${FRAMEWORKS_FOLDER_PATH}/InstabugCore.framework/strip-frameworks.sh"`

**Comment by matteodanelli** [comment]
That's fixed, but I had to use ```bash "${BUILT_PRODUCTS_DIR}/${FRAMEWORKS_FOLDER_PATH}/Instabug.framework/strip-frameworks.sh"```

with `Instabug.framework` instead of `InstabugCore.framework`, since v8 changed that name.

**Comment by Korazy** [comment]
Awesome, happy to hear that. Thanks for letting me know too, I will make sure to update it in the documentation :)
