### ISSUE TITLE
Android app crash on network request failure.

### ISSUE THREAD

**Issue by nkashyap** [Instabug/Instabug-React-Native#201]
### Steps to Reproduce the Problem

Just make a `POST` request which returns nothing or `GET` which fails with no body. 

https://github.com/Instabug/Instabug-React-Native/commit/d58884a08f53294054c57ca53ee3c8a0e34bdde8#commitcomment-30416474

![screenshot_1536239431](https://user-images.githubusercontent.com/1984591/45160225-d9394580-b1e0-11e8-9e9b-a9e199b82c61.png)

### Instabug integration code
*Make sure to remove your app token.*

### SDK Version

8.0.11

### React Native, iOS and Android Versions

react-native - android only

**Comment by Korazy** [comment]
@nkashyap Thanks for pointing this out! We're currently working on a fix for this. Will keep you updated regarding it's progress.

**Comment by Korazy** [comment]
This is now fixed as of 8.0.12. Please feel free to reopen the issue if you run into it again :)
