### ISSUE TITLE
Reference Error, failing to build.

### ISSUE THREAD

**Issue by preko96** [Instabug/Instabug-React-Native#202]
For some reason after installing the package, and linking it, I can't build the project (neither release, or debug build)

```
Undefined symbols for architecture x86_64:
  "_IBGNSLogWithLevel", referenced from:
      _RNIBGLog in libRNInstabug.a(InstabugReactBridge.o)
  "_OBJC_CLASS_$_IBGBugReporting", referenced from:
      objc-class-ref in libRNInstabug.a(InstabugReactBridge.o)
  "_OBJC_CLASS_$_IBGCrashReporting", referenced from:
      objc-class-ref in libRNInstabug.a(InstabugReactBridge.o)
  "_OBJC_CLASS_$_IBGFeatureRequests", referenced from:
      objc-class-ref in libRNInstabug.a(InstabugReactBridge.o)
  "_OBJC_CLASS_$_IBGLog", referenced from:
      objc-class-ref in libRNInstabug.a(InstabugReactBridge.o)
  "_OBJC_CLASS_$_IBGNetworkLogger", referenced from:
      objc-class-ref in libRNInstabug.a(InstabugReactBridge.o)
  "_OBJC_CLASS_$_IBGSurveys", referenced from:
      objc-class-ref in libRNInstabug.a(InstabugReactBridge.o)
  "_OBJC_CLASS_$_Instabug", referenced from:
      objc-class-ref in libRNInstabug.a(InstabugReactBridge.o)
     (maybe you meant: _OBJC_CLASS_$_InstabugReactBridge)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

```
<img width="278" alt="screen shot 2018-09-13 at 09 56 11 am" src="https://user-images.githubusercontent.com/35433203/45478191-45fd9400-b73b-11e8-90ca-3000955265f8.png">

### Steps to Reproduce the Problem
Follow the installation steps. (expect use yarn instead of npm)

### Expected Behaviour
Building the project without error.

### Actual Behaviour
After linking the library I cant build down the project

### React Native, iOS and Android Versions

RN Version: 0.55.2
IBRN Version: 8.0.12

### Additional informations
I've using React Native Navigation what changing the AppDelegate.m a little bit.

**Comment by Korazy** [comment]
Hey @preko96 

Thanks for reaching out. For some reason it seems that the framework was not added to the embedded frameworks. Can you please try removing the Instabug framework, cleaning, then adding it again?

**Comment by Korazy** [comment]
@preko96 did it work for you?

**Comment by Korazy** [comment]
Please feel free to reopen this issue if you run into it again.

**Comment by thefaj** [comment]
I've got this same issue. Removed the Instabug framework (libRNInstabug.a), cleaned, re-added. Unfortunately, the same issue is happening for us.
