### ISSUE TITLE
I can't get Instabug to work on iOS, everything works on Android

### ISSUE THREAD

**Issue by DenisFrezzato** [Instabug/Instabug-React-Native#206]
I can't get Instabug to work on iOS invoking `Instabug.invokeWithInvocationMode(Instabug.invocationMode.chatsList)` and `Instabug.invokeWithInvocationMode(Instabug.invocationMode.newBug)`. On Android everything works fine.

I also tried `Instabug.setInvocationEvent(Instabug.invocationEvent.floatingButton)`: the button is displayed but nothing happens on press.

Obviously I'm missing something. Can you help me?

react-native 0.55
instabug-reactnative 8.0.12
iOS 11

Here is the application repository https://github.com/teamdigitale/italia-app.

**Comment by Korazy** [comment]
Hey @DenisFrezzato 

Thanks for reaching out. Just to make sure, do you call startWithToken first?

**Comment by DenisFrezzato** [comment]
@Korazy Yes, `startWithToken` is called at mount time inside the root component.

**Comment by DenisFrezzato** [comment]
Updating to 8.0.14 resolved that.

**Comment by Korazy** [comment]
Im happy to hear that, please don't hesitate to reach out if you have any other issues :)
