### ISSUE TITLE
iOS - undefined is not an object (evaluating 'Instabug.invocationEventNone')

### ISSUE THREAD

**Issue by gawrysiak** [Instabug/Instabug-React-Native#207]
### Steps to Reproduce the Problem

I have added instabug-reactnative to an existing project with the standard installation process. Android works alright, while iOS crashes. I'm using React Native 0.57. project.pbxproj seems to be updated properly by react-native link. Any advices?

### Expected Behavior

Not to crash :)

### Actual Behavior

<img width="364" alt="screen shot 2018-10-08 at 15 23 01" src="https://user-images.githubusercontent.com/7827311/46611431-16f5fa80-cb0e-11e8-8b0e-0e0ef12135a7.png">

### Instabug integration code

No actual code used, crashes after adding the JavaScript import:
```import Instabug from 'instabug-reactnative';```

### React Native, iOS and Android Versions

RN 0.57.0
iOS 12
instabug-rn 8.0.14

### Device Model

Simulator iPhone 6/XR

**Comment by HeshamMegid** [comment]
@gawrysiak, just letting you know that we're looking into this. Will get back to you once we have a fix.

**Comment by salmamali** [comment]
@gawrysiak, This error appears when the library is not linked. Make sure that when you run `react-native link instabug-reactnative`, it passes with no errors.

**Comment by HeshamMegid** [comment]
Closing this for now. @gawrysiak please feel free to reopen if you're still seeing the same issue after linking Instabug.

**Comment by gawrysiak** [comment]
Like I mentioned before, it was linked properly (no errors) and Android worked okay. But I got an iOS dev on it to handle it within xcode, so while it works now, I'm not sure what was the issue. Anyway, if the problem doesn't happen for others, it's safe to close :+1:

**Comment by hiddentao** [comment]
I am seeing this issue now. `react-native link` ran fine.

**Comment by akahnn** [comment]
Same issue, @gawrysiak can you elaborate on the the xcode fix?

**Comment by burivuhster** [comment]
I have the same issue, 'react-native link' ran without any errors.
My project is ejected from Expo and using ExpoKit, maybe this will help.

**Comment by HeshamMegid** [comment]
@sinewave440hz to be able to help you, can you please open a new issue with the details of the steps you've taken to end up with this Podfile?

**Comment by HeshamMegid** [comment]
I've locked the discussion on this issue. If any of you are still having this problem, please open a new issue.
