### ISSUE TITLE
FileNotFoundException on Android OS Level 25 ASUS_X00ID

### ISSUE THREAD

**Issue by watadarkstar** [Instabug/Instabug-React-Native#208]
Might be related to #119 which was closed and never solved.

### Steps to Reproduce the Problem

Upon installing this library within my RN application, I managed to get everything working fine on iOS however on Android, upon the submission of bug reports, I'm receiving a java.io.FileNotFoundException when it seems to try and fetch the screenshot of the bug report. Stack trace below: 

Android OS Level 25 ASUS_X00ID. 

### Expected Behavior

No exception.

### Actual Behavior

Exception:

```
16:21:03  E/SpannableStringBuilder(25220): SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
16:21:03  E/SpannableStringBuilder(25220): SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
16:21:10  W/System.err(25220): java.io.FileNotFoundException: /storage/emulated/0/Android/data/com.flyreel.underwriterbot/files/instabug/attachments/bug_1539188440248_.jpg (No such file or directory)
16:21:10  W/System.err(25220): 	at java.io.FileInputStream.open(Native Method)
16:21:10  W/System.err(25220): 	at java.io.FileInputStream.<init>(FileInputStream.java:146)
16:21:10  W/System.err(25220): 	at com.instabug.library.util.BitmapUtils$1.run(BitmapUtils.java:111)
16:21:10  W/System.err(25220): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
16:21:10  W/System.err(25220): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
16:21:10  W/System.err(25220): 	at com.instabug.library.util.threading.b$1.run(PriorityThreadFactory.java:28)
16:21:10  W/System.err(25220): 	at java.lang.Thread.run(Thread.java:761)
```

### Instabug integration code

JS:
```
    Instabug.startWithToken(env.INSTABUG_IOS_TOKEN, [
      Instabug.invocationEvent.shake
    ]);
    Instabug.setWelcomeMessageMode(Instabug.welcomeMessageMode.disabled); // Disable welcome message
```

MainApplication.java:
```
new RNInstabugReactnativePackage.Builder("token",MainApplication.this)
							.setInvocationEvent("shake")
							.setPrimaryColor("#1D82DC")
							.setFloatingEdge("left")
							.setFloatingButtonOffsetFromTop(250)
							.build(),
````

### SDK Version

"instabug-reactnative": "^8.0.14",

### React Native, iOS and Android Versions

"instabug-reactnative": "^8.0.14",

### Device Model

asus ASUS_X00ID
OS Level 25

### [Optional] Project That Reproduces the Issue

![screen shot 2018-10-10 at 1 07 16 pm](https://user-images.githubusercontent.com/3059371/46753505-0bc9d880-cc8e-11e8-9fbb-7ee2c4c6162b.png)

**Comment by watadarkstar** [comment]
Also happens on a:

samsung SM-G610M
OS Level 23

**Comment by Korazy** [comment]
Hey @watadarkstar 

Thanks for reaching out, we'll look into this and get back to you :)

**Comment by Korazy** [comment]
Hey again,

We created a custom build for you and we were wondering if you can try and see if it fixes the issue. You can install it by running
`npm install https://github.com/Instabug/Instabug-React-Native#fix/bitmap-crash-issue`
You should also add the following to your project level gradle as well
```
allprojects {
repositories {
mavenLocal()
jcenter()
maven
{ // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm url "$rootDir/../node_modules/react-native/android" }

maven
{ url 'https://maven.google.com/' name 'Google' }

// ADD THIS TO USE SNAPSHOTS
maven
{ url "https://oss.sonatype.org/content/repositories/snapshots" }

}
}
```

**Comment by watadarkstar** [comment]
@Korazy Give me until the end of the week and I will look into it 👍 send me a message Friday to check in :)

**Comment by Korazy** [comment]
Sure thing, @watadarkstar! Take your time :)

**Comment by watadarkstar** [comment]
@Korazy Also happy to zoom / video chat while you walk me through what i should do to get the snapshot working. 😄

**Comment by Korazy** [comment]
Hey @watadarkstar 

Im very sorry for the delay. Of course we can try a call, but before that, can you try adding only this to your gradle file inside repositories?
```
maven
{ url "https://oss.sonatype.org/content/repositories/snapshots" }```

then running:
```npm install https://github.com/Instabug/Instabug-React-Native#fix/bitmap-crash-issue```

**Comment by Korazy** [comment]
@watadarkstar hope you're great. Is everything working now?

**Comment by Korazy** [comment]
Please feel free to reopen the issue if you run into it again.
