### ISSUE TITLE
setPromptOptionsEnabled not working on Android

### ISSUE THREAD

**Issue by koyin** [Instabug/Instabug-React-Native#214]
### Expected Behavior
To disable the "Talk to us" option from the menu

### Actual Behavior
"Talk to us" option still displaying on Android (no problem on iOS)

### Instabug integration code
`Instabug.startWithToken('TOKEN', [Instabug.invocationEvent.shake]);`
`Instabug.setChatNotificationEnabled(false);`
`BugReporting.setPromptOptionsEnabled(false, true, true);`

### SDK Version
8.0.17

### React Native, iOS and Android Versions
RN 0.55.4

**Comment by Korazy** [comment]
Hey @koyin 

Thanks for reaching out with this, we will investigate it and get back to you.

**Comment by Korazy** [comment]
We are unable to reproduce this at the moment. Can you please let me know if you added your token in the MainApplication.java class and after doing so, did you try deleting the app from your device before installing again?

**Comment by Korazy** [comment]
Please feel free to reopen the issue should it occur again :)
