### ISSUE TITLE
Why is Jacoco a hard dependency for Android SDK? 

### ISSUE THREAD

**Issue by cpetzel** [Instabug/Instabug-React-Native#215]
Your [SDK](https://mvnrepository.com/artifact/com.instabug.library/instabug/8.0.11) ships with a dependency on jacoco (code coverage unit testing library, typically only used for internal testing). This bloats the size of the SDK and it is executing unnecessary code on your client's apps. 

### Steps to Reproduce the Problem

Exclude the jacoco agent from a project, and it crashes on app boot. 

```
    compile project(':instabug-reactnative')){
        exclude group: 'org.jacoco'
    }
```

Please don't include test only code in production SDKs

### Expected Behavior
App doesn't crash when build.gradle excludes test only dependencies

### Actual Behavior
App Crashes on app boot.

```
java.lang.NoClassDefFoundError Failed resolution of: Lorg/jacoco/agent/rt/internal_8ff85ea/Offline; 
    Unknown:12 com.instabug.library.invocation.util.InstabugFloatingButtonEdge.$jacocoInit
    Unknown com.instabug.library.invocation.util.InstabugFloatingButtonEdge.<clinit>
    RNInstabugReactnativePackage.java:149 com.instabug.reactlibrary.RNInstabugReactnativePackage$Builder.getFloatingButtonEdge
    RNInstabugReactnativePackage.java:135 com.instabug.reactlibrary.RNInstabugReactnativePackage$Builder.setFloatingEdge
    MainApplication.java:109 co.scoot.scootapp.MainApplication$1.getPackages
    ReactNativeHost.java:76 com.facebook.react.ReactNativeHost.createReactInstanceManager
```

### SDK Version
latest

**Comment by Korazy** [comment]
@cpetzel thanks for reaching out!

We're looking into a fix for this at the moment. I will let you know what we find.

**Comment by Korazy** [comment]
We’ve created a snapshot for you that should resolve this issue.

The custom build should be installed as follows 

npm install --save https://github.com/Instabug/Instabug-React-Native/tree/customBuild/snapshot_8.0.11.11

The following line should be added to the project level gradle:

allprojects {
    repositories {
        mavenLocal()
        jcenter()
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url "$rootDir/../node_modules/react-native/android"
        }
        maven {
            url 'https://maven.google.com/'
            name 'Google'
        }
        // ADD THIS LINE TO USE THE CUSTOM BUILD
        maven {
            url "https://oss.sonatype.org/content/repositories/snapshots"
        }
    }
}
 Please let me know if it works.

**Comment by Korazy** [comment]
Please feel free to reopen the issue should it occur again :)

**Comment by cpetzel** [comment]
Sorry for the delay. I was able to test to verify that this works. 

I don't see the jacoco dependency on my classpath, and the SDK is able to start successfully. 

Did this get merged into a release? 

![image](https://user-images.githubusercontent.com/2036206/48745848-f0a19f80-ec21-11e8-82d4-c67417ae256e.png)

**Comment by Korazy** [comment]
It’s not quite released as of yet, but should hopefully be out in 2 weeks.
