### ISSUE TITLE
8.0.17 missing iOS framework

### ISSUE THREAD

**Issue by peacechen** [Instabug/Instabug-React-Native#216]
### Steps to Reproduce the Problem

Installing instabug-reactnative 8.0.17 from npm does not include the `ios/RNInstabug.xcodeproj` or `ios/Instabug.framework` folders.  Only the `ios/RNInstabug` folder exists.

`npm install instabug-reactnative`

### Expected Behavior

Build success

### Actual Behavior

Instabug framework not found

### Instabug integration code
Instabug.startWithToken(INSTABUG_KEY, [Instabug.invocationEvent.shake]);

### React Native, iOS and Android Versions
RN 0.56.2
iOS 10

### Device Model
iPhone XR

**Comment by peacechen** [comment]
Oddly, removing the folder node_modules/instabug-reactnative folder and npm installing it again brought it down.  I had completely wiped the node_modules folder before, so it couldn't have been caused by a prior version.  npm must have flaked out.

**Comment by ZiadAyman** [comment]
Hey @peacechen. So, is everything okay now? Let me know if we could be of any help please.

**Comment by peacechen** [comment]
Thanks @ZiadAyman .  It's building now after repairing the mysteriously broken node_modules/instabug-reactnative/ios folder
