### ISSUE TITLE
could you guys help to define the typescript interface?

### ISSUE THREAD

**Issue by pengcao1** [Instabug/Instabug-React-Native#221]
Hi team：

Could you guys help to define the typescript declare in to [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped) ?

**Comment by salmamali** [comment]
Hello @pengcao1 
We will be working on this for a future release.

**Comment by VincentLanglet** [comment]
Hey @pengcao1 
I started it a long time ago here : https://github.com/Instabug/Instabug-React-Native/pull/159

**Comment by salmamali** [comment]
Hello @pengcao1 
We've added the typescript interface to our library as of version 8.1.1.
