### ISSUE TITLE
There are difference between source code and guide doc

### ISSUE THREAD

**Issue by pengcao1** [Instabug/Instabug-React-Native#222]
Hi team:

as guide doc. we can follow below steps to enable repro steps. 
but, I found that the source code does not export the interface to do this config.
`.setReproStepsState(State.ENABLED) `

https://docs.instabug.com/docs/android-logging#section-visual-repro-steps

and below code snippet  in `RNInstabugReactnativePackage` constructor

```

        mInstabug = new Instabug.Builder(this.androidApplication, this.mAndroidApplicationToken)
                .setInvocationEvents(this.invocationEvents.toArray(new InstabugInvocationEvent[0]))
                .setCrashReportingState(Feature.State.ENABLED)
                .setReproStepsState(State.DISABLED)
                .build();
```

**Comment by salmamali** [comment]
Hello @pengcao1 
You can enable repro steps by adding
`Instabug.setReproStepsMode(Instabug.reproStepsMode.enabled)`
to your js code. 
Is this what you're looking for?

**Comment by pengcao1** [comment]
thank you.
and what's the difference between `setUserStepsEnabled` and `setReproStepsMode `

**Comment by salmamali** [comment]
```setReproStepsMode``` will show you a visual representation of the steps the user has taken. So on your dashboard under each view you will see what actions the user did. ```setUserStepsEnabled``` will also show all the actions the user has taken but without the visual representation.

**Comment by salmamali** [comment]
Will close this now, please feel free to reopen this issue if you still have any questions.
