### ISSUE TITLE
xcodebuild failure:  error: exportArchive: Code signing "Instabug.framework" failed.

### ISSUE THREAD

**Issue by techopsway2b1** [Instabug/Instabug-React-Native#224]
### Steps to Reproduce the Problem
**Running xcodebuild export command:**
xcodebuild -exportArchive -archivePath $PWD/build/mobile-pipeline.xcarchive -exportOptionsPlist exportOptions.plist -exportPath $PWD/build

**using exportOptions.plist settings:**
\<?xml version="1.0" encoding="UTF-8"?\>
\<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd"\>
\<plist version="1.0"\>
\<dict\>
    \<key>method\</key>
    \<string>app-store\</string>
    \<key>provisioningProfiles\</key>
    \<dict>
        \<key>com.foo.bar\</key>
       \ <string>XXXXXXXXXXXXXXX\</string>
    \</dict>
    \<key>signingCertificate\</key>
    \<string>iPhone Distribution\</string>
    \<key>signingStyle\</key>
    \<string>manual\</string>
   \<key>stripSwiftSymbols\</key>
    \<true/>
    \<key\>teamID\</key>
    <string\>XXXXXXXXXXX</string>
    \<key\>uploadBitcode</key>
    \<true/\>
    \<key\>uploadSymbols</key>
    \<true/\>
\</dict\>
\</plist\>

### Expected Behavior
Export happens successfully.

### Actual Behavior
**When attempting to export a xcodebuild archive we are running into the following error:**
macosbuildserver:ios mobileserverr$ xcodebuild -exportArchive -archivePath $PWD/build/mobile-pipeline.xcarchive -exportOptionsPlist exportOptions.plist -exportPath $PWD/build
2018-11-27 13:31:33.284 xcodebuild[95063:5694256] [MT] IDEDistribution: -[IDEDistributionLogging _createLoggingBundleAtPath:]: Created bundle at path '/var/folders/fc/5b5g61r91l3gts75956k0mlw0000gv/T/XXXXXXXX_2018-11-27_13-31-33.283.xcdistributionlogs'.
2018-11-27 13:31:41.512 xcodebuild[95063:5694256] [MT] IDEDistribution: Step failed: <IDEDistributionPackagingStep: 0x7f96e46f26c0>: Error Domain=IDEDistributionPipelineErrorDomain Code=0 "Code signing "Instabug.framework" failed." UserInfo={NSLocalizedDescription=Code signing "Instabug.framework" failed., NSLocalizedRecoverySuggestion=View distribution logs for more information.}
error: exportArchive: Code signing "Instabug.framework" failed.

Error Domain=IDEDistributionPipelineErrorDomain Code=0 "Code signing "Instabug.framework" failed." UserInfo={NSLocalizedDescription=Code signing "Instabug.framework" failed., NSLocalizedRecoverySuggestion=View distribution logs for more information.}

** EXPORT FAILED **

### Instabug integration code (Problem is most likely not here, its during the build's archive export phase)
    @observable instabugEnabled = false;

    @action initialize = () => Instabug.startWithToken(INSTABUG_TOKEN, [Instabug.invocationEvent.shake]);

    @action setInstabugEnabled = bool => (this.instabugEnabled = bool);

    setInstagbugUserId(userId) {
        try {
            if (this.instabugEnabled) Instabug.setUserAttribute("user_id", String(userId));
        } catch (err) {
            console.error("Failed to set user attribute", err);
        }
    }

    warn() {
        const payloadString = this.stringifyArguments(arguments);
        if (this.instabugEnabled) {
            Instabug.logWarn(payloadString);
        } else {
            console.warn(payloadString); // eslint-disable-line no-console
        }
    }

    info() {
        const payloadString = this.stringifyArguments(arguments);
        if (this.instabugEnabled) {
            Instabug.logInfo(payloadString);
        } else {
            console.info(payloadString); // eslint-disable-line no-console
        }
    }

    log() {
        const payloadString = this.stringifyArguments(arguments);
        if (this.instabugEnabled) {
            Instabug.logVerbose(payloadString);
        } else {
            console.log(payloadString); // eslint-disable-line no-console
        }
    }

    error() {
        const payloadString = this.stringifyArguments(arguments);
        if (this.instabugEnabled) {
            Instabug.reportJSException(new Error(payloadString));
        } else {
            console.error(payloadString); // eslint-disable-line no-console
        

### SDK Version
Xcode 9.4.1

### React Native, iOS and Android Versions
"react": "16.3.1",
"react-native": "0.55.4",

Issue is not on iOS side.

### Device Model
Generic iOS Device

**Comment by salmamali** [comment]
Hello @techopsway2b1,
The issue is that iOS frameworks are always signed with iOS developer and then will be resigned by the developer again. Could you please make sure that Any iOS SDK is signed in the Build Settings -> Signing section.

**Comment by techopsway2b1** [comment]
Thank you!!  You were very close to the issue.  We dont use the iOS Developer profile but use the iOS Distribution Profiles.  The Code Signing Identity for Release was set to Don't Code Sign and Any iOS SDK was set to iOS Distribute.  When I changed the Release setting to iOS Distribute it solved the problem.  Please close this ticket and thank you so much!!!
