### ISSUE TITLE
Manually invoking feedback reporter crashes on android

### ISSUE THREAD

**Issue by ylac** [Instabug/Instabug-React-Native#225]
### Steps to Reproduce the Problem
Try to invoke Instabug feedback reporter manually in debug/release mode.

### Expected Behavior
Feedback reporter opens.

### Actual Behavior
Get red screen of death with error: 

`Attempt to invoke interface method 'int com.facebook.react.bridge.ReadableArray.size()' on a null object reference`

### Instabug integration code
```
new RNInstabugReactnativePackage.Builder("[redacted]",MainApplication.this)
							.setInvocationEvent("none")
							.setPrimaryColor("#1D82DC")
							.setFloatingEdge("left")
							.setFloatingButtonOffsetFromTop(250)
							.build()
```

### SDK Version
8.0.19
### React Native, iOS and Android Versions
0.55. Android 7.0, 8.0
### Device Model
Samsung Galaxy S6 7.0 (physical), Nexus 5x 8.0 (simulator)

**Comment by salmamali** [comment]
Hello @ylac 
We can't seem to reproduce this issue. How exactly are you trying to invoke the feedback view? And are you invoking it in a button?

**Comment by ylac** [comment]
@salmamali Hi, yes I'm invoking it on a button press as below:

> onPress={() => BugReporting.invokeWithInvocationModeAndOptions(BugReporting.invocationMode.newFeedback)}

**Comment by salmamali** [comment]
@ylac 
You need to add the second param needed by the method. If you have no options to add just add an empty array. It should look as follows:
`BugReporting.invokeWithInvocationModeAndOptions(BugReporting.invocationMode.newFeedback, [])`
