### ISSUE TITLE
PreInvocationHandler callback not called when only BugReporting configured

### ISSUE THREAD

**Issue by cpetzel** [Instabug/Instabug-React-Native#226]
### Steps to Reproduce the Problem

This problem only happens on Android.

configure the application to only enable BugReporting 
```javascript
// Arguments: chat, bug, feedback
Instabug.setPromptOptionsEnabled(false, true, false);
```

Then configure a `preInvocationHandler`
```javascript
Instabug.setPreInvocationHandler(() => {
   console.log('testing');
  Instabug.logUserEventWithNameAndParams("test", {
    test: "hi" 
  });
});
```

Now invoke instabug (via floating button, or whatever method)

### Expected Behavior

The pre invocation callback is hit so I can attach a user event. I would see `testing` in the console output. I would also see the `test` object attached as a user event

### Actual Behavior

The pre invocation callback is NOT called. I do not see `testing` in the console output. I do not see the `test` object attached as a user event on the instabug dashboard

If I simply remove this code, then it works 
```
Instabug.setPromptOptionsEnabled(false, true, false);
```

 
### SDK Version
We are maintaining a fork
https://github.com/scootnetworks/instabug-reactnative/blob/master/package.json
8.0.18

### React Native, iOS and Android Versions
RN 57.4

### Device Model
google pixel

**Comment by salmamali** [comment]
Hello @cpetzel 
We'll be looking into the issue and get back to you.

**Comment by salmamali** [comment]
Hello @cpetzel 
Could you try migrating your code to SDK v8.0 using the following guide [Instabug SDK v8.0 Migration](https://docs.instabug.com/docs/react-native-migration-guide)

**Comment by HeshamMegid** [comment]
@cpetzel closing this issue since we haven't heard back from you. Please feel free to reopen.

**Comment by cpetzel** [comment]
Thanks for the fix! It works.
