### ISSUE TITLE
Instabug options not working running on Xcode or AppCenter

### ISSUE THREAD

**Issue by eduardborges** [Instabug/Instabug-React-Native#229]
### Steps to Reproduce the Problem
Run a project clicking the play button on Xcode or building the app with a CI tool.

### Expected Behavior
* Use the dark theme
* Make the email field optional
* Only enable the bug report feature

### Actual Behavior
Everything works using `react-native run-ios` on my local machine, but when I run the app using Xcode or App Center Instabug seems to not care about my set up. It shows up with the light theme, with all the options enabled, and the email field is required.

### Instabug integration code
`if (Platform.OS === 'ios') {
    Instabug.isRunningLive((isLive) => {
      if (isLive) {
        Instabug.startWithToken(RN_INSTABUG_KEY, [Instabug.invocationEvent.none]);
      } else {
        Instabug.startWithToken(RN_INSTABUG_KEY, [Instabug.invocationEvent.shake]);
      }
    });
    Instabug.setPrimaryColor(processColor(Colors.primaryColor));
  }
  Instabug.setColorTheme(Instabug.colorTheme.dark);
  Instabug.setWelcomeMessageMode(Instabug.welcomeMessageMode.beta);
  BugReporting.setInvocationOptions([BugReporting.invocationOptions.emailFieldOptional]);
  BugReporting.setPromptOptionsEnabled(false, true, false);`

### SDK Version
8.0.20

### React Native, iOS and Android Versions
React Native: 0.57.8
iOS: 12.1

### Device Model
iPhone XS Simulator
iPhone XS

### [Optional] Project That Reproduces the Issue

**Comment by HeshamMegid** [comment]
@eduardborges that's odd. Let us check it and get back to you.

**Comment by salmamali** [comment]
@eduardborges Could you try changing your code to look like this
```if (Platform.OS === 'ios') {
      Instabug.isRunningLive(isLive => {
        if (isLive) {
          Instabug.startWithToken(RN_INSTABUG_KEY, [
            Instabug.invocationEvent.none
          ]);
        } else {
          Instabug.startWithToken(RN_INSTABUG_KEY, [
            Instabug.invocationEvent.shake
          ]);
        }
        Instabug.setPrimaryColor(processColor(Colors.primaryColor));

        Instabug.setColorTheme(Instabug.colorTheme.dark);
        Instabug.setWelcomeMessageMode(Instabug.welcomeMessageMode.beta);
        BugReporting.setInvocationOptions([
          BugReporting.invocationOptions.emailFieldOptional
        ]);
        BugReporting.setPromptOptionsEnabled(false, true, false);
      });
    }
```
The reason this is happening is because the `isRunningLive` callback is called after the rest of your integration code that is on the main thread which causes these APIs to be called before Instabug is initialized. Moving them inside the callback will solve the issue.

**Comment by eduardborges** [comment]
It works. Thanks!
