### ISSUE TITLE
Error when building android app - Android dependency ...

### ISSUE THREAD

**Issue by maxweb4u** [Instabug/Instabug-React-Native#230]
### Steps to Reproduce the Problem

1. react-native init Awesome
2. cd Awesome
3. yarn add instabug-reactnative
4. yarn start
5. Go to Android studio and do steps that described here https://docs.instabug.com/docs/react-native-integration in Manual Linking, Android version
6. Sync Gradle - success
7. build project - get an error: 
`Android dependency 'com.android.support:appcompat-v7' has different version for the compile (27.1.1) and runtime (28.0.0) classpath. You should manually set the same version via DependencyResolution`

I've attached an example project.
[Awesome.zip](https://github.com/Instabug/Instabug-React-Native/files/2706315/Awesome.zip)

**Comment by HeshamMegid** [comment]
@maxweb4u, we're looking into the issue and we'll get back to you soon.

**Comment by maxweb4u** [comment]
@salmamali Thanks it's working. However after updating version to 28 I had to include `multiDexEnabled true` in my current project.

**Comment by HeshamMegid** [comment]
@maxweb4u thanks for letting us know. We will update our docs to include the multidex part.

**Comment by sinewave440hz** [comment]
In my case we are using buildToolsVersion 28.0.3 so I used the following: 

```
    ext {
        buildToolsVersion = "28.0.3"
        minSdkVersion = 19
        compileSdkVersion = 28
        targetSdkVersion = 26
        supportLibVersion = "28.0.0"
    }
```

This results in:
```
Android dependency 'com.android.support:transition' has different version for the compile (27.1.0) and runtime (28.0.0) classpath. You should manually set the same version via DependencyResolution
```

or any of several other com.android.support: dependencies, it varies. 

I tried upping minSdkVersion to 21 and setting multiDexEnabled to true, but no change. Any idea how to move forward? Can create a new issue if you prefer, of course.

**Comment by salmamali** [comment]
@sinewave440hz Update the SDK to the latest which uses supportLibVersion 28.0.0. If you are already using the latest, then there must be another dependency besides Instabug that is causing the conflict.

**Comment by sinewave440hz** [comment]
The thing is that this only happens when I have installed and linked Instabug. Do you mean the compile or target SDK, and how do I find out which SDK uses supportLibVersion 28.0.0 if it's okay to pose that question here? Thanks!

**Comment by sinewave440hz** [comment]
Still stuck on this, I've tried all sdk combinations from 26-28 and none work. I would like to upgrade to AndroidX but I can't because another package I use has not updated to AndroidX yet. At this stage, my only choice is find the solution in this issue or rollback and not use Instabug until the other package in question updates to AndroidX. Seems a bit unnecessary :(

**Comment by salmamali** [comment]
@sinewave440hz Which version of instabug-reactnative are you on?

**Comment by sinewave440hz** [comment]
The latest 8.0.21 now, previously 8.0.20. Same issue.

**Comment by salmamali** [comment]
@sinewave440hz These versions map to the native Android SDK version 8.0.12 which uses API level 28 and buildToolsVersion 28.0.3 so I'm not sure what could be the issue and we cannot reproduce it from our end. Would it be possible to send a simple sample app that has this issue?

**Comment by sinewave440hz** [comment]
Hi, thanks for you response :) I can't repro from a clean project either (was about to build you a sample app) so I guess it's something for us to deal with internally.
