### ISSUE TITLE
Testing with Jest

### ISSUE THREAD

**Issue by soumyamishra89** [Instabug/Instabug-React-Native#232]
When i run tests, I get the following error

TypeError: Cannot read property 'invocationEventNone' of undefined

It seems i need to mock instabug for testing. Is there any mock example provided ?

React-native: 0.57.8

**Comment by HeshamMegid** [comment]
Can you give more context about what you're trying to do? How does your test look like and how does it involve Instabug?

**Comment by soumyamishra89** [comment]
@HeshamMegid I managed to mock instabug as per my requirement. Thanks.

**Comment by SudoPlz** [comment]
@soumyamishra89 can you please paste the first lines of your test file? I'd like to mock instabug as well.

Thank you

**Comment by soumyamishra89** [comment]
@SudoPlz create a file by name of instabug-reactnative.js in __mocks__ folder (same level as __tests__ folder)

`const BugReporting = {
    onSDKDismissedHandler: jest.fn(),
    setReportTypes: jest.fn(),
    reportType: {},
    showWithOptions: jest.fn(),
    option: {}
};

const Replies = {
    setInAppNotificationsEnabled: jest.fn(),
    setOnNewReplyReceivedCallback: jest.fn((callback) => null),
    show: jest.fn(),
    getUnreadRepliesCount: jest.fn(() => Promise.resolve(0))
}

const Chats = {
    setEnabled: jest.fn(),
    show: jest.fn()
}

export {
    BugReporting,
    Replies,
    Chats
}

export default {
    startWithToken: jest.fn(),
    setChatNotificationEnabled: jest.fn(),
    invocationEvent: {},
    BugReporting,
    Replies,
    Chats
};`

i use this as my mock file content.

**Comment by soumyamishra89** [comment]
@soumyamishra89 the error you are getting is different. It is because the babel-jest does a transformation of your code into a format it understands i guess and because of this the error occurs.
If you mock the file then it should solve the issue but in case you face the same issue for other modules which does not require mock then maybe you need to look into jest configuration ("transformIgnorePatterns")

**Comment by SudoPlz** [comment]
@soumyamishra89 I've wasted hours digging into this, but because we're stuck . on react-native 0.56, I can't find the correct combination of babel-jest or presets, so I just quit...... until we upgrade to a newer react-native version, where the correct babel dependencies are required by react-native, and not some alpha stage dependencies that we're stuck with..
