### ISSUE TITLE
64 bit native library

### ISSUE THREAD

**Issue by malonguwa** [Instabug/Instabug-React-Native#236]
Google Play will start to ONLY accept 64-bit version android App if there is any native code in the project after Aug 2019:
https://android-developers.googleblog.com/2017/12/improving-app-security-and-performance.html

Does this Instabug-react-native lib is in 32-bit? or 64-bit? I am still new to the android, the react native 0.58 will included the support of 64-bit version of react native app, does this Instabug-react-native will be able to provide 64-bit version, so we can able to keep using this lib after 2019 Aug - Google Play's new policy?

I checked the instabug-reactnative's build.gradle file in my react native android project, I saw this 
```
android {
    compileSdkVersion rootProject.hasProperty('compileSdkVersion') ? rootProject.compileSdkVersion : DEFAULT_COMPILE_SDK_VERSION
    buildToolsVersion rootProject.hasProperty('buildToolsVersion') ? rootProject.buildToolsVersion : DEFAULT_BUILD_TOOLS_VERSION

    defaultConfig {
        minSdkVersion 23
        targetSdkVersion rootProject.hasProperty('targetSdkVersion') ? rootProject.targetSdkVersion : DEFAULT_TARGET_SDK_VERSION
        versionCode 1
        versionName "1.0"
        ndk {
            abiFilters "armeabi-v7a", "x86"
        }
    }
    lintOptions {
       warning 'InvalidPackage'
    }
}

dependencies {
    implementation 'com.facebook.react:react-native:0.20.+'
    implementation ('com.instabug.library:instabug:8.0.12'){
        exclude group: 'com.android.support:appcompat-v7'
    }
}
```
```
        ndk {
            abiFilters "armeabi-v7a", "x86"
        }
```
ndk with abiFilters "armeabi-v7a", "x86", Is this mean the instabug-reactnative only has 32-bit native code/lib?

**Comment by HeshamMegid** [comment]
We support both 32 and 64-bit architectures on the latest Android SDK, which wil be available on React Native in a few days.
