### ISSUE TITLE
Visual Repo Steps Compile fail 

### ISSUE THREAD

**Issue by viperfx** [Instabug/Instabug-React-Native#241]
### Steps to Reproduce the Problem
When adding the follow code to activity 

```
@Override
public boolean dispatchTouchEvent(MotionEvent ev) {
	InstabugTrackingDelegate.notifyActivityGotTouchEvent(ev, this);
	return super.dispatchTouchEvent(ev);
}
```

Following the docs here - https://docs.instabug.com/docs/react-native-logging#section-visual-repro-steps
### Expected Behavior
To compile correctly based on docs
### Actual Behavior
Compile fails because the docs are missing imports.

Added the following imports
```
import android.view.MotionEvent;
import com.instabug.library.InstabugTrackingDelegate;
```
### Instabug integration code
```
new RNInstabugReactnativePackage.Builder("TOKEN", MainApplication.this).setInvocationEvent("shake").build()
```

### SDK Version

"instabug-reactnative": "^8.0.23",
### React Native, iOS and Android Versions
Android
```
ext {
    buildToolsVersion = "27.0.3"
    minSdkVersion = 16
    compileSdkVersion = 27
    targetSdkVersion = 26
    supportLibVersion = "27.1.1"
}
```
React Native
```
 "react-native": "0.57.3",
```

**Comment by salmamali** [comment]
@viperfx 
This was fixed in a custom build. You can install it by running
```
npm install --save https://github.com/Instabug/Instabug-React-Native#customBuild/snapshot_8.0.15.9
```
You need to add the following to your project level build.gradle under allProjects -> repositories

```
maven {
url "https://oss.sonatype.org/content/repositories/snapshots"
}
```
The fix will be officially released with the next android SDK release.

**Comment by viperfx** [comment]
@salamamali can you confirm the correct imports ?

**Comment by salmamali** [comment]
@viperfx  The correct imports were the ones you were using
```
import com.facebook.react.ReactActivity;
import com.instabug.library.InstabugTrackingDelegate;
```
