### ISSUE TITLE
Multiple commands produce ... Instabug.framework

### ISSUE THREAD

**Issue by plowman** [Instabug/Instabug-React-Native#242]
### Steps to Reproduce the Problem
1. `yarn install instabug-reactnative`
2. `react-native link instabug-reactnative`
    * Note: this step updates my project's Podfile
3. `pod install`
    * Note: before doing a pod install, the error I get is on the line of code, `Instabug.invocationEvent.shake,`, and reads: "Unhandled JS Exception: undefined is not an object (evaluating 'Instabug.invocationEventNone')"
4. Build the app for iOS, either in xcode or via the react-native `cli.js` tool.

### Expected Behavior
* It should build without errors.

### Actual Behavior
* I get the following error when trying to build:
> Multiple commands produce '/Users/me/Library/Developer/Xcode/DerivedData/App-dojfwvahrknhgaftbxmqefjshmiy/Build/Products/Debug-iphonesimulator/App Staging.app/Frameworks/Instabug.framework':
> 1) Target 'App Staging' has copy command from '/app/mobile/node_modules/instabug-reactnative/ios/Instabug.framework' to '/Users/me/Library/Developer/Xcode/DerivedData/App-dojfwvahrknhgaftbxmqefjshmiy/Build/Products/Debug-iphonesimulator/App Staging.app/Frameworks/Instabug.framework'
> 2) That command depends on command in Target 'App Staging': script phase “[CP] Embed Pods Frameworks”

### Instabug integration code
```
# App.js
  componentWillMount() {
    Instabug.startWithToken(Constants.instabugToken(), [
      Instabug.invocationEvent.shake,
    ]);
  }
```

### SDK Version
```"instabug-reactnative": "^8.0.23",```

### React Native, iOS and Android Versions
React Native: 0.57.5
iOS: 12.1
Xcode: 10.1

### Additional details
* Both the "Embed Instabug Framework" step and the "[CP] Embed Pods Frameworks" step are trying to copy the Instabug.framework file.
* If you remove the "Embed Instabug Framework" step as well as the "Strip Frameworks" step which runs `bash "${BUILT_PRODUCTS_DIR}/${FRAMEWORKS_FOLDER_PATH}/Instabug.framework/strip-frameworks.sh"`, then the build appears to work.
* My guess is that the `link.rb` script and CocoaPods are trying to do the same work in slightly different ways and are thus not playing well together.

**Comment by HeshamMegid** [comment]
@plowman you should use either `react-native link` or CocoaPods to install Instabug. Please let me know if the docs were not clear on that.

To proceed, you should just remove the 2 build phases which got added by `link.rb`: "Embed Instabug Framework" and "Strip Frameworks".

Thanks for the detailed report! 💯

**Comment by plowman** [comment]
Thanks @HeshamMegid - All the docs say is this:
<img width="675" alt="screen shot 2019-02-05 at 10 15 25 am" src="https://user-images.githubusercontent.com/148066/52294827-24da5180-292f-11e9-9309-46ea238dd4d9.png">

You say:
> you should use either `react-native link` or CocoaPods to install Instabug

But here's the problem I'm having with that:
1. The command `react-native link instabug-reactnative` updates my Podfile in a way which breaks the build.
2. Just trying to use the [Instabug pod](https://cocoapods.org/pods/Instabug) directly doesn't work because the pod lacks the react-native binding.
3. There is no information in [the more detailed docs](https://docs.instabug.com/docs/react-native-integration) to tell you how you'd install for React Native using just cocoapods. Does such a method exist?

**Comment by HeshamMegid** [comment]
> 1. The command `react-native link instabug-reactnative` updates my Podfile in a way which breaks the build.

Is that error you mentioned above (multiple commands producing Instabug), or another error?

> 3. There is no information in [the more detailed docs](https://docs.instabug.com/docs/react-native-integration) to tell you how you'd install for React Native using just cocoapods. Does such a method exist?

I have updated [the readme file in this repo](https://github.com/Instabug/Instabug-React-Native#using-cocoapods) with instruction on how to do that. Can you please check it out and let me know if it works for you?

**Comment by plowman** [comment]
> Is that error you mentioned above (multiple commands producing Instabug), or another error?
Yep, it's the same error in the title of this issue.

> I have updated [the readme file in this repo](https://github.com/Instabug/Instabug-React-Native#using-cocoapods) with instruction on how to do that. Can you please check it out and let me know if it works for you?
Nice! Yes, those install steps appear to work. Two points of feedback on the docs:
1. It might be worth calling out that if you do those manual Pod steps you'll still have to setup Android manually.
2. I'm uncomfortable with the `post_install do |installer|` step since it appears to unlink the React base pod. What's the point of this step? Also, the project still builds if I don't remove that step.

**Comment by HeshamMegid** [comment]
> It might be worth calling out that if you do those manual Pod steps you'll still have to setup Android manually.

That makes sense. Will add it.

> I'm uncomfortable with the `post_install do |installer|` step since it appears to unlink the React base pod. What's the point of this step? Also, the project still builds if I remove that step.

With certain configurations, you might end up having React linked to the project twice, hence the `post_install` hook. If your project is building fine without it, then there's no need to include it

Feel free to reopen the issue if you're still having trouble.

**Comment by plowman** [comment]
Excellent. Thanks again for your help, @HeshamMegid!
