### ISSUE TITLE
React Native: Button Instabug don't work

### ISSUE THREAD

**Issue by andreypaul** [Instabug/Instabug-React-Native#248]
The "Instabug" button is not pressed after restarting the application on Android. When you first start the application, the "Instabug" button works.

"instabug-reactnative": "8.0.23",
"react-native": "0.57.8",

config:
 new RNInstabugReactnativePackage.Builder(environment.getInstabugApiKey(), application.this)
                                .setInvocationEvent("shake", "button", "screenshot")
                                .setPrimaryColor("#8A715C")
                                .setFloatingEdge("left")
                                .setFloatingButtonOffsetFromTop(150)
                                .build(),

**Comment by salmamali** [comment]
@andreypaul Could you give us more details about this issue as we are unable to reproduce it? How do you restart the app? And does the whole app freeze or just the button?

**Comment by HeshamMegid** [comment]
@andreypaul closing this issue as it has been inactive for a couple of weeks. Please feel free to reopen if you need to.
