### ISSUE TITLE
Linking on Windows, Linux

### ISSUE THREAD

**Issue by henryrossiter** [Instabug/Instabug-React-Native#249]
### Steps to Reproduce the Problem

I've encountered this problem on both Windows and Linux. after installing project dependencies with ```yarn install``` I run ```react native link instabug-reactnative``` 

### Expected Behavior

successful project linking. Every other module links successfully.

### Actual Behavior

$ react-native link instabug-reactnative
Scanning folders for symlinks in C:\MYPATH\mindlogger-app\node_modules (55ms)
rnpm-install info Platform 'ios' module instabug-reactnative is already linked
rnpm-install info Platform 'android' module instabug-reactnative is already linked
events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: spawn ruby ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:240:19)
    at onErrorNT (internal/child_process.js:415:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
    at Function.Module.runMain (internal/modules/cjs/loader.js:745:11)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)
Emitted 'error' event at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:246:12)
    at onErrorNT (internal/child_process.js:415:16)
    [... lines matching original stack trace ...]
    at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)

### SDK Version
8.0.19

### System

Windows 10 (encountered same issue with Ubuntu)
react-native 56.0 (encountered same issue with rn 55.4, 58.5)
yarn 1.13
npm 6.4.1

### Project That Reproduces the Issue

https://github.com/ChildMindInstitute/mindlogger-app

**Comment by salmamali** [comment]
@henryrossiter 
As stated in the Readme, we use a gem called `xcodeproj` to link our framework to the app for iOS. I don't think this gem can be installed on Windows. How are you running react native for iOS on your OS, are you using Expo?

**Comment by henryrossiter** [comment]
I'm not in Expo, our app is ejected. I'm only working on the Android version of the app. However, some packages require linking to android, so I still have to run ```react-native link``` before building the Android version.

When I run the same command on MacOS without the gem there is a warning, but no error. On windows/linux, it crashes the linking and prevents other packages from linking. For example, if I have 10 dependences that need to be linked and instabug is the second, the last 8 never get linked.

**Comment by salmamali** [comment]
@henryrossiter At the moment we don't handle linking android only. Here is a workaround until we can work on a better solution for this scenario in the future. First, link your libraries by name so do not use `react-native link` but use `react-native link <name-of-library>`. This will ensure that everything is linked properly and since the linking step needs to be done only once, this will not waste time. Second, use the manual linking steps here [Instabug Android Manual Linking](https://docs.instabug.com/docs/react-native-integration#section-manual-linking) to link Instabug for android only.

**Comment by HeshamMegid** [comment]
@henryrossiter do you still need help with this issue? I'm closing the issue for now but please feel free to reopen it if you need further help.

**Comment by henryrossiter** [comment]
@HeshamMegid  I don't need any help, thanks.

It is possible to manually link libraries as @salmamali suggested, but it was so tedious that I eventually removed Instabug from my project completely so that the balance of my dependencies could link automatically.

Hopefully non macOS linking will come eventually. Thanks!

**Comment by HeshamMegid** [comment]
@henryrossiter we will look more into that and let you know if we find an easier solution.
