### ISSUE TITLE
Disable the SDK from JavaScript on Android

### ISSUE THREAD

**Issue by c100k** [Instabug/Instabug-React-Native#250]
### Expected Behavior

Disable the SDK from JavaScript on Android.

### Actual Behavior

It can easily be done on iOS since we are calling `Instabug.startWithToken` in the JS code. But on Android, all the initialization is done in `MainApplication`.

### Instabug integration code

```java
new RNInstabugReactnativePackage.Builder("My token", MainApplication.this)
    .setCrashReportingEnabled(false)
    .setInvocationEvent("shake")
    .setPrimaryColor("#ff0000")
    .build(),
```

### SDK Version

8.0.26

### React Native, iOS and Android Versions

React Native 0.57.8
Android 28

### Device Model

Not specific to a device model.

**Comment by HeshamMegid** [comment]
@c100k to do this right now you will have to call `disable` from the JS side while retaining the Java code in `MainApplicaiton`, however, we're working on making it possible to initialize the SDK without having to add any code to the native Android project.

Feel free to reopen the issue if this doesn't work for you.
