### ISSUE TITLE
Android asks for photo library permission immediately on App open.

### ISSUE THREAD

**Issue by CapitanRedBeard** [Instabug/Instabug-React-Native#251]
### Steps to Reproduce the Problem
Install and implement Instabug for Android.
Open up app.
Notice the permissions prompt immediately being displayed

### Expected Behavior
Ideally we can match the iOS behavior and only ask for photo permissions when the user pressed the "Take a screenshot" button in the "Report a problem" screen.

### Actual Behavior
Android asks for photo library permissions on app open.

### Instabug integration code
No Android source code to install the library, just implement the native work specified in the readme on a blank application and you'll see Android prompting for permission immediately.

### SDK Version
`instabug-reactnative: 8.0.10`

### React Native
`react-native: 0.57.8`
Android Target SDK is 27 

### Device Model
Reproducible on both my Samsung Galaxy S8 and a Nexus 6 simulator

### [Optional] Project That Reproduces the Issue
This should happen on any out of the box fresh install of instabug on a blank react native repro

Good chance this behavior is just not adjustable however it would be nice to have a legit explanation for why this occurs. My app is not a photo app so asking for permissions just for this library which is only really invoked when a user is reporting a bug is less than ideal for my case.

Thanks for your time!

**Comment by HeshamMegid** [comment]
@CapitanRedBeard are you using the screenshot gesture to invoke Instabug? If this is the case, we request access to local storage to be able to detect when a screenshot has been captured by monitoring the screenshots directory. If you change the invocation event to any other value, that permission won't be needed.

**Comment by CapitanRedBeard** [comment]
@HeshamMegid 	Ah this makes sense yeah I am using screenshot gesture. Thanks for the reply I'll close this out.
