### ISSUE TITLE
Error: spawn ruby ENOENT

### ISSUE THREAD

**Issue by sm2017** [Instabug/Instabug-React-Native#253]
### Steps to Reproduce the Problem
When I run `react-native link instabug-reactnative` 

```
rnpm-install info Linking instabug-reactnative ios dependency
rnpm-install info Platform 'ios' module instabug-reactnative has been successfully linked
rnpm-install info Linking instabug-reactnative android dependency
rnpm-install info Platform 'android' module instabug-reactnative has been successfully linked
events.js:167
      throw er; // Unhandled 'error' event
      ^

Error: spawn ruby ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:232:19)
    at onErrorNT (internal/child_process.js:407:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
Emitted 'error' event at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:238:12)
    at onErrorNT (internal/child_process.js:407:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

### SDK Version

latest

### React Native, iOS and Android Versions
```
  React Native Environment Info:
    System:
      OS: Windows 10
      CPU: (8) x64 Intel(R) Core(TM) i7-3632QM CPU @ 2.20GHz
      Memory: 1.21 GB / 5.58 GB
    Binaries:
      Yarn: 1.13.0 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  3.3.0.0 AI-182.5107.16.33.5199772
```

**Comment by alyezz** [comment]
Hello,

It looks like you're missing Ruby. Try downloading and installing it from the link below:

`https://github.com/oneclick/rubyinstaller2/releases/download/RubyInstaller-2.6.1-1/rubyinstaller-2.6.1-1-x64.exe` 

After installation everything should work fine.

**Comment by sm2017** [comment]
@alyezz , Can you refer me to installation guide that told we need to install ruby too?

I follow installation as documents told

**Comment by HeshamMegid** [comment]
@sm2017 this isn't mentioned anywhere in our docs. We've assumed the installation steps are going to be done on a machine that has Ruby pre-installed. 

We will work on making this clearer.

**Comment by sm2017** [comment]
@HeshamMegid thanks very much

**Comment by HeshamMegid** [comment]
@sm2017 linking on v8.1.5 now work on Windows when Ruby isn't installed.
