### ISSUE TITLE
Improve hasChats implementation

### ISSUE THREAD

**Issue by soumyamishra89** [Instabug/Instabug-React-Native#254]
The Replies.hasChats takes a callback function and does not invoke if it does not have any chats.
This creates certain issues like if I want to invoke new Chat when chats are not already there. 

The callback should be invoked with a boolean stating if chats exists or not. This would make further action meaningful.

The documentation does not tell that hasChats accepts a callback.

### SDK Version
Instabug 8.1.3

### React Native, iOS and Android Versions
RN 0.58.6

**Comment by HeshamMegid** [comment]
@soumyamishra89 what you're saying makes sense. Let me check it from our side and get back to you.

**Comment by HeshamMegid** [comment]
@soumyamishra89 we updated the behavior of the API in v8.1.5. Please check [the release notes](https://github.com/Instabug/Instabug-React-Native/releases/tag/v8.1.5).
