### ISSUE TITLE
Usage guide for sourcemap upload

### ISSUE THREAD

**Issue by soumyamishra89** [Instabug/Instabug-React-Native#260]
The new Instabug version has an sourcemap upload script which expects APP_TOKEN. if not provided it tries to scrap it from files with Instabug.startWithToken.
Now how do you manage separate tokens with ios and android and the token has to be added explicitly and not through constants.
e.g. const instabugToken = '123456789abcdefg';
Instabug.startWithToken(instabugToken) wont work.
and if there is conditional token for ios and android, it would pick up the first one.

Another approach is to set APP_TOKEN as environment variable on the container one is building the app. 

So, can we get a usage guide?

### SDK Version
8.1.5

**Comment by salmamali** [comment]
Hello @soumyamishra89 
You don't need to add the APP_TOKEN yourself, the script searches for your app token in your project folder and adds it automatically.

**Comment by salmamali** [comment]
@soumyamishra89 
Sorry I misunderstood your question. The APP_TOKEN will not be added to the script unless it's in the `startWithToken` API. We'll be looking into how to handle adding the token if it's placed somewhere else.

**Comment by HeshamMegid** [comment]
@soumyamishra89 as we're looking more into this, I'm curious to know why you maintain 2 separate tokens for both iOS and Android. Currently, if you create a React Native app on the Instabug dashboard, both variants of the app should have the same token.

**Comment by juanamd** [comment]
Btw, this new "sourcemap upload" doesn't work on Windows when doing a release build (gradlew assembleRelease).

Had to remove the following lines from build.gradle for it to work:

`task upload_sourcemap(type: Exec) {
    commandLine 'sh', './upload_sourcemap.sh'
}

tasks.whenTaskAdded { task ->
    if (task.name == 'preReleaseBuild') {
        task.dependsOn upload_sourcemap 
    }
}`

(Windows 10 x64 using React Native 0.59.2)

**Comment by HeshamMegid** [comment]
@juanamd are you having the same issue on v8.2.2?

**Comment by soumyamishra89** [comment]
@HeshamMegid: as far as i remember it was mentioned in the docs that it is a good practice to separate the two apps. And it also helps in identifying the bugs specific to app os. I dont see any filter option separating ios and android, but still it would be much easier to maintain two apps for ios and android.

**Comment by ngallion** [comment]
We have run into an issue in which we have the token in our config files (using react-native-config) and the script is failing saying APP_TOKEN not found. But when we hard code the value in, it succeeds. Any suggestions? Would prefer to use the config rather than hard coded values

**Comment by HeshamMegid** [comment]
@soumyamishra89 that makes sense, thanks for the feedback.

@ngallion that issue has been fixed in 8.2.2. Are you still seeing it?

We're currently working on a better way to find the app token(s), including giving you the ability to set them as an env variable.

**Comment by brycebenson** [comment]
@HeshamMegid seeing the same hardcoded issue on 8.2.2 as well for the android build token parsing

**Comment by HeshamMegid** [comment]
@brycebenson on 8.2.2 the script still looks for a hardcoded token, however, it skips the upload if it doesn't find it rather than failing.

We've worked on an improved version of the script that fits the different usage scenarios, and we'll be shipping it very soon.

**Comment by HeshamMegid** [comment]
We have updated our script to handle all the cases mentioned here. Please check [this](https://github.com/Instabug/Instabug-React-Native#uploading-source-map-files-for-crash-reports) for more details.

If you have any feedback about it, we'd love to hear it, so please feel free to open new issues.
