### ISSUE TITLE
Missing photos on bug reports

### ISSUE THREAD

**Issue by soumyamishra89** [Instabug/Instabug-React-Native#261]
### Steps to Reproduce the Problem
- Open bug reporting with 
`BugReporting.showWithOptions(BugReporting.reportType.bug, [BugReporting.option.emailFieldOptional, BugReporting.option.commentFieldRequired]);`
- write a comment and press send. (the screenshot is attached by default)

### Expected Behavior
The bug report on the instabug dashboard should contain the screenshot

### Actual Behavior
The bug report on the instabug dashboard is not always uploaded

### SDK Version
8.1.5

### React Native, iOS and Android Versions
RN 0.58.5

The issue appears sometimes when the bug report has no attached screenshot even when it was attached while uploading.

**Comment by HeshamMegid** [comment]
This was an API issue that has been fixed. Please try again and let us know if you’re still experiencing it.
