### ISSUE TITLE
Resource with same name ib_core_alert_dialog_msg_color

### ISSUE THREAD

**Issue by felix-zg** [Instabug/Instabug-React-Native#265]
### Steps to Reproduce the Problem
After upgrade to 8.2.0 we receive the following error:

> /Users/XXX/.gradle/caches/transforms-1/files-1.1/instabug-survey-8.2.0.aar/49592cbd1ffbe1dca1cd523d258b1197/res/values/values.xml: AAPT: Resource entry InstabugSurveyLight already has bag item ib_core_alert_dialog_msg_color.
>     
> /Users/XXX/.gradle/caches/transforms-1/files-1.1/instabug-survey-8.2.0.aar/49592cbd1ffbe1dca1cd523d258b1197/res/values/values.xml: AAPT: Originally defined here.

In the values file we have two values with the same key:
```
<item name="ib_core_alert_dialog_msg_color">#757575</item>
<item name="ib_core_alert_dialog_msg_color">#757575</item>
```

### SDK Version
8.2.2

### React Native, iOS and Android Versions
Android

**Comment by salmamali** [comment]
@felix-zg 
Could you try clearing your gradle cache by deleting the folder `$HOME/.gradle/caches` and then try building again?

**Comment by felix-zg** [comment]
Yes, same result :(

**Comment by andrewheekin** [comment]
Seeing the exact same bug in my company's project on the same environment/release. (Android, 8.2.2)

**Comment by salmamali** [comment]
@felix-zg @andrewheekin This is in fact an issue. We'll be releasing a fix for this soon.

**Comment by salmamali** [comment]
@felix-zg @andrewheekin This fix has been released on version 8.2.3. Please feel free to reopen the issue if there are any problems.

**Comment by andrewheekin** [comment]
hey @felix-zg, just upgraded to 8.2.3 but now getting the following error on android:
`:app:processDebugResources FAILED
/Users/xxxxxx/myRNAppImBuilding/android/app/build/intermediates/manifests/full/debug/AndroidManifest.xml:22: AAPT: No resource identifier found for attribute 'appComponentFactory' in package 'android'
    
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':app:processDebugResources'.
> Failed to process resources, see aapt output above for details.
* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.`

 Any idea where this error might be coming from?

**Comment by andrewheekin** [comment]
@salmamali any thoughts here?
Here are our version numbers:
buildToolsVersion: 28.0.3
compileSDKVersion: 26
targetSDKVersion: 26

**Comment by salmamali** [comment]
@andrewheekin can you try updating the compileSDKVersion to 28?
