### ISSUE TITLE
React native iOS fails from clean install with: JSON value '1' of type NSNumber cannot be converted to NSArray

### ISSUE THREAD

**Issue by andrewheekin** [Instabug/Instabug-React-Native#275]
### Steps to Reproduce the Problem
Made a fresh react native project and added instabug
"instabug-reactnative": "^8.2.5",
"react": "16.8.3",
"react-native": "0.59.5"

### Expected Behavior
Instabug works on shake

### Actual Behavior
The following error appears in the console - JSON value '1' of type NSNumber cannot be converted to NSArray

### SDK Version
8.2.5

### React Native, iOS and Android Versions
"react": "16.8.3",
"react-native": "0.59.5"

### Project That Reproduces the Issue
https://github.com/andrewheekin/instabugtester

<img width="361" alt="Screen Shot 2019-04-24 at 11 09 59 AM" src="https://user-images.githubusercontent.com/4684591/56673954-2d693b00-6687-11e9-9ac9-621d444395eb.png">

**Comment by salmamali** [comment]
@andrewheekin Can I see your integration code please? There is probably an API that you're using that expects an array of constants but it's getting just a constant.

**Comment by salmamali** [comment]
@andrewheekin I didn't realize you attached a sample project! The issue is this line 
```
Instabug.startWithToken(INSTABUG_TOKEN, Instabug.invocationEvent.shake);
```
This API expects an array of invocation events so it should look like this
```
Instabug.startWithToken(INSTABUG_TOKEN, [Instabug.invocationEvent.shake]);
```

**Comment by andrewheekin** [comment]
@salmamali thanks, making that second arg an array fixes everything on iOS. However I still can't get the instabug menu to show up when shaking the android emulator from the same project

**Comment by salmamali** [comment]
@andrewheekin Add your token to the builder to the in this file https://github.com/andrewheekin/instabugtester/blob/master/android/app/src/main/java/com/instabugtester/MainApplication.java
And maybe try decreasing the shaking threshold for Android as shown and try again please
```
BugReporting.setShakingThresholdForAndroid(400);
```

**Comment by andrewheekin** [comment]
@salmamali my instabug token was in MainApplication.java at the time of the error, and the shaking was done on the emulator so the threshold shouldn't have an effect

**Comment by andrewheekin** [comment]
I'm shaking the emulator with cmd m

**Comment by salmamali** [comment]
Unfortunately cmd M doesn’t simulate the shake as expected. You can try shaking the emulator using the virtual sensors or running on a real device.

**Comment by HeshamMegid** [comment]
@andrewheekin closing this issue since we haven't heard back from you. Please feel free to reopen if you still need help.

**Comment by MakhouT** [comment]
@salmamali Changing it to an array indeed fixes the issue. However the docs needs to be updated then. https://instabug.com/platforms/react-native
On the instabug dashboard the instructions are correct. Also still looking to get it running on android.

**Comment by salmamali** [comment]
@MakhouT Thank you for pointing that out, we will be changing it to the correct usage. If you're having trouble integrating for android, please open a new issue with more details.
