### ISSUE TITLE
Unhandled Promise Rejection

### ISSUE THREAD

**Issue by soumyamishra89** [Instabug/Instabug-React-Native#281]
After updating to latest instabug version, there are warning messages that pop up on debug verison.

PFA the screenshot.

![Screenshot 2019-05-07 at 14 57 08](https://user-images.githubusercontent.com/3540647/57302256-0ffe8d00-70db-11e9-9b20-f7a4aa86b6de.png)

This warning was found on ios app. Have not checked on android, but i guess it would be there on android too. Seems like the Response object is been overridden with custom information.

### Steps to Reproduce the Problem
- Install instabug-reactnative 8.2.7
- run on development mode

### SDK Version
8.2.7

### React Native, iOS and Android Versions
RN 0.59.5

**Comment by soumyamishra89** [comment]
There was some issue running the android version. It could not find the instabug android sdk 8.2.2.0. which was weird since it should be semantic versioning without the last 0. So, will try again and let you know.

**Comment by HeshamMegid** [comment]
> There was some issue running the android version. It could not find the instabug android sdk 8.2.2.0. which was weird since it should be semantic versioning without the last 0

@soumyamishra89  we've switched away from Maven Central to our own repo available at https://sdks.instabug.com/nexus/repository/instabug-cp which includes the versions with the trailing 0.

Unlinking and linking again should add this automatically to your build.gradle file. You can also add it manually.

**Comment by soumyamishra89** [comment]
@HeshamMegid on Android it gave an error "could not invoke Instabug.networkLog, No value for responseCode".
When i disabled NetworkLogger (NetworkLogger.setEnabled(false)) it worked fine. Maybe there is something else that I missed while linking?

**Comment by alyezz** [comment]
@soumyamishra89 We just Released v8.3.0. Update and let us know if you have any issues.

**Comment by soumyamishra89** [comment]
@alyezz: Thank you for a quick response. I tested it. looks fine.
Closing this issue
