### ISSUE TITLE
React Native Instabug 8.3.0 has serious error - captureJsErrors

### ISSUE THREAD

**Issue by alphadevs07** [Instabug/Instabug-React-Native#283]
I installed the latest version - 8.3.0 and I can see such error.
![Simulator Screen Shot - iPad Air - 2019-05-09 at 19 18 25](https://user-images.githubusercontent.com/9720612/57471885-df625300-7294-11e9-98cd-225ab2a7c5ed.png)

I checked the source code and I can see there isn't any function: `captureJsErrors`

Also, I looked through the previous builds and I think the line is deleted in latest version.
`import { parseErrorStack, captureJsErrors } from './utils/InstabugUtils';`

I hope this solution helps other developers who has similar problem with me.

Thanks.

**Comment by alyezz** [comment]
Hello,

Thanks for reporting this, we released a hotfix for it in 8.3.1

Let us know if you have any issues
