### ISSUE TITLE
Wrong Maven dependency on >8.3.0

### ISSUE THREAD

**Issue by facuacostag** [Instabug/Instabug-React-Native#287]
On version 8.3.0 the Android Maven dependency was changed to `8.3.0.0` which is wrong and causes the build to fail, should be changed to `8.3.0`

```
dependencies {
    implementation 'com.facebook.react:react-native:+'
    api ('com.instabug.library:instabug:8.3.0.0'){
        exclude group: 'com.android.support:appcompat-v7'
    }
}
```
Maven repository changelog: [LINK](https://mvnrepository.com/artifact/com.instabug.library/instabug)
For instance, the Android implementation of Instabug is using `8.3.0`
![Screenshot 2019-05-16 at 12 24 40](https://user-images.githubusercontent.com/19332669/57850349-a0bd2300-77d5-11e9-833b-8dcdb3f8ebb5.png)

I changed it manually when building my project and it works fine.

**Comment by alyezz** [comment]
@facuacostag  we've switched away from Maven to our own repo available at https://sdks.instabug.com/nexus/repository/instabug-cp

Unlinking and linking again should add this automatically to your `build.gradle` file. You can also add it manually. Let me know if you have any issues with this.

**Comment by facuacostag** [comment]
Thanks, I recently updated the library and didn't realise that when doing the `link` it was failing because we didn't have `strings.xml` file on Android. Since we are using 3 different flavours we didn't need a "general" `strings.xml` file so I just created a dummy one to avoid the issue. Do we really need to check on this file when running the link script?

**Comment by salmamali** [comment]
@facuacostag The general `strings.xml` should not affect how the script is executed since it doesn't reference the file at all. What version of `instabug-reactnative` was this break happening on?
