### ISSUE TITLE
Android release build fails on Windows

### ISSUE THREAD

**Issue by juanamd** [Instabug/Instabug-React-Native#288]
### Steps to Reproduce the Problem

On a Windows machine, run ./gradlew assembleRelease

### Expected Behavior

The build process finishes successfully

### Actual Behavior

The build process throws the following error:

* What went wrong:
Execution failed for task ':instabug-reactnative:upload_sourcemap'.
> A problem occurred starting process 'command 'sh''

### SDK Version
8.3.1

### React Native, iOS and Android Versions
0.59.8

### Notes

I have mentioned this issue in another related problem that has been already closed a while back.
For now, I've been solving it by just removing the task upload_sourcemap from build.gradle when doing the release build, but its starting to become too annoying.
And the issue is pretty straightforward: Windows doesn't have a "sh" command, so of course, it will fail. I don't know if the actual script works on Windows when executed in any other way or it will need to be rewritten for Windows as a separate script.

**Comment by alyezz** [comment]
@juanamd thanks for reporting this, we're currently working on a fix.

**Comment by alyezz** [comment]
@juanamd We just Release 8.3.2. Update and let us know if you have any issues

**Comment by juanamd** [comment]
Sorry, forgot to report back:
The issue has been solved for me with version 8.3.2
Thanks
