### ISSUE TITLE
Report a problem screen disappear immediately after showing.

### ISSUE THREAD

**Issue by alphadevs07** [Instabug/Instabug-React-Native#289]
I implemented the instabug-reactnative module. Actually, I updated the module to 8.3.1.
Finally, after changing the function name and I made it running.
But I showed that with manually by calling the `show()` method. And it shows the instabug screen. And I clicked the `Report a problem` button but it disappear immediately after showing the report page. 

Here is the video for that issue.
https://www.dropbox.com/s/z9vbwtaavpyajuj/instabug.mov?dl=0

Please let me if anybody has experiences with that.

Thanks.

**Comment by HeshamMegid** [comment]
@alphadevs07 please share your Instabug integration code, including any calls to Instabug methods.
