### ISSUE TITLE
setEmailFieldRequiredForActions not implemented on Android

### ISSUE THREAD

**Issue by SudoPlz** [Instabug/Instabug-React-Native#291]
That method is not implemented on `"instabug-reactnative": "8.3.2",`,

how are we supposed to set wether we want the email field to be required or not, I'm confused.

Thanks

**Comment by salmamali** [comment]
@SudoPlz This API was deprecated a while back. You can now use the API `BugReporting.setInvocationOptions([BugReporting.option. emailFieldHidden])` or any value of `BugReporting.option`. Please feel free to reopen the issue if this wasn't what you were looking for.

**Comment by SudoPlz** [comment]
Oh got it, thanks @salmamali
