### ISSUE TITLE
Wrong typescript definition of BugReporting.setReportTypes

### ISSUE THREAD

**Issue by wynch** [Instabug/Instabug-React-Native#292]
Hello,

In your index.d.ts, you wrote : 
  `function setReportTypes(types: reportType): void;`

it should be

 ` function setReportTypes(types: reportType[]): void;`

**Comment by salmamali** [comment]
@wynch Thanks for pointing that out! We'll fix it and include it in our next release.

**Comment by salmamali** [comment]
@wynch this was fixed in version 8.3.3. Closing this issue.
