### ISSUE TITLE
BugReporting.setReportTypes doesn't work on Android

### ISSUE THREAD

**Issue by wynch** [Instabug/Instabug-React-Native#294]
When using instabug-react-native 8.3.1, 

### Expected Behavior

We don't want the prompt options when users does a screenshot, and we want to directly display the bug reporting form.

The code below should have this behavior on both android and iOS 

### Actual Behavior

The code below only works for iOS (bug form is directly displayed when user does a screenshot), on android, we still have the pre-form dialog prompt to select wether it's a bug or a feedback.

### Instabug integration code

```
import Instabug, { BugReporting, Chats, Replies } from "instabug-reactnative";

    BugReporting.setEnabled(true);
    Chats.setEnabled(false);
    Replies.setEnabled(false);
    BugReporting.setReportTypes([BugReporting.reportType.bug]);
```

Of course, android also has the MainApplication.java integration : 

```
@Override
        protected List<ReactPackage> getPackages() {
             new ArrayList<ReactPackage>(Arrays.<ReactPackage>asList(
                      // .... other packages
                   new RNInstabugReactnativePackage.Builder(BuildConfig.INSTABUG_API_KEY_ANDROID, MainApplication.this)
                            .setInvocationEvent("screenshot").setPrimaryColor("#1D82DC")
                            .setFloatingEdge("left").setFloatingButtonOffsetFromTop(250).build())

       }

```
### SDK Version
RN 59.8

### React Native, iOS and Android Versions

tested on:
iOS: iPhone 7 running iOS 12.2
android: Galaxy A5 running android 8.0.0

**Comment by salmamali** [comment]
@wynch thank you for the detailed report. We’ll look into this issue.

**Comment by salmamali** [comment]
@wynch
Are you using any other APIs in your code besides the ones you mentioned above?

**Comment by wynch** [comment]
@salmamali it works, thank you !

**Comment by salmamali** [comment]
@wynch That shouldn't be happening they should both be consistent. We will be working on a fix for this. However, all features are enabled by default so it shouldn't make a difference whether you enable them initially or not. And as for the screenshot not doing anything, is that happening on iOS or Android or both? Because it could be just that you need to accept the capturing screen permission to get to work.

**Comment by wynch** [comment]
One thing that could come into play is that I have codepush builds. It can bring different behavior than direct build, because the app js bundle isn't in the same directory.

I'll try and test both cases, and tell you....

**Comment by wynch** [comment]
@salmamali : Ok, I tested again. Direct & Codepush build, and I have consistent behavior between iOS & android. I had to remove `BugReporting.setEnabled(true)` like you advised.

I don't know what happened previously... 
I close this issue :)

Thank you !
