### ISSUE TITLE
IBGUserStepsModeEnable not found in xcode

### ISSUE THREAD

**Issue by hohien** [Instabug/Instabug-React-Native#297]
"
RCT_ENUM_CONVERTER(IBGUserStepsMode, (@{
                                        @"reproStepsEnabled": @(IBGUserStepsModeEnable),
                                      @"reproStepsDisabled": @(IBGUserStepsModeDisable),
                                      @"reproStepsEnabledWithNoScreenshots": @(IBGUserStepsModeEnabledWithNoScreenshots)
                                      }), IBGUserStepsModeEnabledWithNoScreenshots, integerValue)
"

I got error at IBGUserStepsModeEnable,

**Comment by rollsroyc3** [comment]
Looks like the same issue as mine

https://github.com/Instabug/Instabug-React-Native/issues/296

@salmamali

**Comment by hohien** [comment]
@rollsroyc3 My RN version is 0.59.8

**Comment by salmamali** [comment]
@rollsroyc3 @hohien Sorry for the delay. We will be releasing the fix for this shortly.

**Comment by salmamali** [comment]
@rollsroyc3 @hohien We just released version 8.3.4. We've removed the `reproStepsMode.enabled` enum as per recent changes to the App Store guidelines, please refer to [this](https://github.com/Instabug/Instabug-iOS/issues/317) issue. To enable repro steps now you can use this instead `reproStepsMode.enabledWithNoScreenshots`.
