### ISSUE TITLE
No native crashes caught before RCTRootView initialization

### ISSUE THREAD

**Issue by chrs1885** [Instabug/Instabug-React-Native#303]
### Steps to Reproduce the Problem
Our app is using a native bottom navigation. Each tab is representing a RCTRootView or a native view. Depending on which tab is active when launching the app, the SDK may or may not be initialized. In case of a native view, native crashes will not be reported. I understand that the SDK was not built for app setups like this, but for single RCTRootView apps instead. However, would it be possible to use the native AND the react native SDK at the same time by disabling native crash handling when configuring the react native SDK?

Furthermore, due to privacy concerns we need to stop/start crash reporting based on a toggle state inside our settings screen. Is there a way to do so by using the rn sdk?

### Expected Behavior
Crashes are reported even before a RCTRootView was presented to the user.

### Actual Behavior
No crashes are reported. You need to display a RN screen before native client gets initialized.

### Instabug integration code
```
import Instabug from 'instabug-reactnative';

Instabug.startWithToken('<MY-KEY>', [Instabug.invocationEvent.shake]);
```

### SDK Version
version "8.4.0"

### Device Model
-

**Comment by salmamali** [comment]
@chrs1885 There may be a workaround for your case. I recommend initializing Instabug from the `AppDelegate` using this API in `didFinishLaunchingWithOptions`:
```
[Instabug startWithToken:@"APP_TOKEN" invocationEvents:IBGInvocationEventShake];
```
and you can import Instabug at the top using:
```
#import <Instabug/Instabug.h>
```

In that case you won't need to initialize again in the JS side and it should start capturing native crashes on app launch.

**Comment by chrs1885** [comment]
@salmamali But will I get the javascript exceptions as well if if do the initialization on the native side?

**Comment by salmamali** [comment]
@chrs1885 Yes,  just by importing Instabug in your `app.js`, the SDK will start listening for crashes once the js bundle is loaded.

**Comment by salmamali** [comment]
@chrs1885 will close this issue now, feel free to reopen it if you still have any questions regarding this issue.
