### ISSUE TITLE
using deprecated method Instabug.setViewsAsPrivate(arrayOfViews);

### ISSUE THREAD

**Issue by paomosca** [Instabug/Instabug-React-Native#304]
### Steps to Reproduce the Problem
Just update the last version (8.4.0) and run: react-native run-android

the last version doesn't compile on android for deprecated method

### Actual Behavior

> Task :instabug-reactnative:compileDebugJavaWithJavac FAILED
/PATHPROJECT/node_modules/instabug-reactnative/android/src/main/java/com/instabug/reactlibrary/RNInstabugReactnativeModule.java:2051: error: cannot find symbol
                Instabug.setViewsAsPrivate(arrayOfViews);
                        ^
  symbol:   method setViewsAsPrivate(View[])
  location: class Instabug

### SDK Version
Release v8.4.0
affected method: 
public void hideView(final ReadableArray ids)

commenting deprecated method make it compiles correctly (while i suppose i'm breaking some important action on native world)

### React Native, iOS and Android Versions
Android

**Comment by salmamali** [comment]
@paomosca I'm not sure how this is causing a problem because `Instabug.setViewAsPrivate` is a newly added API and not a deprecated one. Can you make sure that the native version of instabug in the `build.gradle` is version `8.4.0.1`? You can find it in the path `<project>/node_modules/instabug-reactnative/android/build.gradle` and you should find the line
```
api ('com.instabug.library:instabug:8.4.0.1'){
        exclude group: 'com.android.support:appcompat-v7'
    }
```

**Comment by paomosca** [comment]
yes I can confirm it's 
```
api ('com.instabug.library:instabug:8.4.0.1'){
        exclude group: 'com.android.support:appcompat-v7'
    }
```

"deprecated method" was the error message of compiler (maybe is a wrong message output)

**Comment by paomosca** [comment]
some more info:
updating react-native to 0.59.9 the error won't raise. 
the version affected was: react-native 0.58.6

**Comment by hohien** [comment]
i also get this error in react-native: 0.59.8

**Comment by hohien** [comment]
Any idea to fix this one

**Comment by salmamali** [comment]
@paomosca @hohien We're looking into this and we'll keep you updated.

**Comment by paomosca** [comment]
@hohien as a temp workaround I commented the line:

`//Instabug.setViewsAsPrivate(arrayOfViews); `

To compile it correctly. 

Apparently everything is still working because is a new functionality of Instabug I'm not using in my app.

**Comment by hohien** [comment]
@paomosca thanks

**Comment by salmamali** [comment]
@paomosca @hohien We're having trouble reproducing this. Could you check that the actual synced instabug version is `8.4.0.1` as shown below in Android Studio under `External Libraries`
<img width="1420" alt="Screen Shot 2019-06-19 at 2 55 00 PM" src="https://user-images.githubusercontent.com/10803019/59767675-191a7680-92a3-11e9-86cc-dbb627c57228.png">

**Comment by paomosca** [comment]
Yes, I can confirm, but i cannot help anymore in debug, because updating react-native to 0.59.9 did the trick for me, so I cannot catch the error anymore. I'm sorry.

**Comment by HeshamMegid** [comment]
Thanks @paomosca.


@hohien can you please confirm [this](https://github.com/Instabug/Instabug-React-Native/issues/304#issuecomment-503550846)?

**Comment by hohien** [comment]
@HeshamMegid  I have updated to the new version 8.4.2, the bug disappeared
