### ISSUE TITLE
onReportSubmitHandler freezes the app

### ISSUE THREAD

**Issue by GlisboaDev** [Instabug/Instabug-React-Native#306]
### Steps to Reproduce the Problem
Install Instabug 8.3.4 or 8.4, on setup, assign `onReportSubmitHandler` and shake your phone to invoke instabug popup.

### Expected Behavior
Show feedback popup
### Actual Behavior
app freezes

### Instabug integration code
```
import Instabug from 'instabug-reactnative';
    Instabug.startWithToken(
      'xxxxx',
      [Instabug.invocationEvent.shake]
    );
    Instabug.setWelcomeMessageMode(Instabug.welcomeMessageMode.disabled);
    Instabug.setCrashReportingEnabled(false);

    //This is done due to poor performance and avoid asking for extra permissions on our app.
    Instabug.setEnabledAttachmentTypes(true, false, false, false);
    Instabug.onReportSubmitHandler(() => {
 //Put anything in here or leave it empty, freezes the same way.
    });
```

### SDK Version
`"instabug-reactnative": "^8.4.0",`

### React Native, iOS and Android Versions
`"react-native": "0.58.4",`
`iOS 12.3.1`

### Device Model
iPhone XS (also happens with all the ones I tested with on simulator)

**Comment by salmamali** [comment]
@GlisboaDev We can't seem to reproduce this with your integration code. Would it be possible for you to create a simple app that has this issue?

**Comment by GlisboaDev** [comment]
Unfortunately I don't have time to setup a sample app now, since we're paying for the service, I reported it here hoping you'd have a follow up with the support or a fix for it.
What I noticed with the little I looked into, you seem to be sending a notification and waiting for it to trigger the feedback. That notification doesn't seem to be sent or the listener is missing it.

**Comment by HeshamMegid** [comment]
@GlisboaDev Just letting you know that we're still looking into this. We're having trouble reproducing the issue on our end, but we're trying to figure out what would cause it.

**Comment by alyezz** [comment]
@GlisboaDev   We just Release 8.4.3. Update and let us know if you have any issues
