### ISSUE TITLE
NetworkLogger.setEnabled(false) doesn't seem to work

### ISSUE THREAD

**Issue by kenvunz** [Instabug/Instabug-React-Native#314]
### Steps to Reproduce the Problem
- Add the code below to `index.js`
```js
import Instabug, { NetworkLogger } from 'instabug-reactnative';

NetworkLogger.setEnabled(false);
```
- Shake the device and select "Report a problem"
- Review the message on `https://dashboard.instabug.com`

### Expected Behavior
- No network request details being logged and display on dashboard

### Actual Behavior
- Network request  details still appear on the dashboard

### Instabug integration code
```js
function() {
	useEffect(() => {
		Instabug.startWithToken(instabugKey, [Instabug.invocationEvent.shake]);
		Instabug.setWelcomeMessageMode(Instabug.welcomeMessageMode.disabled); // Disable welcome message
	}, []);

	return (
		<ReduxStateProvider store={store}>
			<AppStateProvider>
				<NotificationHanlder />
				<StatusBar translucent={true} backgroundColor="transparent" />
				<PersistGate loading={null} persistor={persistor}>
					<NavigationContainer />
				</PersistGate>
			</AppStateProvider>
		</ReduxStateProvider>
	);
}
```

### SDK Version
`8.3.2`

### React Native, iOS and Android Versions
`0.59.3`

### Device Model
iPhone 7

**Comment by alyezz** [comment]
@kenvunz There might be some cashed network logs that are causing this issue, try running `Instabug.clearLogs();` only once then remove it and try again.

**Comment by kenvunz** [comment]
@alyezz your suggestion works! thanks for your help
