### ISSUE TITLE
'NSInvalidArgumentException unrecognized selector sent to instance' after upgrading from 2.13.3 to 8.4.2

### ISSUE THREAD

**Issue by Joao360** [Instabug/Instabug-React-Native#315]
### Steps to Reproduce the Problem

Report problem on iOS

### Expected Behavior

Report problem successfully

### Actual Behavior

Crashing when pressing the send button

### Instabug integration code

`Instabug.startWithToken(<TOKEN>, [Instabug.invocationEvent.screenshot])`

### SDK Version

8.4.2

### React Native, iOS and Android Versions
- React Native 0.58.6
- iOS 12.3.1

### Device Model

iPhone 7

When upgrading the package from 2.13.3 to 8.4.2 I started to caught a `NSInvalidArgumentException` when trying to report a problem through the app.

I followed the documentation on how to upgrade the library but I couldn't execute the `react-native unlink instabug-reactnative` command since it would say I didn't have Ruby installed while I do, so I manually unlinked the library on that step.

To try to fix this issue I linked the library on different ways, with and without CocoaPods, but on both the app still crashes.

Here's the full log:

> 2019-07-02 13:52:03.187671+0100 MYAPP[821:567987] -[__NSCFConstantString allKeys]: unrecognized selector sent to instance 0x1e0df3be8
2019-07-02 13:52:03.188041+0100 MYAPP[821:567987] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[__NSCFConstantString allKeys]: unrecognized selector sent to instance 0x1e0df3be8'
*** First throw call stack:
(0x1b06ad27c 0x1af8879f8 0x1b05c9ab8 0x1b06b2ac4 0x1b06b475c 0x10261c7d0 0x1025a45b8 0x1027094d0 0x1b323fb28 0x104348c74 0x104350bf4 0x1043518b4 0x10435b77c 0x1b02cd114 0x1b02cfcd4)
libc++abi.dylib: terminating with uncaught exception of type NSException

**Comment by alyezz** [comment]
@Joao360 you can do the unlinking/linking steps manually by following our [documentation](https://docs.instabug.com/docs/react-native-integration#section-manual-linking). You can do the steps in reverse to unlink, then redo them to link.

**Comment by Joao360** [comment]
@alyezz just did that, still got the same error when trying to submit a report.

**Comment by alyezz** [comment]
@Joao360 Can you please provide us with the following:

1) The native iOS instabug module version which can be found under : `node_modules/instabug-reactnative/ios/Instabug.framework/Info.plist`. You should find it under `Bundle versions string, short`.

2) Any other instabug integration code you use.

**Comment by Joao360** [comment]
@alyezz here's the requested info:

- iOS instabug module version 8.4

integration code:
```
import React, { Component } from 'react'
import { AppRegistry } from 'react-native'
import { Provider } from 'react-redux'
import { PersistGate } from 'redux-persist/integration/react'
import Instabug from 'instabug-reactnative'
import { store, persistor } from './store'

import App from './App'

class ConnectedApp extends Component {
  constructor(props) {
    super(props)

    Instabug.startWithToken(endpoints.instabugKey, [Instabug.invocationEvent.screenshot])
  }

  render () {
    return (
      <Provider store={store}>
        <PersistGate loading={null} persistor={persistor}>
          <App />
        </PersistGate>
      </Provider>
    )
  }
}

AppRegistry.registerComponent('myApp', () => ConnectedApp)

export default ConnectedApp
```

I also found out that if I run the app without attaching it to Xcode, reporting a problem works fine.

**Comment by alyezz** [comment]
@Joao360  We just Release 8.4.4. Update and let us know if you have any issues

**Comment by mattetre** [comment]
@Joao360 did 8.4.4 work for you? We just updated to 8.4.4 and we are seeing this issue

**Comment by alyezz** [comment]
@mattetre  we just release 8.5.0 the issue is fixed there.

The problem was that in some cases, `xhrNetworkInterceptor` library we use returned empty headers when trying to get the response's headers. We added some defensive coding to prevent this issue from happening again.

**Comment by Joao360** [comment]
@alyezz @mattetre , still didn't have a chance to test it, but will surely give you feedback when I do, thank you for the help!

**Comment by mattetre** [comment]
@alyezz does 8.50 require react native 0.60? We haven't upgraded yet (waiting on some of our Android dependencies to move to AndroidX)

**Comment by alyezz** [comment]
@mattetre no it doesn't require React Native 0.60

**Comment by mattetre** [comment]
Thanks @alyezz, 8.5.0 seems to fix the issues!
