### ISSUE TITLE
Android: Task :app:preDebugBuild FAILED (Could not find com.instabug.library:instabug:8.4.0.2.)

### ISSUE THREAD

**Issue by andrewheekin** [Instabug/Instabug-React-Native#322]
### SDK Version
8.4.4

### React Native, iOS and Android Versions
RN 0.59

### Device Model
Android

getting the following error on android:

```
info Building and installing the app on the device (cd android && ./gradlew app:installDebug)...
> Task :app:preDebugBuild FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Could not resolve all files for configuration ':app:debugCompileClasspath'.
> Could not find com.instabug.library:instabug:8.4.0.2.
Required by:
project :app > project :instabug-reactnative
```

**Comment by alyezz** [comment]
@andrewheekin we've switched away from Maven to our own repo available at https://sdks.instabug.com/nexus/repository/instabug-cp

Unlinking and linking again should add this automatically to your build.gradle file. You can also add it manually. Let me know if you have any issues with this.
