### ISSUE TITLE
Impossible to add to pod project

### ISSUE THREAD

**Issue by EJohnF** [Instabug/Instabug-React-Native#327]
### SDK Version
8.5.0

### React Native, iOS and Android Versions
react-native 0.56

It's building time problem. When I follow setup steps, after react-native link I've got new line in pod file
Then I run pod install
and it show this error: 
`[!] The 'Pods-quarters' target has frameworks with conflicting names: instabug.framework.`

I was struggling around for a long time. But solution for me was to downgrade instabug to 8.3.0 -> then pods installed correctly

**Comment by alyezz** [comment]
@EJohnF since you're using pods anyway, can you try deleting the framework in the following path `node_modules/instabug-reactnative/ios/instabug.framework` and then run pod install again

**Comment by EJohnF** [comment]
@alyezz yes, then pod install finish successfully

**Comment by EJohnF** [comment]
But this is still a problem... It requires to remove it after each modules installation

**Comment by alyezz** [comment]
@EJohnF yes, unfortunately there is no other way for us to support pre RN 0.60, cocoapods and non cocoapods projects, we will eventually migrate to React Native 0.60 and remove the framework from our side.

**Comment by otajor** [comment]
Shouldn't this be added to the readme? I just encountered the same thing by following the pod install instructions and had to look through here to find this solution.

Happy to make a PR if it would be accepted.

**Comment by alyezz** [comment]
@otajor we're currently looking into a solution to eliminate the need for this extra integration step
