### ISSUE TITLE
Tried to override RNInstabugReactnativeModule (autolinked?)

### ISSUE THREAD

**Issue by pbfrias17** [Instabug/Instabug-React-Native#331]
### Steps to Reproduce the Problem
I previously had instabug-reactnative installed fine, but upon upgrading to RN 0.60 and 8.5.0 (for this package) I'm having issues.
I ran these in the following order `react-native unlink instabug-reactnative`; `yarn remove instabug-reactnative`; `yarn add instabug-reactnative`; (I didn't even run `react-native add-instabug`, which im assuming is for iOS only anyway)

### Expected Behavior
Should run fine, but it does not.

### Actual Behavior
Builds fine. When I run I get the "Native module Instabug tried to override RNInstabugReactnativeModule." error. I'm not including that module or importing the package more than once. If I remove the below integration code, then i'll get a different error about needing to call "Instabug.Builder().build()" first.

### Instabug integration code

```
import com.instabug.reactlibrary.RNInstabugReactnativePackage;
...
List<ReactPackage> packages = new PackageList(this).getPackages()
packages.add(new RNInstabugReactnativePackage.Builder(BuildConfig.INSTABUG_TOKEN, 
    MainApplication.this)
        .setInvocationEvent("shake")
        .setPrimaryColor("#1D82DC")
        .setFloatingEdge("left")
        .setFloatingButtonOffsetFromTop(250)
        .build()
     );
```

### SDK Version

8.5.0

### React Native, iOS and Android Versions
RN 0.60.0

**Comment by taschik** [comment]
My solution to the problem was by adding this to the `react-native.config.js`:

```
module.exports = {
  project: {
    ios: {},
    android: {}, // grouped into "project"
  },
  dependencies: {
    'instabug-reactnative': {
      platforms: {
        android: undefined,
      },
    },
  },
}
```

This avoids it being linked automatically and takes the manual linked input from your `MainApplication.java`

**Comment by alyezz** [comment]
@pbfrias17 Since our library supports autolinking, you integration code should be as follows instead

```
List<ReactPackage> packages = new PackageList(this).getPackages();
      // Packages that cannot be autolinked yet can be added manually here, for example:
      // packages.add(new MyReactNativePackage());
      new RNInstabugReactnativePackage.Builder("YOUR_TOKEN",this.getApplication())
              .setInvocationEvent("shake")
              .build();
      return packages;
```

**Comment by pbfrias17** [comment]
@alyezz Thanks that makes sense. I didn't even think of calling `build()` without adding it to the PackageList.
