### ISSUE TITLE
IOS build fails after integrating 

### ISSUE THREAD

**Issue by prasadpilla** [Instabug/Instabug-React-Native#348]
"react-native": "0.57"
"instabug-reactnative": "^8.5.1"

After installing and linking the package, iOS build doesn't build.

Error: "Can't read property "invocationEventNone" of undefined.

**Comment by AliAbdelfattah** [comment]
It seems that the linking process has not been done properly. Please follow the steps in the docs to manually link the SDK in iOS and let us know how it goes https://docs.instabug.com/docs/react-native-integration#section-ios

**Comment by prasadpilla** [comment]
@AliAbdelfattah yes, it works after the manual linking, thnaks!
