### ISSUE TITLE
Add data to manual crash report

### ISSUE THREAD

**Issue by cxrod** [Instabug/Instabug-React-Native#350]
Hi, is there any way to add custom data when a crash is reported manually?

### SDK Version
8.5.1

### React Native, iOS and Android Versions
React Native 0.59.9

**Comment by AliAbdelfattah** [comment]
Hey @cxrod, have you tried `Instabug.onReportSubmitHandler`?

Example:
```js
    Instabug.onReportSubmitHandler((report) => {
      report.appendConsoleLog('My Log Message');
      report.setUserAttribute('key', 'value');
      report.appendTag('tag');
    });
```

**Comment by cxrod** [comment]
@AliAbdelfattah Thanks for you feedback! As I understand that function is executed in each report, correct? What I am looking for is a way to add meta data to reportJsException.

**Comment by HeshamMegid** [comment]
@cxrod can you give us an example of the type of data you want to add to the reported exception?

**Comment by cxrod** [comment]
Usually is a string, some object that may be involve in the crash parsed as JSON

**Comment by AliAbdelfattah** [comment]
@cxrod, unfortunately, we currently don't have a way to directly attach data to the API `reportJsException`. However, you can use other APIs to achieve what you need.

```js
    try {
      throw new SyntaxError();
    } catch (error) {
      Instabug.setUserAttribute("CRASH_DATA", "data");
      Instabug.reportJSException(error);
      Instabug.removeUserAttribute("CRASH_DATA");
    }
```

**Comment by HeshamMegid** [comment]
Closing this for now. Please feel free to reopen if you have any more questions.
