### ISSUE TITLE
Can't override string "Take a screen recording"

### ISSUE THREAD

**Issue by cxrod** [Instabug/Instabug-React-Native#351]
Hi,

There is no string key mapped to override "Take a screen recording" from the chat's attachment options.

### SDK Version
8.5.1

### React Native, iOS and Android Versions
0.59.9

**Comment by AliAbdelfattah** [comment]
@cxrod thanks for reporting this. We're looking into it.

**Comment by cxrod** [comment]
Also, the key `conversationsHeaderTitle` just mapped on Android.

**Comment by HeshamMegid** [comment]
We just released v8.5.3 that includes this fix.
