### ISSUE TITLE
Instabug.show() doesn't do anything in Android

### ISSUE THREAD

**Issue by prasadpilla** [Instabug/Instabug-React-Native#357]
### Steps to Reproduce the Problem
Show Instabug in Javascript manual method, Instabug.show() in Android

### Expected Behavior
It should show instabug dialogue 

### Actual Behavior
Nothing is happening, no logs in the console as well.

### Instabug integration code
new RNInstabugReactnativePackage.Builder(token, MainApplication.this)
                            .setInvocationEvent("shake", "button", "screenshot")
                            .setPrimaryColor("#00cf89")
                            .setFloatingEdge("left")
                            .setFloatingButtonOffsetFromTop(250)
                            .build()

### SDK Version
8.5.1

### React Native, iOS and Android Versions
0.57

**Comment by HeshamMegid** [comment]
@prasadpilla we automatically disable the SDK when the app token is incorrect. Can you please double check that the token is correct and has no leading or trailing whitespace?

**Comment by prasadpilla** [comment]
Hey @HeshamMegid , thanks for your quick response. I didn't change the token, but it got fixed after I fixed a few other issues in the build. But unfortunately, I don't have a specific root cause.
