### ISSUE TITLE
Instabug.setFloatingButtonEdge is not a function

### ISSUE THREAD

**Issue by SudoPlz** [Instabug/Instabug-React-Native#359]
Instabug.setFloatingButtonEdge is not a function

It's super simple, just try to use that, you'll see there's no implementation any more.
Please fix it.

### Steps to Reproduce the Problem
`Instabug.setFloatingButtonEdge(...)`

### Actual Behavior
Crash

### SDK Version
"instabug-reactnative": "^8.5.3",

### React Native, iOS and Android Versions
"react-native": "0.59.9",

### Device Model
iOS Simulator 12.4 (doesn't matter)

**Comment by SudoPlz** [comment]
Fix: https://github.com/Instabug/Instabug-React-Native/pull/360

**Comment by alyezz** [comment]
@SudoPlz Thanks for reporting this, we're looking into it and will release a hotfix soon

**Comment by alyezz** [comment]
@SudoPlz we just release 8.5.4 fixing this issue. Feel free to reopen this if you have any issues.
