### ISSUE TITLE
Change lintOption => abortOnError to false

### ISSUE THREAD

**Issue by predbjorn** [Instabug/Instabug-React-Native#363]
### Steps to Reproduce the Problem
build latest with react 

### Expected Behavior
build success

### Actual Behavior

> Task :instabug-reactnative:lint FAILED
Ran lint on variant debug: 2 issues found
Ran lint on variant release: 2 issues found
Wrote HTML report to file:/// xxx /node_modules/instabug-reactnative/android/build/reports/lint-results.html
Wrote XML report to file:/// xxx /node_modules/instabug-reactnative/android/build/reports/lint-results.xml

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':instabug-reactnative:lint'.
> Lint found errors in the project; aborting build.

  Fix the issues identified by lint, or add the following to your build script to proceed with errors:
  ...
  android {
      lintOptions {
          abortOnError false
      }
  }
  ...

  Errors found:

  xxx /node_modules/instabug-reactnative/android/src/main/java/com/instabug/reactlibrary/RNInstabugReactnativeModule.java:339: Error: Call requires API level 21 (current min is 16): setAutoScreenRecordingEnabled [NewApi]
              BugReporting.setAutoScreenRecordingEnabled(autoScreenRecordingEnabled);
                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



### SDK Version
"instabug-reactnative": "^8.5.4",

### React Native, iOS and Android Versions
react-native: 0.60.4, 

buildToolsVersion = "28.0.3"
supportLibVersion = "28.0.0"
minSdkVersion = 21
compileSdkVersion = 28
targetSdkVersion = 28

lintOptions {
      abortOnError false
      checkReleaseBuilds false
}


### FIX: 
Change lintOption => abortOnError to false

/node_modules/instabug-reactnative/android/build.gradle
lintOptions {
       warning 'InvalidPackage'
        abortOnError true => false 
    }

**Comment by AliAbdelfattah** [comment]
Hey @predbjorn, while I'm unable to reproduce this error, it seems from the error message that you're using the deprecated API `Instabug.setAutoScreenRecordingEnabled`. Please give `BugReporting.setAutoScreenRecordingEnabled` a shot and let us know if you're still having errors.
