### ISSUE TITLE
IBGpreSendingHandler is not a supported event type for InstabugReactBridge

### ISSUE THREAD

**Issue by nasmuris** [Instabug/Instabug-React-Native#365]
Hi, it seems that setting `onReportSubmitHandler` is not possible anymore, while not stated in docs?

### Steps to Reproduce the Problem
```Instabug.onReportSubmitHandler(() => { foo() });```
### Expected Behavior
should be working just fine as it did in previous versions
### Actual Behavior
red error screen: ```IBGpreSendingHandler is not a supported event type for InstabugReactBridge. Supported events are: IBGSendHandledJSCrash, IBGSendUnhandledJSCrash, IBGSetNetworkDataObfuscationHandler```
### SDK Version
Instabug-reactnative 8.5.5
### React Native, iOS and Android Versions
react native 0.60.5
### Device Model
iOS

**Comment by AliAbdelfattah** [comment]
@nasmuris, thanks for reporting this. We're looking into it.

**Comment by AliAbdelfattah** [comment]
@nasmuris, we're sorry you ran into this error. It's been fixed now in v8.5.6.
