### ISSUE TITLE
upload_sourcemap.sh could use some love

### ISSUE THREAD

**Issue by plowman** [Instabug/Instabug-React-Native#369]
Hey there. Apologies for not using the template. This is more of a feature request. Right now there are a bunch of deficiencies with upload_sourcemap.sh. Among them:
1. The script doesn't wait until it has an app token before compiling the sourcemap, meaning your build wastes easily 15-30 seconds creating a sourcemap it cannot possibly use.
2. If you have different staging/prod instabug instances it will never figure out what your API key is, because your instantiation call won't match the regex pattern of `Instabug.startWithToken('[a-zA-Z0-9]+')`
3. If you use the now preferred `Instabug.start` instead of `startWithToken`, it will also not find your app token.
4. Even if you do match the proper `Instabug.startWithToken` pattern, the script will then match your method call inside the `android_sourcemap.json` file it just created, and so the upload will still fail.
4. On Android, it is impossible to set an environment variable to specify `INSTABUG_APP_TOKEN` because `instabug-reactnative/android/build.gradle` overrides the `INSTABUG_APP_TOKEN` environment variable right before it's called.
5. The script creates `android-sourcemap.zip`, which it never uses. The file it does use, `android-sourcemap.json`, it does not delete once it's been uploaded.
6. And so forth...

Are there any plans to improve upload_sourcemap.sh? For example by allowing you to specify your APP_TOKEN in your build configuration or to disable the upload_sourcemap.sh script entirely? And if not, would you accept a PR? Thanks for taking a look.

**Comment by HeshamMegid** [comment]
@plowman thank you for pointing these out.

PRs are always welcome, but we're actively working on improving this and planning to address those issues in future releases.

I'll keep this issue open for further discussion about this as we work on it more.

**Comment by alyezz** [comment]
@plowman We included fixes/improvements for all of the above mentioned cases here: #375 

Fell free to reopen this if you still have any concerns
