### ISSUE TITLE
Bug! version 8.6.1.0 does not exist, should be 8.6.1 instead

### ISSUE THREAD

**Issue by OleksandrKucherenko** [Instabug/Instabug-React-Native#377]
https://github.com/Instabug/Instabug-React-Native/blob/018081bb91875cb75343cad997e49da8bf6fbd1f/android/build.gradle#L30

this line produce error during the compilation.

**Comment by HeshamMegid** [comment]
@OleksandrKucherenko we've switched away from Maven to our own repo available at https://sdks.instabug.com/nexus/repository/instabug-cp

Unlinking and linking again should add this automatically to your `build.gradle` file. You can also add it manually.

Feel free to reopen the issue if you're still having trouble with this.

**Comment by OleksandrKucherenko** [comment]
I think you don't get it... version 8.6.1.0 does not exists in repository exists only 8.6.1

When gradle try to resolve the dependency it fails. And it does not depend on repository hosting.

8.6.1 != 8.6.1.0 in Gradle terms

<img width="1340" alt="Screenshot 2019-08-30 at 08 21 07" src="https://user-images.githubusercontent.com/6419758/63997593-3cfa0400-caff-11e9-88f1-33e9e8ab43a2.png">

**Comment by OleksandrKucherenko** [comment]
@HeshamMegid ^ read comments please, and than re-open bug please

**Comment by HeshamMegid** [comment]
@OleksandrKucherenko the screenshot you have is from the Maven Central repo. As I mentioned above, we've switched away from Maven Central to our own repo. When you add the custom Maven repo URL to your `build.gradle` file, Gradle will be able to resolve version 8.6.1.0.

**Comment by OleksandrKucherenko** [comment]
Still, a bug. If you on purpose did this, then in gradle file should be registered custom repository. By default android gradle scripts know google, jcenter, mavenCenter repositories.

```groovy
repositories {
  maven { url "https://sdks.instabug.com/nexus/repository/instabug-cp/" }
}
```

**Comment by HeshamMegid** [comment]
> Still, a bug.

I'm not sure I understand. You're not able to resolve version 8.6.1.0 after adding the custom Maven repo using the snippet you mentioned above?

**Comment by OleksandrKucherenko** [comment]
I have an active project, I update the version of the module and it start fail.

So in two words: new version broke the build pipeline. Of course, I found solution in 30 seconds, but I'm confused that latest version break pipeline. Like nobody is interested in "smooth" version upgrades.

I point u on bug, so just apply the change and fix it.

Bug is in broken upgrade flow.

**Comment by HeshamMegid** [comment]
We definitely don't want to break builds for anyone updating from one Instabug version to another. We're not aware of any way to solve this issue automatically since the custom repo has to be in the app-level `build.gradle`, so we do our best to make those build-breaking changes visible in our changelog and upgrade guide on the repo's readme.

I'd love to know if you have suggestions on how to make the upgrade experience smoother for changes that will have to break builds for existing apps.
