### ISSUE TITLE
logUserEventWithNameAndParams no longer exists??????? (and complaints about constantly making BREAKING CHANGES)

### ISSUE THREAD

**Issue by SudoPlz** [Instabug/Instabug-React-Native#383]
Can you PLEAAAAAAAASE stop making **breaking** changes ALL the time?

You keep on making useless changes and break our code constantly, and you don't even bother making it super clear about what changes we need to make on our end.

I understand you may have made poor naming choices in method names in the past (we all do), but even so there are a ton of ways to fix those without breaking the existing code of your customers.
Plus, many the breaking changes you make, don't really add functionality, they just change method names and break our code... Why?

This time I found myself spending half an hour trying to figure why logs don't contain data any more. Why on earth did you remove [logUserEventWithNameAndParams](https://github.com/Instabug/Instabug-React-Native/blob/v8.0.26/index.js#L697) and why on earth isn't it clearly stated on some doc that's easy to find?

Searching `logUserEventWithNameAndParams` on your doc website returns nothing.

Apologies for my tone, but I've just went through that too many times so far (for no good reason), and I'm frustrated..

**Comment by HeshamMegid** [comment]
@SudoPlz please accept my apologies for that. I understand how frustrating it can be to have breaking changes when updating dependencies and not easily find documentation for those changes.

Most API changes happen to reflect changes in the product itself and how it’s evolving, while a smaller number of changes happen (as you mentioned) to have a more consistent naming convention that works with each platform.

Our strategy when it comes to this is to follow the semantic versioning rules, to only deprecate APIs and keep them working for a while before removing them, and to have migration guides and clear documentation for when those changes happen. We should be doing a better job at the latter.

The specific API you’re talking about was deprecated in v8.0, released 15 months ago, and removed in v8.6. We no longer support adding params to user events and there’s no alternative API to do this right now. 

We’d hate to see you waste time trying to figure out what APIs have changed and what to use instead, so if you’re having any more trouble migrating to the latest version, please let us know. In the meantime, we’re working on a more streamlined process for future API changes.

**Comment by SudoPlz** [comment]
> We no longer support adding params to user events and there’s no alternative API to do this right now.

Cool, so is that removed from the native SDK's as well?
Can I open a PR and add this functionality myself?

Thank you.

**Comment by HeshamMegid** [comment]
@SudoPlz this has been removed from the native SDKs as well. We still have full support for events, but we just dropped the ability to add parameters to them.

**Comment by SudoPlz** [comment]
Got it, so is this for the old instabug versions as well?
I mean can we no longer send event data even if we use old versions of the sdk?

Thanks

**Comment by HeshamMegid** [comment]
@SudoPlz yes, that's true. Older version of the SDK will let you send the data but it will be discarded and not visible on the dashboard.

**Comment by SudoPlz** [comment]
Cool, please make such changes more clear in the future, I'd really appreciate that, thanks.
