### ISSUE TITLE
Update documentation

### ISSUE THREAD

**Issue by cihati** [Instabug/Instabug-React-Native#388]
I see references to the method `setUserStepsEnabled` throughout different parts of Instabug documentation, but there's no such method. The relevant methods now are `setTrackUserSteps` and `setReproStepsMode`, I think.

**Comment by HeshamMegid** [comment]
Thanks @cihati for letting us know. We're on it.

**Comment by HeshamMegid** [comment]
We just updated the docs to reflect the method name changes.
