### ISSUE TITLE
Manual linking steps -> react-native link not working

### ISSUE THREAD

**Issue by WillyRamirez** [Instabug/Instabug-React-Native#397]
Hi, the react-native link command is not working for me (local issue). Could you please point me to the documentation containing the manual linking steps for both ios and android?

**Comment by alyezz** [comment]
@WillyRamirez Here you go https://docs.instabug.com/docs/react-native-integration#section-manual-linking

**Comment by WillyRamirez** [comment]
@alyezz thanks for pointing me in the right direction. I followed the docs and I ran into the same problem as shown in this thread:
https://github.com/Instabug/Instabug-React-Native/issues/322

I can't comment on the thread anymore as it has been closed. However, the link you posted in that comment is dead. How would i go about installing your own repo to get my instabug to work? 
And can this information be added to the manual-install docs?

**Comment by alyezz** [comment]
@WillyRamirez you just need to add the following maven repository to your project level gradle

```
allprojects {
	repositories {
	    maven {
	        url "https://sdks.instabug.com/nexus/repository/instabug-cp"
	    }
	}
}
```

**Comment by WillyRamirez** [comment]
Thanks!

**Comment by dancomanlive** [comment]
Worked. Auto-linking should be updated. Running > 60 and got this as error message:

```
Could not find com.instabug.library:instabug:8.7.0.0.
Required by:
    project :instabug-reactnative
```
