### ISSUE TITLE
BugReporting.show() not supported

### ISSUE THREAD

**Issue by nasmuris** [Instabug/Instabug-React-Native#398]
Hello,
I've discovered some problems with `BugReporting.show()` method in version 8.6.3
`index.d.ts` definitions:
```function showWithOptions(
    type: reportType,
    options: option[]): void;
  function show(
    type: reportType,
    options: option[]): void;
```

while `index.js` has only `show()` method, when using it with no parameters, I'm getting 
```Argument 0 (IBGBugReportingReportType) of IBGBugReporting.show must not be null```
Tested with iOS, but after checking the sourcecode, I assume the same behavior on android

**Comment by HeshamMegid** [comment]
Thanks for the report. We're on it.

**Comment by alyezz** [comment]
@nasmuris I think you are confusing `Instabug.show()` with `BugReporting.show(ReportType, Options)`. The first one invokes the SDK, the latter shows a specific report type (Bug, Feedback, Question). Feel free to reopen this if you have any questions.
