### ISSUE TITLE
adding INSTABUG_APP_TOKEN in my .env file didn't work. also, I have different tokens for ios/android.

### ISSUE THREAD

**Issue by HeshamMegid** [Instabug/Instabug-React-Native#417]
adding INSTABUG_APP_TOKEN in my .env file didn't work. also, I have different tokens for ios/android.

and how is this not enough?
```
task upload_sourcemap(type: Exec) {
    environment "INSTABUG_APP_TOKEN", project.env.get("INSTABUG_KEY_ANDROID")
    commandLine 'sh', './upload_sourcemap.sh'
}
```

_Originally posted by @newah in https://github.com/Instabug/Instabug-React-Native/issues/396#issuecomment-537393269_

**Comment by AliAbdelfattah** [comment]
Hi @newah, could you please clarify how it's not working? Are you getting any errors upon running `upload_sourcemap.sh` script?
