### ISSUE TITLE
Recording video on android is not working

### ISSUE THREAD

**Issue by tuannguyen041094** [Instabug/Instabug-React-Native#420]
When I use the recording screen in android I have 2 issues:
1. When I finish recording and press stop It is not saved on my form to submit
2. When I  recording the screen a go to report a bug form It's stopped my record and not save on the form either. 
Please help me solve this problem

**Comment by AliAbdelfattah** [comment]
Hi @tuannguyen041094, thanks for reporting this. We're looking into it.

Please fill in the issue template to help us reproduce it and fix it faster.

**Comment by tuannguyen041094** [comment]
Recording video on android is not working

Steps to Reproduce the Problem:
- Recording and press stop It is not saved on my form to submit
- Recording the screen a go to report a bug form It's stopped my record and not save on the form either.
Expected Behavior
 All recorded video should attach in instabug form.
Actual Behavior
Video must be save in instabug form to submit

SDK Version
8.7.1

React Native, Android Versions
React Native: 0.60.5
iOS: 12.4

**Comment by AliAbdelfattah** [comment]
Sorry @tuannguyen041094, we're not able to reproduce it. Could you check if you have enough disk space?

Also, to help us investigate further, we have a couple of questions for you.
- What's the Android version and the device model?
- Does the screenshot attachment appear in the report form?

**Comment by tuannguyen041094** [comment]
@AliAbdelfattah We have checked and there is enough space for it. 
Our android version is 8.1.0
screenshot attachment appears in report form, but not for recorded video.

**Comment by AliAbdelfattah** [comment]
@tuannguyen041094 unfortunately, we're still unable to reproduce the issue. Have you tried it across different devices? and please let us know the device model name you're testing on.

It'd also be great if you could provide a sample app where the issue is reproducible.
