### ISSUE TITLE
upload_sourcemap cut command only strips double quotes from INSTABUG_APP_TOKEN

### ISSUE THREAD

**Issue by jonczeck** [Instabug/Instabug-React-Native#421]
### Steps to Reproduce the Problem
If you use single quotes for your string, the sourcemap script breaks.

This doesn't work:
`Instabug.startWithToken('AppTokenHere', [Instabug.invocationEvent.shake]);`

This does:
`Instabug.startWithToken("AppTokenHere", [Instabug.invocationEvent.shake]);`

If you have prettier or something enforcing single quoted strings, you can work around this issue by putting the double quoted version in a comment.

edit: Just to be clear, you have to put the comment before the real line so grep finds it first.

**Comment by AliAbdelfattah** [comment]
@jonczeck thanks for reporting this, we're looking into it.

**Comment by AliAbdelfattah** [comment]
@jonczeck we've found the cause of the issue, we've fixed it and it'll be available in the next release. You'll be able to use single quotation marks and won't have to work around it.
