### ISSUE TITLE
null is not a object evaluating IBGBugReporting.show

### ISSUE THREAD

**Issue by Akash-T2S** [Instabug/Instabug-React-Native#425]
### Steps to Reproduce the Problem
Below line added to make comments required.

BugReporting.showWithOptions([BugReporting.option.commentFieldRequired]);

### Expected Behavior

Should make comments field mandatory.

### Actual Behavior

Throws error, null is not an object evaluating IBGBugReporting.show

### SDK Version

8.7.1

### React Native, iOS and Android Versions

RN version - 0.59.9
iOS - 12

### Device Model

iPhone 7 plus

**Comment by AliAbdelfattah** [comment]
@Akash-T2S thanks for reporting this. We're looking into it.

**Comment by AliAbdelfattah** [comment]
Hi @Akash-T2S, the API `BugReporting.showWithOptions` is missing the first parameter, the report type you're trying to show here; e.g., bug, feedback, question.

Here's an example:
```
BugReporting.showWithOptions(BugReporting.reportType.bug, [BugReporting.invocationOptions.commentFieldRequired]);
```

To set the invocation options for all report types, there's a different API for that:
```
BugReporting.setOptions([BugReporting.invocationOptions.commentFieldRequired]);
```

Feel free to reopen the issue if it's still throwing an error.
