### ISSUE TITLE
React Native - Android compilation fails on SDK v8.7.1 (ReactNative v0.61.2)

### ISSUE THREAD

**Issue by azizuysal** [Instabug/Instabug-React-Native#426]
### Steps to Reproduce the Problem
Following the [integration steps](https://docs.instabug.com/docs/react-native-integration) as outlined in your documentation, iOS app seems to work fine but Android app fails to compile.

#### Additional issues:
Probably not needed to resolve the main issue above, but I want to report these as well, hoping you'd fix them too.

1) The various SDK integration instructions for react-native are conflicting and does not seem to be up to date:
https://docs.instabug.com/docs/react-native-integration
https://dashboard.instabug.com/applications/test/beta/settings/sdk-integrations
https://github.com/Instabug/Instabug-React-Native

I followed the first one which seemed the more up-to-date one but unfortunately it doesn't seem to work.

2) Also, probably unrelated, but while testing the iOS build, I see a notification on the web dashboard that says:
`test is not using the latest version of the SDK. Please update to version to be able to use all the features.`
The message is worded like it'd mention a version number, but doesn't. And I'm using the latest version (8.7.1) available in npm repo.

### Expected Behavior
Instabug SDK should be integrated and work as expected in both Android and iOS.
### Actual Behavior
iOS app compiles and works fine with Instabug integration. Android app fails during compile:
```
react-native run-android

info Running jetifier to migrate libraries to AndroidX. You can disable it using "--no-jetifier" flag.
Jetifier found 1044 file(s) to forward-jetify. Using 8 workers...
info JS server already running.
info Installing the app...

> Task :app:compileDebugJavaWithJavac FAILED

Deprecated Gradle features were used in this build, making it incompatible with Gradle 6.0.Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/5.5/userguide/command_line_interface.html#sec:command_line_warnings
134 actionable tasks: 3 executed, 131 up-to-date
/Users/dev/test/android/app/src/main/java/com/dev/test
/android/MainApplication.java:44: error: package RNInstabugReactnativePackage doe
s not exist
    new RNInstabugReactnativePackage.Builder("IOS_APP_TOKEN", 
MainApplication.this)
                                    ^
1 error

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 4s
```
### Instabug integration code

`yarn add instabug-reactnative`
`react-native add-instabug `
`cd ios && pod install && cd .. `

Then in App.js:
`import Instabug, { BugReporting, Surveys, FeatureRequests } from 'instabug-reactnative';`
`Instabug.startWithToken('IOS_APP_TOKEN', [Instabug.invocationEvent.shake]);`

And in MainApplication.java:
```@Override
   public void onCreate() {
     new RNInstabugReactnativePackage
             .Builder("APP_TOKEN", MainApplication.this)
             .setInvocationEvent("shake")
             .setPrimaryColor("#1D82DC")
             .setFloatingEdge("left")
             .setFloatingButtonOffsetFromTop(250)
             .build();
     super.onCreate();
     SoLoader.init(this, /* native exopackage */ false);
   }
```

### SDK Version

8.7.1

### React Native, iOS and Android Versions
iOS 13.1
RN 0.61.2
Android: 28.0.3

**Comment by AliAbdelfattah** [comment]
@azizuysal thank you for the extensive report!

We're currently working on enhancing the process of updating the docs more consistently across our platforms, we totally understand how frustrating it can be to follow outdated docs. Regarding the update message showing on your dashboard, we've recently fixed an issue related to that, let us know if you're still seeing it.

As for the compilation issue, let me look into that and get back to you.

**Comment by ste00martin** [comment]
@AliAbdelfattah could you update the React Native docs on Instabug's website? They don't have this step added in
