### ISSUE TITLE
App Crash using setViewHierarchyEnabled

### ISSUE THREAD

**Issue by jphilipstevens** [Instabug/Instabug-React-Native#429]
# Steps to Reproduce the Problem

run an ios app on a simulator or device

### Expected Behavior
The app loads with the welcome mode

### Actual Behavior
app crashes with an error:
TypeError: IBGBugReporting.setViewHierarchyEnabled is not a function. (In 'IBGBugReporting.setViewHierarchyEnabled(viewHierarchyEnabled)', 'IBGBugReporting.setViewHierarchyEnabled' is undefined)
- node_modules/instabug-reactnative/modules/BugReporting.js:177:44 in setViewHierarchyEnabled
* app/app.js:84:41 in componentWillMount
- node_modules/react-native/Libraries/Renderer/oss/ReactNativeRenderer-dev.js:7430:4 in callComponentWillMount
- node_modules/react-native/Libraries/Renderer/oss/ReactNativeRenderer-dev.js:7576:27 in mountClassInstance
- ... 19 more stack frames from framework internals

### Instabug integration code
in app.js import Instabug, { BugReporting } from "instabug-reactnative";

inside comonentWillMount method

  Instabug.setWelcomeMessageMode(Instabug.welcomeMessageMode.beta);
  Instabug.setCrashReportingEnabled(true);
  Instabug.startWithToken(<redacted>, [
      Instabug.invocationEvent.twoFingersSwipe
   ]);
   BugReporting.setViewHierarchyEnabled(true);
  

### SDK Version
8.7.2, and 8.7.3

### React Native, iOS and Android Versions
RN 0.59.8 
iOS 13.1.2 
Android N/A

### Device Model
- iPad Air 2, iPhone 11
- PRO Max simulator

**Comment by alyezz** [comment]
@jphilipstevens thanks for the detailed report, we're looking into it

**Comment by alyezz** [comment]
@jphilipstevens we just release a hotfix for that v8.7.3. Please update and feel free to reopen this if you're still facing the issue.
