### ISSUE TITLE
Unless a name is there, the user email won't be stored either.

### ISSUE THREAD

**Issue by SudoPlz** [Instabug/Instabug-React-Native#432]
Hey there,

I spent half an hour again trying to debug an issue that I discovered today (users were unidentified, eventhough we were setting their email address).
After debugging your native code I noticed that unless the name of a customer is a non empty string, the email won't be taken into account!

If that is the expected behaviour (I don't see any reason why), at least add it to the docs.

### Steps to Reproduce the Problem
Run `Instabug.identifyUserWithEmail("anEmail@example.com, "");`

### Expected Behavior
After invoking instabug, the email field should be prefilled

### Actual Behavior
The email field is empty.

### SDK Version
"instabug-reactnative": "^8.7.3",

### React Native, iOS and Android Versions
Android

**Comment by HeshamMegid** [comment]
@SudoPlz thanks for the report. We're working on changing the API so that the name parameter would be an optional nullable without affecting whether the email is retained or not.

Will let you know once we release this.

**Comment by alyezz** [comment]
@SudoPlz we just release v9.0.0, this release includes a fix for this issue.

Feel free to reopen this if you still have any issues

**Comment by SudoPlz** [comment]
Perfect, thanks @alyezz
