### ISSUE TITLE
Strings in index.d.ts do not match index.js

### ISSUE THREAD

**Issue by gcottrell1** [Instabug/Instabug-React-Native#433]
There are discrepancies between the exported `strings` in `index.d.ts` and `index.js`. For example `index.js` includes `reportQuestionDescription`, but `index.d.ts` does not

### SDK Version

8.7.3
### React Native, iOS and Android Versions
N/A
### Device Model

N/A
### [Optional] Project That Reproduces the Issue

N/A

**Comment by alyezz** [comment]
@gcottrell1 thanks for the report, we're looking into it

**Comment by alyezz** [comment]
@gcottrell1 we just release v9.0.0, this release includes a fix for this issue.

Feel free to reopen this if you still have any issues
