### ISSUE TITLE
Bashism in upload_sourcemap.sh

### ISSUE THREAD

**Issue by Yuras** [Instabug/Instabug-React-Native#436]
The `upload_sourcemap.sh` fails because `[[` [here](https://github.com/Instabug/Instabug-React-Native/blob/dbaccb4e448e7c6c1805e27c6a467d60e7bcb160/android/upload_sourcemap.sh#L5) is specific to `bash` and not supported in POSIX `sh`.

The solution could be either to replace bashism with a language construct supported by POSIX `sh`, or actually use `bash` [here](https://github.com/Instabug/Instabug-React-Native/blob/master/android/build.gradle#L48)

Also [shellcheck](https://www.shellcheck.net) reports a number of other issues with `upload_sourcemap.sh`, you may want to check it:

```
Line 5:
if [[ -s "$HOME/.nvm/nvm.sh" ]]; then
   ^-- SC2039: In POSIX sh, [[ ]] is undefined.
 
Line 6:
. "$HOME/.nvm/nvm.sh"
  ^-- SC1090: Can't follow non-constant source. Use a directive to specify location.
 
Line 7:
elif [[ -x "$(command -v brew)" && -s "$(brew --prefix nvm)/nvm.sh" ]]; then
     ^-- SC2039: In POSIX sh, [[ ]] is undefined.
 
Line 8:
. "$(brew --prefix nvm)/nvm.sh"
  ^-- SC1090: Can't follow non-constant source. Use a directive to specify location.
 
Line 14:
    INSTABUG_APP_TOKEN=$(grep -r --exclude-dir={node_modules,ios,android} "Instabug.start[WithToken]*([\"\'][0-9a-zA-Z]*[\"\']" ./ -m 1 | grep -o "[\"\'][0-9a-zA-Z]*[\"\']" | cut -d "\"" -f 2 | cut -d "'" -f 2)
                                               ^-- SC2039: In POSIX sh, brace expansion is undefined.
 
Line 21:
    echo "Instabug: Token found" "\""${INSTABUG_APP_TOKEN}"\""
                                     ^-- SC2027: The surrounding quotes actually unquote this. Remove or escape them.
                                     ^-- SC2086: Double quote to prevent globbing and word splitting.

Did you mean: (apply this, apply all SC2086)
    echo "Instabug: Token found" "\"""${INSTABUG_APP_TOKEN}""\""
```

### Steps to Reproduce the Problem
The issue occurs on Unix when `/bin/sh` is not `bash`. E.g. on Debian they usually use `dash` for `/bin/sh`. Create a sample project, integrate instabug and run `./gradlew assembleRelease`

### Expected Behavior
Task `:instabug-reactnative:upload_sourcemap` should succeed

### Actual Behavior
```
./upload_sourcemap.sh: 5: [[: not found
Instabug: Looking for Token...
./upload_sourcemap.sh: 7: [[: not found
```

### SDK Version
`instabug-reactnative-8.7.3`

### React Native, iOS and Android Versions
`react-native-0.60.6`, any android version.

**Comment by HeshamMegid** [comment]
Thanks for the detailed report. We're working on a fix.

**Comment by AliAbdelfattah** [comment]
Sorry for the late reply. We haven’t received any requests to support POSIX since the issue was raised and that got the issue moved down our priority list. Unfortunately, we currently have no plans to support POSIX in the near future. However, this can change depending on the number of requests on this or the priorities in our backlog. We apologize for any inconvenience this may have caused.
