### ISSUE TITLE
App store rejection

### ISSUE THREAD

**Issue by kimobrian** [Instabug/Instabug-React-Native#437]
### Steps to Reproduce the Problem
- Install the library and submit your app to the store.

### Expected Behavior
- The app should be accepted.

### Actual Behavior
- The app is rejected with the following reason.

> TMS-90683: Missing Purpose String in Info.plist - Your app's code references one or more APIs that access sensitive user data. The app's Info.plist file should contain a NSBluetoothPeripheralUsageDescription key with a user-facing purpose string explaining clearly and completely why your app needs the data.

I did a grep on the ios folder to see any traces of bluetooth and this is one of them:

![image](https://user-images.githubusercontent.com/22055697/70261647-ee19d580-17a3-11ea-8274-5af3ffc66d0d.png)

Why is instabug using Corebluetooth which in turn prevents me from submitting the app without providing a reason why.

### SDK Version
   -  "instabug-reactnative": "^8.7.3"

### Device Model
- App store submission

**Comment by AliAbdelfattah** [comment]
Thanks for reporting this. We're looking into it.

**Comment by AliAbdelfattah** [comment]
Hi @kimobrian, we don't use _CoreBluetooth_ in our SDK. Also, I was unable to reproduce this on my side using the grep command.

I'd suggest you reinstall node modules and check again:
`rm -rf node_modules && yarn`
