### ISSUE TITLE
Welcome banner showing on Android without starting module

### ISSUE THREAD

**Issue by marcusmolchany** [Instabug/Instabug-React-Native#442]
### Steps to Reproduce the Problem
1. install `instabug-reactnative` on your react native project
2. run on android
3. import the module in whatever your main file is. _DO NOT_ `.start()` or `.startWithToken()` the module

### Expected Behavior
Instabug should not have started. You should not have seen the welcome message ("We are happy to hear your thoughts").

### Actual Behavior
Some part of Instabug initializes and you will see the welcome message

### Instabug integration code

```js
import Instabug from 'instabug-reactnative';
```

### SDK Version

```
"instabug-reactnative": "^9.0.0",
```

### React Native, iOS and Android Versions
Expo SDK 35 (React Native 59)
Android 29

### Device Model

All Android devices

### Related issues
- [https://github.com/Instabug/Instabug-React-Native/issues/135](https://github.com/Instabug/Instabug-React-Native/issues/135)
- [https://github.com/Instabug/Instabug-React-Native/issues/393](https://github.com/Instabug/Instabug-React-Native/issues/393)
- [https://github.com/Instabug/Instabug-React-Native/issues/250](https://github.com/Instabug/Instabug-React-Native/issues/250)
- [https://github.com/Instabug/Instabug-React-Native/issues/193](https://github.com/Instabug/Instabug-React-Native/issues/193)

### [Optional] Project That Reproduces the Issue

give me a second to repro this

**Comment by marcusmolchany** [comment]
To shed some more light on the situation, I'm trying to conditionally start Instabug based on whether or no a user is an admin in our system. Based on the API I was hoping I could not `.start()` Instabug until I could check to see the users role. This works on iOS, however on Android I'm running into the issue described above.

**Comment by alyezz** [comment]
@marcusmolchany the android SDK is initialized in the Application class on the android side therefore there is no way to conditionally start it, If you wish you can disable the welcome message using the API `Instabug.setWelcomeMessageMode(false);` .

**Comment by marcusmolchany** [comment]
ah, that makes a ton of sense. thanks!

**Comment by marcusmolchany** [comment]
@alyezz I tried setting that in the javascript code and the welcome message was still showing on Android.

I changed the code in `node_modules/instabug-reactnative/android/src/main/java/com/instabug/reactlibrary/RNInstabugReactnativeModule.java` to match what was said here https://github.com/Instabug/Instabug-React-Native/issues/193#issuecomment-417176631 and that worked. This won't work longterm unless we fork the package. Any thoughts?

Also, is there a way to expose `Instabug.setWelcomeMessageState()` from `MainApplication.java`?

**Comment by alyezz** [comment]
@marcusmolchany Yes you can ass it to the `MainApplication.java` After the builder
`Instabug.setWelcomeMessageState(WelcomeMessage.State.DISABLED);`

**Comment by marcusmolchany** [comment]
@alyezz do you know the syntax for that? I'm using this react native package and do not have `Instabug` or `WelcomeMessage` namespaces available.

**Comment by alyezz** [comment]
@marcusmolchany Just add the following imports to the `MainApplication.java`
```import com.instabug.library.Instabug;
import com.instabug.library.ui.onboarding.WelcomeMessage;```

And then add the line `Instabug.setWelcomeMessageState(WelcomeMessage.State.DISABLED);`
after the `RNInstabugReactnativePackage.Builder` call

**Comment by marcusmolchany** [comment]
awesome, that worked. thanks so much
