### ISSUE TITLE
How can we disable **Upload Sourcemap** when we build ios app?

### ISSUE THREAD

**Issue by pengcao1** [Instabug/Instabug-React-Native#443]
**[21:51:51]: ▸ Running script 'Upload Sourcemap'**  cost more 30 min every times.

Is there anyway to disable this action?

**Comment by alyezz** [comment]
@pengcao1 Sure, open xcode and go to build phases and remove the entry `Upload Sourcemap`
![Screen Shot 2020-01-15 at 10 45 57 AM](https://user-images.githubusercontent.com/10798072/72418862-576a0c80-3784-11ea-9585-f1d7ffcde60c.png)

**Comment by pengcao1** [comment]
Thank your reply. 

I also want to customize this `Upload Sourcemap`. 

eg: 
under QA/UAT, I don't want to upload the sourcemap file to instabug dashboard
under Prod, I want to upload the sourcemap file to the Instabug dashboard.

**Comment by alyezz** [comment]
@pengcao1 you can expand `Upload Sourcemap` to find: 
![Screen Shot 2020-01-15 at 10 56 10 AM](https://user-images.githubusercontent.com/10798072/72419576-c7c55d80-3785-11ea-8a04-1c992fd7819f.png)

Add a check to conditionally run the command  `bash "../node_modules/instabug-reactnative/ios/upload_sourcemap.sh"` based on your Env.

Hope this helps
