### ISSUE TITLE
Upgrade 8.0 to 9.0.1: JSON value '0' of type NSNumber cannot be converted to NSArray

### ISSUE THREAD

**Issue by jjblumenfeld** [Instabug/Instabug-React-Native#444]
## Steps to Reproduce the Problem
Upgraded existing integration from instabug-reactnative 8.0.26 to 9.0.1
Updated the API methods to the 9.x versions.

### Expected Behavior
Instabug would launch without errors.

### Actual Behavior
Instabug Launches with error: 
JSON value '0' of type NSNumber cannot be converted to NSArray

+[RCTConvert NSArray:]
    RCTConvert.m:54
__41-[RCTModuleMethod processMethodSignature]_block_invoke_16
-[RCTModuleMethod invokeWithBridge:module:arguments:]
facebook::react::invokeInner(RCTBridge*, RCTModuleData*, unsigned int, folly::dynamic const&)
facebook::react::RCTNativeModule::invoke(unsigned int, folly::dynamic&&, int)::$_0::operator()() const
invocation function for block in facebook::react::RCTNativeModule::invoke(unsigned int, folly::dynamic&&, int)
_dispatch_call_block_and_release
_dispatch_client_callout
_dispatch_main_queue_callback_4CF
__CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__
__CFRunLoopRun
CFRunLoopRunSpecific
GSEventRunModal
UIApplicationMain
main
start
0x0

### Instabug integration code
file: app/app.js
```
import Instabug, { BugReporting } from 'instabug-reactnative';

if (Platform.OS === 'ios') {
  Instabug.start(InstabugToken, [Instabug.invocationEvent.none]);
  Instabug.setTrackUserSteps(true);
}
BugReporting.setReportTypes(false, true, true);
```
### SDK Version
9.0.1

### React Native, iOS and Android Versions
RN: 0.59.10
iOS 13.1

### Device Model
Running in simulator for various iOS devices.

**Comment by alyezz** [comment]
@jjblumenfeld the following API was changed:
Old usage:
`BugReporting.setReportTypes(false, true, true);`

Instead it now accepts an array of report types that you want

New usage: 
`BugReporting.setReportTypes([
      BugReporting.reportType.bug,
      BugReporting.reportType.feedback,
      BugReporting.reportType.question
    ]);`

feel free to re-open this if you still have any issues/ questions

**Comment by jjblumenfeld** [comment]
Thanks,.
Do you have more details on the transition from the old usage to new usage?
I don't know what the old usage of (false, true, true) translates to in the
new usage.

**Comment by alyezz** [comment]
@jjblumenfeld so that would translate to `BugReporting.setReportTypes([ BugReporting.reportType.bug, BugReporting.reportType.feedback]);`
