### ISSUE TITLE
"onReportSubmitHandler" fires too early

### ISSUE THREAD

**Issue by jd20** [Instabug/Instabug-React-Native#454]
### Steps to Reproduce the Problem
Setup a handler like so:

```javascript
Instabug.onReportSubmitHandler((report) => console.log(report))
```

### Expected Behavior
According to the docs, the handler should be fired right before the report is submitted. If I wanted to collect meaningful info from the report (such as the message entered, tags, attachments, etc...) I'd be able to do so from the `report` param that is passed.

### Actual Behavior
The listener is called as soon as Instabug is invoked (more like `willInvokeHandler` behavior), and the data on the `report` parameter is always empty. There doesn't seem to be a way to get a callback after the user has filled out the report (other than the `IBGpostInvocationHandler` event, but that only gives `dismissType` and `reportType`, not the report data).

### Instabug integration code
See the repro steps above.

### SDK Version
9.0.6

### React Native, iOS and Android Versions
"react-native": "0.61.5"
"react": "16.9.0"
iOS: 13

### Device Model
Testing on iOS specifically.

**Comment by AliAbdelfattah** [comment]
Hi @jd20, thanks for reporting this. We're looking into it.

**Comment by AliAbdelfattah** [comment]
Hi @jd20, the purpose of `Instabug.onReportSubmitHandler` is to add your own additional logs to the report before sending it out, the report attributes data represent these additional data. This is why it gets invoked before you actually press Submit. Here's an example:
```
    Instabug.onReportSubmitHandler(report => {
      report.appendConsoleLog('Log Message');
      console.log(report.consoleLogs[0]); // prints "Log Message"
    });
```

Here's the full list of APIs you can invoke before the report is submitted.
<img width="1556" alt="Screen Shot 2020-02-06 at 18 33 05" src="https://user-images.githubusercontent.com/10587548/73958083-0a570180-4910-11ea-8870-e4a692052614.png">

Please let us know if it's still unclear.

**Comment by jd20** [comment]
I see that I can push data into the report, what I was looking for was a way to pull out user-entered data from the report when it is submitted. For example, if user entered e-mail or description fields, or added a screenshot / video, there does not seem to be a callback that would give my app access to that information?

**Comment by AliAbdelfattah** [comment]
@jd20 sorry it took a while to get back to you. Unfortunately, it isn't possible to access this data through the SDK. I'm closing the issue for now, please feel free to reopen.
