### ISSUE TITLE
The number of method references in a .dex file cannot exceed 64K.

### ISSUE THREAD

**Issue by AndrewMorsillo** [Instabug/Instabug-React-Native#455]
I'm attempting to integrate end to end testing with [Detox](https://github.com/wix/Detox). When attempting to build the test configuration for Android per the docs there, the build fails on the step:

```
Execution failed for task ':instabug-reactnative:mergeDexDebugAndroidTest'.
> com.android.build.api.transform.TransformException: java.lang.RuntimeException: java.lang.RuntimeException: com.android.builder.dexing.DexArchiveMergerException: Error while merging dex archives:
  The number of method references in a .dex file cannot exceed 64K.
  Learn how to resolve this issue at https://developer.android.com/tools/building/multidex.html
```

The strange thing is, I have multiDex enabled and working. The normal debug and release builds of my project work fine. It is only when attempting to build a testing configuration that multiDex appears to get ignored.

I'm not sure if this is an issue with Instabug or with Detox since I'm not very familiar with the Android build system.

### Steps to Reproduce the Problem
Add Detox test configuration to Android in a react-native project with Instabug integrated.

### Expected Behavior
Build uses multidex and works as expected

### Actual Behavior
Multidex appears to be ignored causing a dex methods count error

### SDK Version
9.0.6

### React Native, iOS and Android Versions

```
System:
    OS: macOS 10.15.3
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
    Memory: 158.98 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.10.0 - ~/.nvm/versions/node/v12.10.0/bin/node
    Yarn: 1.19.2 - ~/.yarn/bin/yarn
    npm: 6.10.3 - ~/.nvm/versions/node/v12.10.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.6010548
    Xcode: 11.3.1/11C504 - /usr/bin/xcodebuild
  npmPackages:
    @react-native-community/cli: ^3.0.4 => 3.0.4
    react: 16.9.0 => 16.9.0
    react-native: ^0.61.5 => 0.61.5
```

**Comment by AliAbdelfattah** [comment]
Hi @AndrewMorsillo, thanks for reporting this. I've enabled the multidex from our Android side and here's a custom build with the fix. Could you give it a try and let me know if it fixes your issue please?

```
npm install --save https://github.com/Instabug/Instabug-React-Native#custom/android-multidex
```

**Comment by AndrewMorsillo** [comment]
@AliAbdelfattah That works! Will multidex be enabled for a future official release?

**Comment by AliAbdelfattah** [comment]
@AndrewMorsillo glad it worked! We'll definitely include it in the next release.
