### ISSUE TITLE
identifyUserWithEmail doesn't work on Android. Works fine for iOS.

### ISSUE THREAD

**Issue by N1ghtly** [Instabug/Instabug-React-Native#462]
### Steps to Reproduce the Problem

Call `Instabug.identifyUserWithEmail("example@mail.com", "")` on startup.

### Expected Behavior
When opening the Bug Reporting modal, email is prefilled.

### Actual Behavior
When opening the Bug Reporting modal, email is empty on Android. works on iOS.

### SDK Version
8.7.1

### React Native, iOS and Android Versions
RN 0.61.5

**Comment by AliAbdelfattah** [comment]
Hi @N1ghtly, the issue has been fixed on the latest version, please update your SDK.

Closing the issue now, please feel free to reopen if it still occurs after the update.
