### ISSUE TITLE
Do you support codeless analytics for screen views

### ISSUE THREAD

**Issue by MikePendo** [Instabug/Instabug-React-Native#463]
Is there any support for screen views analytics without code (like in google analytics) for native apps?

**Comment by AliAbdelfattah** [comment]
No, we don't provide analytics for screen views. However, our SDK can help you with:
- Detecting issues before each release.
- Reproducing and fixing bugs faster while debugging.
- Tracking and ensuring release stability.
- Collecting feedback and validating ideas.
- Driving positive app reviews.

Please let me know if you have other questions regarding the SDK.
