### ISSUE TITLE
Android build exception in task :app:processDebugResources for React Native 0.61.5 and SDK 9.0.6

### ISSUE THREAD

**Issue by jonczeck** [Instabug/Instabug-React-Native#464]
### Steps to Reproduce the Problem
Test repo: https://github.com/jonczeck/instabug-react-native-android-test

1. Init a react-native application with `npx react-native init InstabugReactNativeTest --template react-native-template-typescript` (At the time of writing, that is using react-native 0.61.5)
2. `cd InstabugReactNativeTest`
3. `npm i`
4. Go through steps 1, 2 and 3 at https://github.com/Instabug/Instabug-React-Native/blob/master/README.md#using-react-native-cli
5. Go through all steps under https://github.com/Instabug/Instabug-React-Native/blob/master/README.md#using-instabug taking the path for >= 0.60 as we are on 0.61.5
6. `npx react-native run-android`
7. Build failure.

### Expected Behavior

App builds.

### Actual Behavior

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugResources'.
> Android resource linking failed
  (path)/InstabugReactNativeTest/android/app/build/intermediates/merged_manifests/debug/AndroidManifest.xml:138: AAPT: error: attribute android:foregroundServiceType not found.
`

Looking at the block referenced in the merged AndroidManifest.xml:
```
	<service
	    android:name="com.instabug.library.internal.video.ScreenRecordingService"
	    android:enabled="true"
	    android:exported="false"
	    android:foregroundServiceType="mediaProjection" />
```

### Instabug integration code
React Native:
```import Instabug from 'instabug-reactnative';
// etc

const App = () => {
  useEffect(() => {
    Instabug.startWithToken('token', [Instabug.invocationEvent.floatingButton]);
  }, []);
  return ( <View /> );
};```

Gradle:

```    repositories {
        //etc
    	maven {
      	    url "https://sdks.instabug.com/nexus/repository/instabug-cp"
       	}  
      }
}
```
Java:
```import com.instabug.reactlibrary.RNInstabugReactnativePackage;
// etc

  @Override
  public void onCreate() {
    super.onCreate();
    new RNInstabugReactnativePackage
    .Builder("token", MainApplication.this)
    .setInvocationEvent("FLOATING_BUTTON")
    .setPrimaryColor("#1D82DC")
    .setFloatingEdge("left")
    .setFloatingButtonOffsetFromTop(250)
    .build();
    SoLoader.init(this, /* native exopackage */ false);
    initializeFlipper(this); // Remove this line if you don't want Flipper enabled
  }
 ```
### SDK Version
9.0.6

### React Native, iOS and Android Versions
React Native v0.61.5
Android targetSdkVersion: 28

**Comment by alyezz** [comment]
@jonczeck Please change your android compileSDK version to 29
