### ISSUE TITLE
Send reports via a HTTP Proxy

### ISSUE THREAD

**Issue by chanind** [Instabug/Instabug-React-Native#468]
Is there a way to send reports via a HTTP Proxy? We have an app with some users in China, so if Instabug is going to send reports directly across the firewall a lot of the requests will fail. I'd like to set up a http proxy as an intermediary for the requests sent from China, but I can't find an option to set an HTTP proxy in the react native client.

**Comment by alyezz** [comment]
@chanind Unfortunately, there is no way to do so because all the requests our SDK send are from the native side rather than js side

**Comment by chanind** [comment]
Should I open an issue in the native SDK repos then?
