### ISSUE TITLE
shake causes iOS getting freeze when onReportSubmitHandler called

### ISSUE THREAD

**Issue by jayasme** [Instabug/Instabug-React-Native#475]
### Steps to Reproduce the Problem

1) Handle onReportSubmitHandler with a callback
```javascript
InstabugRn.onReportSubmitHandler((report: Report) => {
      if (this.reportTags && this.reportTags.length) {
        // add tags for individual report
        for (const tag of this.reportTags) {
          report.appendTag(tag);
        }
        // reset the report tags
        this.reportTags = [];
      }
    });
```

2) Enable shake to call out the bug report
```javascript
InstabugRn.startWithToken(this.appToken, [InstabugRn.invocationEvent.shake]);
```

3) Run the App
4) Shake the phone

I found eventually it's about the invisible function in the Instabug's iOS SDK `setWillSendReportHandler_private` call causing the freeze, if I just replace it with 
```objective-c
Instabug.willSendReportHandler = ^IBGReport * _Nonnull(IBGReport * _Nonnull report) {
            NSArray *tagsArray = report.tags;
             NSArray *instabugLogs= report.instabugLogs;
             NSArray *consoleLogs= report.consoleLogs;
             NSDictionary *userAttributes= report.userAttributes;
             NSArray *fileAttachments= report.fileLocations;
             NSDictionary *dict = @{ @"tagsArray" : tagsArray, @"instabugLogs" : instabugLogs, @"consoleLogs" : consoleLogs,       @"userAttributes" : userAttributes, @"fileAttachments" : fileAttachments};
            [self sendEventWithName:@"IBGpreSendingHandler" body:dict];

            currentReport = report;
            return report;
        };
```
and 
```objective-c
RCT_EXPORT_METHOD(submitReport) {
    if (globalReportCompletionHandler && currentReport) {
        globalReportCompletionHandler(currentReport);
    }
    currentReport = nil;
}
```
Everything goes fine, but I am very concerned `globalReportCompletionHandler` will be always `nil` and don't know what bad things will happen even I can normally see the report in Instabug's dashboard.

### Expected Behavior

Present the bug report window as expectation

### Actual Behavior

App getting freeze, any tap on the screen without response.

### SDK Version

instabug-reactnative 9.0.7

### React Native, iOS and Android Versions

React Native 0.61.5
iOS 13.2

### Device Model

iPhone XS (Real device)
iPhone 11 (Simulator)

**Comment by alyezz** [comment]
@jayasme Thanks for the detailed report, we are looking into it

**Comment by gilbertl** [comment]
Hi all,

This seems like a pretty significant issue but the fix has been sitting around for the past 2 months. Should we been patching it ourselves? Is there a different fix?

**Comment by AliAbdelfattah** [comment]
Hi @gilbertl, we do have a fix ready for the issue. However, we've found a blocker while testing that was causing an issue in the SDK. We know the fix probably took longer than expected, sorry about that. We wanted to make sure it doesn't affect other parts of the SDK.

That being said, I'll do my best in moving the fix into production within next week, sounds good? :)
