### ISSUE TITLE
Disable the automatic upload of the sourcemap in iOS

### ISSUE THREAD

**Issue by jacquesdev** [Instabug/Instabug-React-Native#477]
Your documentation mentions how to disable this for Android, but I'd like to know how to disable this for iOS, see this link: https://github.com/Instabug/Instabug-React-Native#uploading-source-map-files-for-crash-reports.

**Comment by AliAbdelfattah** [comment]
@jacquesdev you'll need to remove "Upload sourcemap" script in the build phases through Xcode.
