### ISSUE TITLE
Turn of instabug features

### ISSUE THREAD

**Issue by jacquesdev** [Instabug/Instabug-React-Native#478]
I'd like to completely turn off the following features of Instabug in Android and iOS

- Bug Reporting
- Crash Reporting

Is this currently possible?

I love this part of Instabug
- In-App Replies
- In-App Surveys

But the Bug Reporting and Crash Reporting is really not worth the effort in our app since we use alternative options right now, and this, unfortunately, creates unintentional bloat in our app.

**Comment by AliAbdelfattah** [comment]
Hi @jacquesdev, here's the script to disable the Bug Reporting and Crash Reporting:
```BugReporting.setEnabled(false);
CrashReporting.setEnabled(false);```

**Comment by jacquesdev** [comment]
Thank you!

**Comment by jacquesdev** [comment]
@AliAbdelfattah - quick question on this, if I disable these two, I see it's still uploading the sourcemap - when I do the iOS archive - is that expected? I would not have expected that to happen once these two functions are disabled.

**Comment by AliAbdelfattah** [comment]
@jacquesdev linking between these two is somewhat limited. Given that a feature flag is highly reliant on runtime and the sourcemap uploading is more like a configuration step which RN linking process is responsible for. We'd appreciate it if you have any ideas on how we could link them together.

You can manually remove the script that uploads the sourcemap though. You'll find it in the Build Phases through Xcode.
