### ISSUE TITLE
NullPointerException Attempt to invoke virtual method 'java.lang.String android.view.View.getTransitionName()

### ISSUE THREAD

**Issue by SudoPlz** [Instabug/Instabug-React-Native#494]
### Stacktrace
```
java.lang.NullPointerException Attempt to invoke virtual method 'java.lang.String android.view.View.getTransitionName()' on a null object reference 
    ViewCompat.java:2314 androidx.core.view.ViewCompat.getTransitionName
    InstabugDialogActivity.java:5 com.instabug.library.invocation.invocationdialog.InstabugDialogActivity.setContent
    InstabugDialogActivity.java:11 com.instabug.library.invocation.invocationdialog.InstabugDialogActivity.onNewIntent
    Activity.java:7339 android.app.Activity.performNewIntent
    Instrumentation.java:1366 android.app.Instrumentation.callActivityOnNewIntent
    Instrumentation.java:1378 android.app.Instrumentation.callActivityOnNewIntent
    ActivityThread.java:3295 android.app.ActivityThread.deliverNewIntents
    ActivityThread.java:3311 android.app.ActivityThread.performNewIntents
    ActivityThread.java:3328 android.app.ActivityThread.handleNewIntent
    NewIntentItem.java:49 android.app.servertransaction.NewIntentItem.execute
    TransactionExecutor.java:108 android.app.servertransaction.TransactionExecutor.executeCallbacks
    TransactionExecutor.java:68 android.app.servertransaction.TransactionExecutor.execute
    ActivityThread.java:1926 android.app.ActivityThread$H.handleMessage
    Handler.java:106 android.os.Handler.dispatchMessage
    Looper.java:214 android.os.Looper.loop
    ActivityThread.java:6986 android.app.ActivityThread.main
    Method.java:-2 java.lang.reflect.Method.invoke
    RuntimeInit.java:494 com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run
    ZygoteInit.java:1445 com.android.internal.os.ZygoteInit.main
```

### Reproduction steps

We received the following breadcrumbs from a user in production that indicates the user paused and resumed the instabug dialog activity a couple of times before this crash happened.

Many users have reported they can't get Instabug to show up, so maybe this is related to that? Dunno...

0ms before |   | NAVIGATIONInstabugDialogActivityActivityLifecycleonPause()
-- | -- | --
0ms before |   | NAVIGATION - InstabugDialogActivity - ActivityLifecycle - onResume()
0ms before |   | NAVIGATION - InstabugDialogActivity - ActivityLifecycle - onPause()
1.00s before |   | NAVIGATION - InstabugDialogActivity - ActivityLifecycle - onResume()
1.00s before |   | NAVIGATION - InstabugDialogActivity - ActivityLifecycle - onPause()
1.00s before |   | NAVIGATION - InstabugDialogActivity - ActivityLifecycle - onResume()
1.00s before |   | NAVIGATION - InstabugDialogActivity - ActivityLifecycle - onPause()
3.00s before |   | NAVIGATION - InstabugDialogActivity - ActivityLifecycle - onResume()
3.00s before |   | NAVIGATION - InstabugDialogActivity - ActivityLifecycle - onPause()

### Expected Behavior
No crashes

### Actual Behavior
Crash

### SDK Version
instabug-reactnative: 9.0.1

### React Native, iOS and Android Versions
Android only

### Device Model
Samsung devices (S8, S9, S10)

Before telling us to "update to the latest version" solution, please make sure that this has been fixed on that latest version if possible.
I'd be grateful.
Thanks!

**Comment by alyezz** [comment]
@SudoPlz Thanks for reporting this. The issue has been fixed and will be included in our next release. In the meantime here is a custom build with the fix that you can use ```npm install --save https://github.com/Instabug/Instabug-React-Native#customBuild/9.1.6.1```

Feel free to re-open this if you are still facing this issue

**Comment by SudoPlz** [comment]
Awesome, thanks @alyezz I appreciate it.
