### ISSUE TITLE
Again instabug server got failed?

### ISSUE THREAD

**Issue by naveenst2s** [Instabug/Instabug-React-Native#497]
* What went wrong:
Execution failed for task ':app:preAppReleaseBuild'.
> Could not resolve all files for configuration ':app:appReleaseCompileClasspath'.
   > Could not resolve com.instabug.library:instabug:8.7.0.0.
     Required by:
         project :app > project :instabug-reactnative
      > Could not resolve com.instabug.library:instabug:8.7.0.0.
         > Could not get resource 'https://sdks.instabug.com/nexus/repository/instabug-cp/com/instabug/library/instabug/8.7.0.0/instabug-8.7.0.0.pom'.
            > Could not GET 'https://sdks.instabug.com/nexus/repository/instabug-cp/com/instabug/library/instabug/8.7.0.0/instabug-8.7.0.0.pom'. Received status code 401 from server: Unauthorized

**Comment by AliAbdelfattah** [comment]
It was down for a few mins, sorry for the inconvenience. It should be working now.
