### ISSUE TITLE
Mising "onNavigationStateChange" function inside index.d.ts definitions for 9.1.6 Version

### ISSUE THREAD

**Issue by santiagogarzon** [Instabug/Instabug-React-Native#498]
Instabug-React-Native 9.1.6 Version

### Expected Behavior
Every new feature should be added inside index.d.ts for typescript projects
### Actual Behavior
onNavigationStateChange is missing in index.d.ts

**Comment by axeljeremy7** [comment]
any updates?

**Comment by santiagogarzon** [comment]
@axeljeremy7 I created a PR https://github.com/Instabug/Instabug-React-Native/pull/499. Waiting to be approved in order to merge it.

**Comment by alyezz** [comment]
@santiagogarzon Thanks for the PR! It has been merged and included in the latest release 9.1.7
