### ISSUE TITLE
RN + dSYM results in: Instabug: err: script not found. Make sure that you're including Instabug.bundle in your project directory

### ISSUE THREAD

**Issue by melvinmt** [Instabug/Instabug-React-Native#506]
### Steps to Reproduce the Problem

1. Follow instructions on installing instabug for react native:

```
yarn add instabug-reactnative
gem install xcodeproj
react-native add-instabug
```

2. Follow instructions to install [iOS dSYM symbolication](https://docs.instabug.com/docs/ios-symbolication#automatically)

### Expected Behavior

Project builds and uploads dSYM with no errors

### Actual Behavior

Project build aborts with the following error:

```
Instabug: err: script not found. Make sure that you're including Instabug.bundle in your project directory
```

### Instabug integration code
```
#- -- SCRIPT BEGIN - --
# SKIP_SIMULATOR_BUILDS=1
  SCRIPT_SRC=$(find "$PROJECT_DIR" -name 'Instabug_dsym_upload.sh' | head -1)
  if [ ! "${SCRIPT_SRC}" ]; then
    echo "Instabug: err: script not found. Make sure that you're including InstabugResources.bundle in your project directory"
    exit 1
  fi
  APP_TOKEN="YOUR-APP-TOKEN-HERE"
  source "${SCRIPT_SRC}"
#- -- SCRIPT END - --
```

### SDK Version

9.1.7

### React Native, iOS and Android Versions

React Native: `0.63.1`
iOS: 10.0+
Xcode: `11.7`

**Comment by AliAbdelfattah** [comment]
Hi @melvinmt, could you try executing the command `pod install` inside your ios directory and try building again?
