### ISSUE TITLE
Crash Issue

### ISSUE THREAD

**Issue by Guna-T2S** [Instabug/Instabug-React-Native#513]
It got crashed in initial screen of the app.

Device:  samsung SM-G950F

instabug version: 9.1.7

react-native version : "0.61.5"

Error Message: 
io.reactivex.exceptions.UndeliverableException: java.net.UnknownHostException: Unable to resolve host "api.instabug.com": No address associated with hostname (NetworkManager.java:8)

**Comment by AliAbdelfattah** [comment]
Hi @Guna-T2S, thanks for reporting this. We're looking into it.

**Comment by AliAbdelfattah** [comment]
This should be fixed in v9.1.8. Please give it a try and feel free to reopen the issue if it persists.
