### ISSUE TITLE
In coversation module screenrecorded video is not displaying 

### ISSUE THREAD

**Issue by 08Thug** [Instabug/Instabug-React-Native#518]
### Steps to Reproduce the Problem
Select Report a bug option choose screen recorder option and record the video and post it along with report on the conversation module posted video is not displaying  instead it show as image or it doesn't show anything all
### Expected Behavior
The expected behaviour is when we attach screen recorded video with bug reporting on the conversation module it should display the video on the chat module
### Actual Behavior
The attached video is not showing in the chat module instead it show as image or it doesn't show anything
### Instabug integration code
public void onCreate() {
    super.onCreate();
     new RNInstabugReactnativePackage
         .Builder("APP_TOKEN", MainApplication.this)
         .setInvocationEvent("shake")
         .setPrimaryColor("#1D82DC")
         .setFloatingEdge("left")
         .setFloatingButtonOffsetFromTop(250)
         .build();
    initializeFlipper(this, getReactNativeHost().getReactInstanceManager());
    Instabug.setWelcomeMessageState(WelcomeMessage.State.DISABLED);

### SDK Version
 "instabug-reactnative": "^9.1.7",

### React Native, iOS and Android Versions
"react": "16.13.1"
tried on multiple android version 5.0,6.0,9.0
### Device Model
I tried with multiple device but the issue occurs most of the time

**Comment by alyezz** [comment]
@08Thug apologies for the late reply, would you mind showing us a screen recording of the issue?

**Comment by divyasri93** [comment]
@alyezz I'm facing the same issue .. I'd attached a recorded video and it doesn't display in the conversation window. But able to view in dashboard. Only in mobile app its not showing. I'm using the latest version of instabug.
