### ISSUE TITLE
Popup disappears automatically if it remains idle for a short period of time

### ISSUE THREAD

**Issue by 08Thug** [Instabug/Instabug-React-Native#520]
### Steps to Reproduce the Problem
Installed the plugin and after shaking the popup appears but it disappear when it remains idle after short period of time (10sec) 
### Expected Behavior
Is there is way to override it? it should not disappear when the device is idle for a short period of time
### Actual Behavior
the Instabug popup appears but it disappear when it remains  idle after short period of time (10sec) 
### Instabug integration code
public void onCreate() {
super.onCreate();
new RNInstabugReactnativePackage
.Builder("APP_TOKEN", MainApplication.this)
.setInvocationEvent("shake")
.setPrimaryColor("#1D82DC")
.setFloatingEdge("left")
.setFloatingButtonOffsetFromTop(250)
.build();
initializeFlipper(this, getReactNativeHost().getReactInstanceManager());
Instabug.setWelcomeMessageState(WelcomeMessage.State.DISABLED);

### SDK Version
"instabug-reactnative": "^9.1.7",

### React Native, iOS and Android Versions
"react": "16.13.1"
tried on multiple android version 5.0,6.0,9.0
ios 11,12

**Comment by alyezz** [comment]
@08Thug This is by design and currently there is no way to override the timeout. Do you mind sharing with us the use case for this?
