### ISSUE TITLE
Delay in getting report in conversation page

### ISSUE THREAD

**Issue by 08Thug** [Instabug/Instabug-React-Native#521]
### Steps to Reproduce the Problem
- send a report
- After sent, open conversations
- reported bug is not showing 
- finally shows after some delay"
### Expected Behavior
Reported bugs should show in converstion once reported
### Actual Behavior
There is a delay in showing reported bugs in conversation
### Instabug integration code
public void onCreate() {
super.onCreate();
new RNInstabugReactnativePackage
.Builder("APP_TOKEN", MainApplication.this)
.setInvocationEvent("shake")
.setPrimaryColor("#1D82DC")
.setFloatingEdge("left")
.setFloatingButtonOffsetFromTop(250)
.build();
initializeFlipper(this, getReactNativeHost().getReactInstanceManager());
Instabug.setWelcomeMessageState(WelcomeMessage.State.DISABLED);

### SDK Version
"instabug-reactnative": "^9.1.7",

### React Native, iOS and Android Versions
"react": "16.13.1"
tried on multiple android version 5.0,6.0,9.0
ios 12,13

**Comment by AliAbdelfattah** [comment]
@08Thug how long is the delay?

**Comment by 08Thug** [comment]
we don't know the exact time some times report is shown after some minutes or until next report has been made

**Comment by AliAbdelfattah** [comment]
@08Thug are you still encountering this delay? If so:
- Just to confirm, you're having this delay on both Android and iOS, correct?
- If possible, could you be more specific about how long it may take for a report to appear i.e. the maximum delay duration?

**Comment by 08Thug** [comment]
Yeah sure let me consult with my QA team!
