### ISSUE TITLE
Conversations : Another User's conversations are also listed along with Currently logged in user

### ISSUE THREAD

**Issue by 08Thug** [Instabug/Instabug-React-Native#522]
### Steps to Reproduce the Problem
-when I Logged in with a account and reports a bug from that account
-logged out from that account again logs in with a new account
-open instabug navigate to convo page it shows the reports attached by the pervious logged users.
### Expected Behavior
It should not show report sent by previous user should only show the currently logged user reports
### Actual Behavior
it show the Report of both previously logged user and current user
### Instabug integration code
public void onCreate() {
super.onCreate();
new RNInstabugReactnativePackage
.Builder("APP_TOKEN", MainApplication.this)
.setInvocationEvent("shake")
.setPrimaryColor("#1D82DC")
.setFloatingEdge("left")
.setFloatingButtonOffsetFromTop(250)
.build();
initializeFlipper(this, getReactNativeHost().getReactInstanceManager());
Instabug.setWelcomeMessageState(WelcomeMessage.State.DISABLED);

### SDK Version

"instabug-reactnative": "^9.1.7",

### React Native, iOS and Android Versions
"react": "16.13.1"
tried on multiple android version 5.0,6.0,9.0
ios 12,13

**Comment by AliAbdelfattah** [comment]
Hi @08Thug, are you calling `identifyUser` and `logOut` APIs anywhere in your project? If so, please specify the use cases.
