### ISSUE TITLE
Missing console.log statements in report because of react-native-reanimated

### ISSUE THREAD

**Issue by gilbertl** [Instabug/Instabug-React-Native#540]
The app my team and I work on uses react-native-reanimated for rendering animations. After installing their latest major version, we notice that Instabug is no longer capturing / sending console.log / error statements 

We believe the culprit is some kind of unintended consequence of either package trying to override the behavior of console.log

e.g https://github.com/software-mansion/react-native-reanimated/blob/b80d480df20632d15b07cc46f858d40e5f8464eb/src/reanimated2/core.js#L246

We're looking for insights into how all these works underneath the hood and how we can best move forward with the 2 packages.

### Steps to Reproduce the Problem
1. Setup Instabug React Native
2. Install react native reanimated v2 https://github.com/software-mansion/react-native-reanimated
3. File a bug report using Instabug

### Expected Behavior
All console.log statements captured as part of Instabug report

### Actual Behavior
No console.log statements are captured.

**Comment by AliAbdelfattah** [comment]
@gilbertl thank you for reporting this. We're looking into it.

**Comment by ahmed1hisham** [comment]
Hi @gilbertl ,
We couldn't reproduce the issue using the react-native-reanimated v2 [release](https://github.com/software-mansion/react-native-reanimated/releases/tag/2.0.0)
Are you still able to reproduce it given this latest release?

**Comment by gilbertl** [comment]
> Hi @gilbertl ,
> We couldn't reproduce the issue using the react-native-reanimated v2 [release](https://github.com/software-mansion/react-native-reanimated/releases/tag/2.0.0)
> Are you still able to reproduce it given this latest release?

This seems to be fixed in react-native-reanimated
