### ISSUE TITLE
User steps features

### ISSUE THREAD

**Issue by imranMnts** [Instabug/Instabug-React-Native#543]
Hello, 

I have a request about your nice lib.
Do you plan to add `User steps` features? If yes can we have any ETA please? 

Thanks

**Comment by bsameh-at-instabug** [comment]
Hello @imranMnts 

It's in our backlog, however, there's no exact ETA at the moment. Will make sure to bump this up our queue so that it's prioritized and will let you know as soon as we have an ETA 👍

**Comment by imranMnts** [comment]
Hello @bsameh-at-instabug 

Do we have any update related to this feature, please?

**Comment by odemolliens** [comment]
Any ETA?

**Comment by odemolliens** [comment]
Any ETA?

**Comment by imranMnts** [comment]
Hello @AliAbdelfattah @bsameh-at-instabug?

Can we know the state of this feature? Do we have any progress?

**Comment by AliAbdelfattah** [comment]
@imranMnts @odemolliens it's still in our backlog but several higher priority items have preceded it. We don't have an ETA at the moment but we are working on providing one.

**Comment by odemolliens** [comment]
Any update?
