### ISSUE TITLE
Instabug: err: INSTABUG_APP_TOKEN not found

### ISSUE THREAD

**Issue by mukesh-simform** [Instabug/Instabug-React-Native#547]
### Steps to Reproduce the Problem
1. Must have [react-native-config](https://github.com/luggit/react-native-config) setup
2. Create .env file with INSTABUG_APP_TOKEN=""
3. Add an invocation event
```
    import Secrets from 'react-native-config';
    ......
    constructor(props) {
       super(props);
       Instabug.startWithToken(Secrets.INSTABUG_APP_TOKEN, [
         Instabug.invocationEvent.screenshot
       ]);
    }
```
4. Generate signed APK ./gradlew assembleRelease

### Expected Behavior
- It should auto-upload source map file 

### Actual Behavior
- Getting Instabug: err: INSTABUG_APP_TOKEN not found error while generating signed APK [./gradlew assembleRelease]
![Screenshot 2021-01-30 at 5 37 12 PM](https://user-images.githubusercontent.com/56827526/106355981-d6939980-6321-11eb-9e3c-17c29dca2281.png)

### Instabug integration code
```
   Instabug.startWithToken(Secrets.INSTABUG_APP_TOKEN, [
      Instabug.invocationEvent.screenshot
   ]);
```

### SDK Version
9.1.10

### React Native, iOS and Android Versions
RN Version: 0.62.2

**Comment by mukesh-simform** [comment]
It's working fine if use the INSTABUG_APP_TOKEN directly instead from the .env to constant variable
```
 Instabug.startWithToken("INSTABUG_APP_TOKEN", [
      Instabug.invocationEvent.screenshot
 ]);
```

**Comment by AliAbdelfattah** [comment]
Hi @mukesh-simform, to automatically upload the sourcemap files, you have to directly add the token (hardcoded) or you can store the token in an environment variable. I understand the first approach isn't very convenient, but it's how our regex is currently implemented. However, I've added this to our backlog.

For more info, please check [the README](https://github.com/Instabug/Instabug-React-Native#uploading-source-map-files-for-crash-reports). Feel free to reopen if you encounter any related issues.

**Comment by charleyoliveira** [comment]
@mukesh-simform @AliAbdelfattah  there is other way to solve this
edit Podfile in ios folder 
run pod install
```sh
post_integrate do |integrate|
  require 'xcodeproj'
  project = Xcodeproj::Project.open "./YOURPROJECT.xcodeproj"
  for target in project.targets
    if target.name == "YOURPROJECT"
        phase = target.shell_script_build_phases().find {|item| item.name == "[CP-User] [instabug-reactnative] Upload Sourcemap"}
        phase.shell_script = "export INSTABUG_APP_TOKEN="+ENV["INSTABUG_APP_TOKEN"]+"\nbash \"../node_modules/instabug-reactnative/ios/upload_sourcemap.sh\"\n"
    end
  end
  project.save()
end
```
