### ISSUE TITLE
Locale is not supporting for IOS

### ISSUE THREAD

**Issue by 08Thug** [Instabug/Instabug-React-Native#551]
In document it is told that instabug will fetch the device locale and will reflect the same! this feature works well for android,but it is not working in IOS it sticks to the default language i.e english i even tried the override method 
Instabug.setLocale(Instabug.locale.french);
yet no change

### Steps to Reproduce the Problem
change the device language 
shake for instabug popup 
locale is not updated

should i have to change any for IOS?

### Expected Behavior

should reflect the device language or the override method should work on IOS

### Actual Behavior

Instabug is not reflecting the device language or the override method is not working in IOS

### Instabug integration code
 Instabug.startWithToken(STAGE_TOKEN, [Instabug.invocationEvent.shake]);
    if(DeviceLang!=="en")
    {
      Instabug.setLocale(Instabug.locale.spanish);
    }
    else
    {
      Instabug.setLocale(Instabug.locale.english);     
    }

### SDK Version
Latest version
i.e 9.1.10

### Device Model
On all IOS platform

**Comment by ahmed1hisham** [comment]
Thank you for opening this issue. We are currently looking into it.

**Comment by ahmed1hisham** [comment]
Hi there,
We traced the issue, and here’s what you should do to ensure that the Instabug SDK follows the device language:
 (You can use the attached screenshot to help you) 
- Open your project in Xcode.
- Navigate to the LaunchScreen of your App.
- Go to file inspector on the right side.
- Under the Localization section, check all the languages you want the SDK to support. 

Hope this helped! Please let us know the updates.

<img width="1426" alt="Screen Shot 2021-03-02 at 3 42 44 PM" src="https://user-images.githubusercontent.com/36399893/109664465-d4696880-7b75-11eb-88e8-be38a9fdffde.png">
