### ISSUE TITLE
Android assembleRelease errors: Could not get resource

### ISSUE THREAD

**Issue by jsonreeder** [Instabug/Instabug-React-Native#557]
### Expected Behavior

When I run `./gradlew assembleRelease` in CircleCI, the build completes with `BUILD SUCCESSFUL`.

This was the behavior we had until our last successful build at 12:04pm GMT-8 today 3/9.

### Actual Behavior

When I run `./gradlew assembleRelease` in CircleCI, the job fails with the following error

```
FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':app:lintVitalRelease'.
> Could not resolve all artifacts for configuration ':app:debugCompileClasspath'.
   > Could not download instabug-core-10.1.1.0.aar (com.instabug.library:instabug-core:10.1.1.0)
      > Could not get resource 'https://sdks.instabug.com/nexus/repository/instabug-cp/com/instabug/library/instabug-core/10.1.1.0/instabug-core-10.1.1.0.aar'.
         > Premature end of Content-Length delimited message body (expected: 2,147,032; received: 444,270)
```

This was the case at 12:39pm GMT-8. We didn't make any code changes during that time. When I rerun previous builds that passed, they now fail on that error. So I assume this is an error with Instabug's repository not our codebase.

### Instabug integration code

Selection from `android/build.gradle`

```
allprojects {
    repositories {
        mavenLocal()
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url("$rootDir/../node_modules/react-native/android")
        }
        maven {
            // Android JSC is installed from npm
            url("$rootDir/../node_modules/jsc-android/dist")
        }
        maven {
            // Instabug
	        url "https://sdks.instabug.com/nexus/repository/instabug-cp"
	    }

        google()
        jcenter()
        maven { url 'https://www.jitpack.io' }

    }
}
```

### SDK Version

instabug-reactnative@^10.0.0:
  version "10.0.0"
  resolved "https://registry.yarnpkg.com/instabug-reactnative/-/instabug-reactnative-10.0.0.tgz#f5c44194f5b34e89216df9ebafc438a82cea4166"

**Comment by Jonovono** [comment]
We are getting this as well, @jsonreeder I have reached out to support and they are looking into it so hopefully will be resolved soon :)

**Comment by harshal-moneylion** [comment]
We are also getting same, Adding logs below for reference. 

```
* What went wrong:
Could not determine the dependencies of task ':app:lintVitalBetaRelease'.
> Could not resolve all artifacts for configuration ':app:betaDebugCompileClasspath'.
   > Could not download instabug-core-9.1.8.1.aar (com.instabug.library:instabug-core:9.1.8.1)
      > Could not get resource 'https://sdks.instabug.com/nexus/repository/instabug-cp/com/instabug/library/instabug-core/9.1.8.1/instabug-core-9.1.8.1.aar'.
         > Premature end of Content-Length delimited message body (expected: 2,079,744; received: 694,150)
```

**Comment by snamstorm** [comment]
> We are also getting same, Adding logs below for reference.
> 
> ```
> * What went wrong:
> Could not determine the dependencies of task ':app:lintVitalBetaRelease'.
> > Could not resolve all artifacts for configuration ':app:betaDebugCompileClasspath'.
>    > Could not download instabug-core-9.1.8.1.aar (com.instabug.library:instabug-core:9.1.8.1)
>       > Could not get resource 'https://sdks.instabug.com/nexus/repository/instabug-cp/com/instabug/library/instabug-core/9.1.8.1/instabug-core-9.1.8.1.aar'.
>          > Premature end of Content-Length delimited message body (expected: 2,079,744; received: 694,150)
> ```

We are getting the exact same logs as well

**Comment by lha-ryq** [comment]
The same here:
```
* What went wrong:
Could not determine the dependencies of task ':app:lintVitalAlphaRelease'.
> Could not resolve all artifacts for configuration ':app:alphaDebugCompileClasspath'.
   > Could not download instabug-core-9.1.8.1.aar (com.instabug.library:instabug-core:9.1.8.1)
      > Could not get resource 'https://sdks.instabug.com/nexus/repository/instabug-cp/com/instabug/library/instabug-core/9.1.8.1/instabug-core-9.1.8.1.aar'.
         > Premature end of Content-Length delimited message body (expected: 2,079,744; received: 673,494)
```

**Comment by AliAbdelfattah** [comment]
Just letting you know, we're still looking into it. Will keep you updated.

**Comment by AliAbdelfattah** [comment]
It should be fixed now.

**Comment by jsonreeder** [comment]
I confirm that I'm no longer seeing the error and builds are succeeding. Alf shokr ya Ali!
