### ISSUE TITLE
IOS crash when Network logging

### ISSUE THREAD

**Issue by kadarsh11** [Instabug/Instabug-React-Native#559]
#### In case of number value in request header, the app gets crashed on IOS device with error saying 
*Could not cast value of type '__NSCFNumber' to 'NSString'.*

### Instabug integration code
`Instabug.startWithToken('', [Instabug.invocationEvent.shake]);
        Instabug.setWelcomeMessageMode(Instabug.welcomeMessageMode.disabled);`

### SDK Version
v 10.0.0

### Device Model
All IOS device

<img width="761" alt="Screenshot 2021-03-25 at 11 56 33 AM" src="https://user-images.githubusercontent.com/31586309/112428604-69204a00-8d61-11eb-923d-ff3da32859e3.png">

**Comment by AliAbdelfattah** [comment]
Thank you for reporting this. We're looking into it.

**Comment by ahmed1hisham** [comment]
Hi @kadarsh11 ,

We included a fix for this issue in a snapshot. Please use this command to install it:
`npm install --save https://github.com/Instabug/Instabug-React-Native#snapshot/10.0.0-MOB-5115`

Please update us and feel free to let us know if the issue persists.

**Comment by MaxInMoon** [comment]
I face a similar issue with Instabug 0.14 or 0.15 and react-native 0.80.1

```
Could not cast value of type '__NSDictionary0' (0x1f340ebf0) to 'NSString' (0x1f34077f8).
```

It happens after a request of my app has a timeout.
If I comment the Instabug.init part, the app won't crash.
```
    // Instabug.init({
    //  token: "MY__TOKEN",
    // });
```
Anyone did solve this ?
