### ISSUE TITLE
[Android] CRITICAL: Instabug Storage Approach May prevent App Approval/Release

### ISSUE THREAD

**Issue by tomwanzek** [Instabug/Instabug-React-Native#582]
### Steps to Reproduce the Problem

We recently received the following message in the Google Play Store inbox for one of our Apps and require critical guidance on how to proceed:

![Screen Shot 2021-05-03 at 2 06 41 PM](https://user-images.githubusercontent.com/16323903/116914646-fab09080-ac18-11eb-88b2-6f0d72eb775c.png)

IMPORTANT: Look in particular at the last statement about App Removal from Play Store and inability to publish updates.

Below the above message is a "Learn more" which refers here: https://support.google.com/googleplay/android-developer/answer/10467955

After investigation, we have determined that the _exclusive_ reason why Google is pointing out this warning in our code base is the `Instabug React Native SDK`.

Specifically, as per the `build/app/outputs/logs` for our Android build, it is only `Instabug` which requests external storage related permissions (`uses-permission#android.permission.WRITE_EXTERNAL_STORAGE` and `uses-permission#android.permission.READ_EXTERNAL_STORAGE`

>uses-permission#android.permission.READ_EXTERNAL_STORAGE
ADDED from [com.instabug.library:instabug-bug:10.1.1.0] /Users/XXXXXX/.gradle/caches/transforms-3/131459e0f11fd2ecdce66426e0fb3373/transformed/jetified-instabug-bug-10.1.1.0/AndroidManifest.xml:11:5-80
MERGED from [com.instabug.library:instabug-core:10.1.1.0] /Users/XXXXXX/.gradle/caches/transforms-3/76963bc19d4e6f88412b8761a0bee66e/transformed/jetified-instabug-core-10.1.1.0/AndroidManifest.xml:12:5-80
MERGED from [com.instabug.library:instabug-core:10.1.1.0] /Users/XXXXXX/.gradle/caches/transforms-3/76963bc19d4e6f88412b8761a0bee66e/transformed/jetified-instabug-core-10.1.1.0/AndroidManifest.xml:12:5-80

>uses-permission#android.permission.WRITE_EXTERNAL_STORAGE
ADDED from [com.instabug.library:instabug-core:10.1.1.0] /Users/XXXXXXX/.gradle/caches/transforms-3/76963bc19d4e6f88412b8761a0bee66e/transformed/jetified-instabug-core-10.1.1.0/AndroidManifest.xml:11:5-81
	android:name
		ADDED from [com.instabug.library:instabug-core:10.1.1.0] /Users/XXXXXX/.gradle/caches/transforms-3/76963bc19d4e6f88412b8761a0bee66e/transformed/jetified-instabug-core-10.1.1.0/AndroidManifest.xml:11:22-78

and adds the admonished: `android:requestLegacyExternalStorage` flag:

>android:requestLegacyExternalStorage
		ADDED from [com.instabug.library:instabug-core:10.1.1.0] /Users/XXXXXXXX/.gradle/caches/transforms-3/76963bc19d4e6f88412b8761a0bee66e/transformed/jetified-instabug-core-10.1.1.0/AndroidManifest.xml:21:9-52

### Expected Behavior

We are currently still building with target Android 10, but will also in the near future upgrade to using React Native 0.64 and intent to build with Android 11 target.

We expect that using the Instabug SDK uses the minimally necessary permission (here in particular on Android) and uses the Google recommended/demanded approach to using the appropriate storage. It should not jeopardize our ability to have the next app releases review, approved and released.

### Actual Behavior

It appears the current SDK is leading to issues as outlined above.

### Instabug integration code

Integration as per documentation, has been in use and in production without issues for several months now.

### SDK Version

10.0.0

### React Native, iOS and Android Versions

> System:
    OS: macOS 11.3
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
    Memory: 27.56 GB / 64.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.10.0 - /var/folders/kb/0gc38wkn40bb3513d34xdym40000gp/T/yarn--1620067262236-0.08275756404312506/node
    Yarn: 1.22.5 - /var/folders/kb/0gc38wkn40bb3513d34xdym40000gp/T/yarn--1620067262236-0.08275756404312506/yarn
    npm: 6.14.8 - ~/.nvm/versions/node/v14.10.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
    Android SDK: Not Found
  IDEs:
    Android Studio: 4.1 AI-201.8743.12.41.7042882
    Xcode: 12.5/12E262 - /usr/bin/xcodebuild
  Languages:
    Java: javac 15 - /usr/bin/javac
    Python: 3.8.3 - /opt/anaconda3/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: 0.63.4 => 0.63.4 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

Currently as per Android `build.gradle`:

```
buildToolsVersion = "29.0.2"
minSdkVersion = 16
compileSdkVersion = 29
targetSdkVersion = 29
```

As mentioned, we intend to move towards targetSdkVersion 30 in short order.

### Device Model

All Android devices.

**Comment by tomwanzek** [comment]
As I understand it, there is a new release under preparation. However, at this point it is **time critical for us to have clear guidance** as to how we should proceed.

Specifically could you please provide a point by point response to the below,

(1) Will the new release move towards using Scoped Storage? As seems to be the requirement laid out by Google?

(2) What should we do at present, given Google's May 5th deadline in the Google Play Store message,

(2a) given that we are currently building and have so far released with Android 10 (API level 29) target?

(2b) once we upgrade to target Android 11 (API level 30)?


Please note, that we are particularly concerned about getting a timely, vetted response how to stay compliant when we submit builds for review/release to Google Play, given the severity of the sanctions seemingly threatened by Google:

>Apps requesting access to the All files access permission without a permitted use will be removed from Google Play, and you won't be able to publish updates.

**Comment by tomwanzek** [comment]
It seems, the best current information is available under this issue in the Android SDK for Instabug: https://github.com/Instabug/Instabug-Android/issues/371

**Comment by AliAbdelfattah** [comment]
@tomauty just want to let you know a fix has already been released in our native Android SDK and we're working on including the fix to our upcoming RN release. Let me get back to you with your questions.

**Comment by tomwanzek** [comment]
Thanks @AliAbdelfattah 🙇  I did some more digging, and am wondering, if the mere workaround with adding:

```
android:requestLegacyExternalStorage="false"
tools:replace="requestLegacyExternalStorage"
```

is sufficient.

For one, Google's wording is a little ambiguous:

> We've detected that your app contains the requestLegacyExternalStorage flag in the manifest file

And with the workaround:
```
android:requestLegacyExternalStorage="false"
```
will be in the final manifest file. So technically, there still _is_ an entry in the manifest, albeit the flag is set to `false`.

More Importantly, even with this work-around, the following two permissions are still requested as a result of Instabug SDK 10.0.0:

```
<uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
```

Which leads me to wonder about: https://developer.android.com/about/versions/11/privacy/storage#permissions
specifically:

![Screen Shot 2021-05-04 at 4 17 56 PM](https://user-images.githubusercontent.com/16323903/117064583-5e5bbc00-acf4-11eb-9d0b-b32461230ff7.png)


So, in short, it is not really clear to me (as a non-Android):

a) What will happen for **Instabug SDK 10.0.0 + workaround** w.r.t. permissions with **Deployment Target = Android 10 and Device running Android 10**
b) What will happen for **Instabug SDK 10.0.0 + workaround** w.r.t. permissions with **Deployment Target = Android 10 and Device running Android 11**
c) * What will happen for **Instabug SDK next** w.r.t. permissions with **Deployment Target = Android 11 and Device running Android 10**
d) * What will happen for **Instabug SDK next** w.r.t. permissions with **Deployment Target = Android 11 and Device running Android 11**

What storage-related permissions are needed in each of these scenarios, what for, which ones will the user be prompted for automatically?

Is there or will there be any use of requesting "All files access" permissions by Instabug.

What happens with Instabug an its features, if the user declines the permission?

Again, lot's of questions, but I think this area is particularly unclear right now. Thanks in advance 😄

**Comment by tomauty** [comment]
> @tomauty just want to let you know a fix has already been released in our native Android SDK and we're working on including the fix to our upcoming RN release. Let me get back to you with your questions.

Did you mean to tag @tomwanzek ? Hopefully I didn't contribute anything problematic years back :)

**Comment by tomwanzek** [comment]
Any update? It's May 5th today 😄

**Comment by haozhutw** [comment]
Looks like the storage issue is fixed in [https://github.com/Instabug/Instabug-Android/issues/371](https://github.com/Instabug/Instabug-Android/issues/371). I think a new version of instabug-reactnative is needed based on Android code changes. We are still waiting and don't know when this would be published.
