### ISSUE TITLE
setNetworkDataObfuscationHandler not working as intended

### ISSUE THREAD

**Issue by pouriabagheri** [Instabug/Instabug-React-Native#595]
### Steps to Reproduce the Problem
enable network log
### Expected Behavior
to obfuscate the content if they are present in the request.
### Actual Behavior
adds the key value to every single request and replaces any other value that should have not been obfuscated.
![image](https://user-images.githubusercontent.com/5735478/121128114-71b2f780-c85d-11eb-81f4-c39bb583482a.png)
### Instabug integration code
```
NetworkLogger.setNetworkDataObfuscationHandler(async (networkData) => {
  networkData.requestHeaders = {'Authorization': '***'};
  networkData.requestBody = {'password': '***'};
  networkData.responseBody = {'token':'***' };
  return networkData;
});
```
### SDK Version

^10.4
### Device Model
emulator

**Comment by AliAbdelfattah** [comment]
Hi @pouriabagheri sorry for not getting to you sooner, the API is currently implemented in this way by design. As a workaround, you can check if the key exists before setting values.
