### ISSUE TITLE
Android photo permissions issue after upgrading to 10.4

### ISSUE THREAD

**Issue by jacquesdev** [Instabug/Instabug-React-Native#599]
### Steps to Reproduce the Problem
About two months ago I upgraded to instabug 10.0. Since then I've had some crashes being reported around instabug causing these crashes, but not clear what is causing them, so I decided to upgrade to 10.4. Upgrading to this version is causing me to experience photo permissions issues on Android (and it's not clear why the upgrade is the cause of this). To be clear, nothing in my app changes, only updating to instabug 10.4. Just as a related test, updating the react-native-permissions library has no effect. I am running the app on Android 11.

### Expected Behavior
When I request and grant the photo permission, the photo permission is set as permission approved.

### Actual Behavior
When I request and grant the photo permission, the photo permission is set as permission rejected.

### Instabug integration code
Instabug.startWithToken(INSTABUG_KEY, [Instabug.invocationEvent.none])

### SDK Version
"instabug-reactnative": "10.4.0",

### React Native, iOS and Android Versions
"react-native": "0.63.3"
Android
        buildToolsVersion = "29.0.2"
        minSdkVersion = 24
        compileSdkVersion = 29
        targetSdkVersion = 29
        playServicesVersion = "17.0.0"

Current permissions
    android:name="android.permission.CAMERA"
    android:name="android.permission.WRITE_EXTERNAL_STORAGE"

Likely related to this issue https://github.com/Instabug/Instabug-React-Native/issues/582

**Comment by jacquesdev** [comment]
Can close this one, but looks like if you don't have android:name="android.permission.READ_EXTERNAL_STORAGE" when using 10.4, it will cause this issue. Possibly one to add to your install notes?

**Comment by jacquesdev** [comment]
Any advice here would be great, not currently able to upgrade to this version of instabug

**Comment by jacquesdev** [comment]
No idea why I needed to do this, but this seemed to be the fix needed https://github.com/zoontek/react-native-permissions/issues/448#issuecomment-627310896

**Comment by AliAbdelfattah** [comment]
@jacquesdev not sure why this is closed, are you still having issues with upgrading?

**Comment by jacquesdev** [comment]
Hi @AliAbdelfattah - I did continue to have this issue, and the issue involved updating my permissions plugin. Happy to re-open if you have an idea what may be causing this?

**Comment by AliAbdelfattah** [comment]
We don't think this is an issue with our SDK, your app might have been depending on permissions that our SDK uses, and when those permissions changed, your app broke. To make sure this is the case, you can try running your app after uninstalling Instabug to make sure your app runs without Instabug first and then install the latest version.
