### ISSUE TITLE
Update to 10.4.0 (Some library on Android not running well (permission), e.g: can't open gallery and microphone)

### ISSUE THREAD

**Issue by mobilewd** [Instabug/Instabug-React-Native#600]
I tried to update Instabug 10.4.0 when I build my android apps and can't open the gallery and microphone
and some permission can't be granted

![image](https://user-images.githubusercontent.com/83465439/123581392-05953500-d806-11eb-97bc-b8bc5758b8e5.png)

**SDK Version**
"instabug-reactnative": "^10.4.0",

**React Native**
"react": "16.13.1",
"react-native": "0.63.2",

**Device Model**
Android 10, Samsung A10s

**Comment by AliAbdelfattah** [comment]
Hi @mobilewd, thank you for reporting this. Could you try running your app without Instabug and check if the error still appears?

**Comment by mobilewd** [comment]
> Hi @mobilewd, thank you for reporting this. Could you try running your app without Instabug and check if the error still appears?

Yes, running well
and also previously I've used instabug version 10.0.0 it's running well

**Comment by AliAbdelfattah** [comment]
@mobilewd are you able to reproduce the issue on our sample app?

**Comment by singhayush1403** [comment]
This has been happening with me recently. How should I fix it?
