### ISSUE TITLE
React Native Version 0.64.2 Crash Android App at RunTime When System Font Size Change. 

### ISSUE THREAD

**Issue by temchannat** [Instabug/Instabug-React-Native#602]
I am using React Native `0.64.2` and it crash on Android Plateform on RunTime when we change system font size. 

Step to produce
1. Open app
2. Go to phone settings and change font size
3. Back to app
This will crash the app. 

I have set `allowFontScaling=false` but it still not working. 

There is no such problem on RN `0.64.1`

**Comment by AliAbdelfattah** [comment]
@temchannat thank you for reporting this. Any reason why you think it is caused by Instabug SDK? Also which version of the SDK?

**Comment by temchannat** [comment]
@AliAbdelfattah  I am not sure about that too.
