### ISSUE TITLE
target has frameworks with conflicting names

### ISSUE THREAD

**Issue by mrshahzeb7** [Instabug/Instabug-React-Native#606]
### **Steps To Reproduce:**
 npm install instabug-reactnative, cd iOS ,pod install

### **Expected Behaviour:**
 should install pod successfully

### **Actual Behaviour**
 The 'Pods-muv' target has frameworks with conflicting names: instabug.xcframework

### Environment:
"instabug-reactnative": "10.4.0",
"react-native": "0.64.1"
my  pod version :"1.10.1"
not building on any iOS device/simulator

**Comment by AliAbdelfattah** [comment]
Issue resolved through our support channel.
