### ISSUE TITLE
React Native plugin does not include critical iOS 15 fixes from recent iOS release.

### ISSUE THREAD

**Issue by swyftx-ryan** [Instabug/Instabug-React-Native#629]
The iOS plugin version must be updated in order to properly support iOS 15. 

See Instabug-iOS release below: 
![Screen Shot 2021-09-29 at 1 29 44 pm](https://user-images.githubusercontent.com/77943025/135198473-bc3d4ea3-c8b6-49fb-b7ce-7ffd37d97850.png)

**Comment by AliAbdelfattah** [comment]
Updated in the latest release.
