### ISSUE TITLE
Add SDK method to add build version attribute at runtime

### ISSUE THREAD

**Issue by sterlingwes** [Instabug/Instabug-React-Native#656]
### Steps to Reproduce the Problem

Use codepush to apply an over-the-air update to existing app binary and cause a crash. You'll notice the previously uploaded JS source map (for the existing app binary) does not map the stack trace correctly.

### Expected Behavior

The patched JS bundle in the app updated with codepush should use a separate sourcemap from the one originally uploaded for the initial app submission.

We can upload a separate source map when we send codepush updates to an existing app version and the stack trace mapping happens as expected.

I assume we could accomplish this by doing something like:

```
instabugClient.setAppVersion('1.2.0-codepush-3')
```

Where `codepush-3` is an identifier the user can construct based on the deployment tag / ID that gets incremented on each deployment. Then, a sourcemap can be uploaded for the same build number but that separate app version from the base app version (`1.2.0`).

This seems like it'd require changes here, and in instabug-ios / android SDKs, since the version appears to be reported in the underlying native SDKs and can't be amended.

### Actual Behavior

Any crashes that happen with the app version that has a codepush update applied are mapped to the original source map which does not have the codepush content, which leads to incorrect mapping / line / file references.

### Instabug integration code
N/A - this feature does not exist

### SDK Version
10.9.1

**Comment by ahmed1hisham** [comment]
Hello @sterlingwes ,
Thank you so much for the thorough and detailed issue description. We currently don't support codepush, however, it is in our short term plan.

I will close this issue, please feel free to re-open it if need be.

**Comment by sterlingwes** [comment]
That's too bad, you've probably lost a customer

**Comment by almirboticario** [comment]
@ahmed1hisham any update for this? Codepush is a problem for instabug

**Comment by davydspotnana** [comment]
> however, it is in our backlog.

@DavidMina96, @TheBuggedYRN, @a7medev  how about finally take it from backlog ?

**Comment by TheBuggedYRN** [comment]
Great news everyone! It finally senaked out of our backlog.
We are currently working on supporting CodePush, and it will land in one of our next releases, by the end of this year.
