### ISSUE TITLE
LogOut function does not remove user attribute

### ISSUE THREAD

**Issue by taboulot** [Instabug/Instabug-React-Native#670]
Hi 👋

When I call the `logOut` method I expect the user attributes to be removed as explain in [this documentation](https://docs.instabug.com/docs/react-native-identify-user#logout)

### Steps to Reproduce the Problem
1. Setup instabug
2. Set an attribute using `setUserAttribute`
3. Call `logOut`
4. Shake your phone
5. Report a bug

#### Video example
![out-02_22_2022-16_30_43](https://user-images.githubusercontent.com/9041221/155165068-280df89c-ee06-4aa1-a45f-1d544398cc5e.gif)

#### Code example
```
import Instabug from 'instabug-reactnative';
import React, { FunctionComponent, useEffect } from 'react';
import { Button, View } from 'react-native';
import RNBootSplash from 'react-native-bootsplash';
import { env } from './environment';

const setUpInstabug = () => {
  Instabug.start(env().INSTABUG_TOKEN, [Instabug.invocationEvent.shake]);
};

const setAttribute = () => {
  Instabug.setUserAttribute('MYATTRIBUTE', 'This is my value');
};

const logout = () => {
  Instabug.logOut();
};

const App: FunctionComponent = () => {
  useEffect(() => {
    RNBootSplash.hide();
  }, []);

  return (
    <View
      style={{ flex: 1, backgroundColor: 'white', justifyContent: 'center', alignItems: 'center' }}
    >
      <Button title="Setup Instabug" onPress={setUpInstabug} />
      <Button title="Set attribute MYATTRIBUTE" onPress={setAttribute} />
      <Button title="Instbug logout" onPress={logout} />
    </View>
  );
};

export { App };
```

### Actual Behavior
|    |  `Intabug.start`   | `Intabug.setUserAttribute`   | `Intabug.logOut`    |
|:-:|:-:|:-:|:-:|
|  **Actual report in instabug**  |   <img width="834" alt="image" src="https://user-images.githubusercontent.com/9041221/155166104-a6042fb4-6ab3-408c-bf92-82c6702ca851.png">|   <img width="827" alt="image" src="https://user-images.githubusercontent.com/9041221/155166298-47b27bca-0f89-4dbc-ab33-b32fcec59298.png">|  <img width="762" alt="image" src="https://user-images.githubusercontent.com/9041221/155166480-88afb7a7-9d95-4f64-b16b-6afe9c5dcde2.png"> |
|  **Expected behavior ?**  | ✅   |  ✅ |  ❌ I expect to not see MYATTRIBUTE as I have called `logOut`  |

### SDK Version
package.json
```
"instabug-reactnative": "^10.11.0"
```

yarn.lock
```
instabug-reactnative@^10.11.0:
  version "10.11.0"
  resolved "https://registry.yarnpkg.com/instabug-reactnative/-/instabug-reactnative-10.11.0.tgz#604852dae8969d159b2519302e1e1c84a1b7184b"
  integrity sha512-xebpObp1S32l4h/S6Qogvzx+SZ3NQF8Q+wlNCPnRp8bglYUcDBmnWfaixx3e2143GI80uvKVVxDCeHVPwRuKlw==
```

### Device Model
- iOS : reproduce on simulator iOS 15.2
- Android : test in progress

**Comment by AliAbdelfattah** [comment]
@taboulot thank you for reporting this, we're looking into it.

**Comment by AliAbdelfattah** [comment]
@taboulot the user needs to be identified for the log out API to work, you can do that through the API `Instabug.identifyUser`.

**Comment by taboulot** [comment]
@AliAbdelfattah 

It's exactly that. It works fine now 👌
Thank you for your help 🙏

Is the document open source so I can update it ? I think it could be a good idea to precise that in the `logout` section 😀

**Comment by AliAbdelfattah** [comment]
@taboulot don't worry about it, we'll be updating it. I'll close the issue now.
