### ISSUE TITLE
[CRASH] java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.instabug.apm.a3.l()' on a null object reference

### ISSUE THREAD

**Issue by muhamedzeema** [Instabug/Instabug-React-Native#677]
On Android, we are experiencing this crash after integrating Instabug with our application.

`java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.instabug.apm.a3.l()' on a null object reference
	 at com.instabug.apm.p0$a.run(Unknown Source:69)
	 at com.instabug.library.util.threading.PoolProvider$b.run(PoolProvider.java:5)
	 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
	 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
	 at com.instabug.library.o6$a.run(PriorityThreadFactory.java:8)
	 at java.lang.Thread.run(Thread.java:784)`

### Steps to Reproduce the Problem

Only Android users are experiencing this crash, and it is so random. We were able to reproduce it by logging out 2:3 times.

### Expected Behavior
no crashes

### Actual Behavior

The app crashes and won't open again.

### Instabug integration code
`    Instabug.start(token, [Instabug.invocationEvent.none]);
`

The problem appears to be with the APM module. Here is what we use.

`endAppLaunch: () => {
      APM.endAppLaunch();
  }`

`startExecutionTrace: async (name: string, attributes?: object) => {
      try {
        const trace = await APM.startExecutionTrace(name);
        return trace;
      } catch (error: any) {
        Instabug.logError(error.message || 'startExecutionTraceError');
      }
  }`

  `endExecutionTrace: async (trace: any) => {
    if (trace) {
      trace.end();
    }
  }`
  `startUITrace: async (traceName: string) => {
      APM.startUITrace(traceName);
  }`
  `endUITrace: async (traceName: string) => {
      APM.endUITrace(traceName);
  }`

### SDK Version
10.11.0

### React Native, iOS and Android Versions
0.64.0

### Device Model
Samsung Galaxy S10 (SM-G973F)
OPPO CPH2235
Samsung Galaxy S20 5G (SM-G981U1)
Huawei Mate 10 lite (RNE-L21)

### [Optional] Project That Reproduces the Issue
Only happens in release build.

**Comment by DavidMina96** [comment]
@muhamedzeema Thank you for reporting this to us, and apologies for any inconvenience. We're actively looking into it and will make sure to share with you any updates once possible.

**Comment by muhamedzeema** [comment]
@DavidMina96 thanks and waiting for your clarification, for now we enabled APM on android `APM.setEnabled(true)` but removed all calls to APM functions (endAppLaunch, startUITrace, endUITrace, startExecutionTrace) and haven't seen this crash since then, so the issue with one of those functions i guess.

**Comment by muhamedzeema** [comment]
@DavidMina96 any update on this ?

**Comment by DavidMina96** [comment]
@muhamedzeema Thank you for your patience. We've fixed a similar crash and included the fix in our latest release v10.13.0.
Please give it a try and let us know if the issue is resolved for you.

**Comment by muhamedzeema** [comment]
@DavidMina96 This crash can't be reproduced anymore, so we'll release the fix to users and see how it goes, 
thank you David 🙏

**Comment by DavidMina96** [comment]
@muhamedzeema Sounds great! Glad to be of help :)
