### ISSUE TITLE
No way to opt-out for sourcemap uploading on iOS

### ISSUE THREAD

**Issue by oblador** [Instabug/Instabug-React-Native#686]
Due to bugs like https://github.com/Instabug/Instabug-React-Native/issues/643 we noticed that Instabug is always uploading sourcemaps on iOS when using autolinking, whereas on Android you can control this via `instabugUploadEnable`. Since our usage of Instabug doesn't include crash reporting we do not want this functionality in our build steps.

### SDK Version
10.13.0

**Comment by sidferreira** [comment]
@AliAbdelfattah would be great if we could use file-based tokens, instead of code-based...

**Comment by oblador** [comment]
Any updates on this?
