### ISSUE TITLE
A problem occurred evaluating project ':instabug-reactnative'.

### ISSUE THREAD

**Issue by adityaputra11** [Instabug/Instabug-React-Native#719]
### Steps to Reproduce the Problem
install instabug on project

### Expected Behavior
can build apk

### Actual Behavior
error

* What went wrong:
A problem occurred evaluating project ':instabug-reactnative'.
> Invalid revision: '30.0.2'

### SDK Version
11.0

### React Native, iOS and Android Versions
 react-native: 0.66.4
  IDEs:
    Android Studio: 2021.1 AI-211.7628.21.2111.8309675
    Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild

### Device Model
not installed yet

**Comment by AliAbdelfattah** [comment]
@adityaputra11 please make sure to do a gradle sync after installing Instabug. If the issue still occurs, please provide us with more details on how you installed the library and how you are running the build script.

**Comment by AliAbdelfattah** [comment]
Closing the issue since we haven't heard back from you. Please feel free to reopen the issue if you have more information to add.

**Comment by arjuntare** [comment]
I faced the same issue, resolved by removing single quotes around InstabugReactNative_buildToolsVersion value in instabug-reactnative\android\gradle.properties

InstabugReactNative_buildToolsVersion='30.0.2' --> InstabugReactNative_buildToolsVersion=30.0.2
