### ISSUE TITLE
RN 0.69 support

### ISSUE THREAD

**Issue by Abhishek2250** [Instabug/Instabug-React-Native#732]
### Steps to Reproduce the Problem

While building the app for iOS, getting below warning:
<img width="769" alt="Screenshot 2022-06-27 at 2 37 13 PM" src="https://user-images.githubusercontent.com/97332137/175903634-44274301-6f61-489c-8252-9a5641becb0f.png">

After building the app, below error is coming on metro bundler:
<img width="853" alt="Screenshot 2022-06-27 at 2 35 08 PM" src="https://user-images.githubusercontent.com/97332137/175902674-ed91b4aa-08de-47d8-8b43-562d6057b084.png">

### Expected Behavior

Should work as working for react-native version 0.68.1

### Actual Behavior

Build warning and runtime error as shown above

### Instabug integration code

Instabug.isRunningLive(function (isLive) {
	if (isLive) {
		Instabug.start("Token", [Instabug.invocationEvent.none]);
	} else {
		Instabug.start("Token", [Instabug.invocationEvent.shake]);
	}
	Instabug.setPrimaryColor("#1D82DC");
	BugReporting.setFloatingButtonEdge(Instabug.floatingButtonEdge.left, 250);
});

### SDK Version

SDK 11

### React Native, iOS and Android Versions

react-native: 0.69
"instabug-reactnative": "^11.0.1",

**Comment by AliAbdelfattah** [comment]
@Abhishek2250 thank you for reporting this, we're looking into it.

**Comment by DavidMina96** [comment]
Hi @Abhishek2250, 

We were able to reproduce this behavior on our side and have created a fix for you in the below snapshot, which updates `react-native.config.js` file. Could you please give it a try and let us know if the issue is resolved? 

Snapshot:
`npm install https://github.com/Instabug/Instabug-React-Native#snapshot/11.0.1-MOB-8986`

**Comment by Abhishek2250** [comment]
@DavidMina96 I'm getting below issue while hitting `npm install https://github.com/Instabug/Instabug-React-Native#snapshot/11.0.1-MOB-8986`.

Error: zsh: no matches found: https://github.com/Instabug/Instabug-React-Native#snapshot/11.0.1-MOB-8986

**Comment by DavidMina96** [comment]
@Abhishek2250 It seems the `#` character might not be automatically escaped in your shell. You can escape it with a backslash `\#`. 

The full command would be:
`npm install https://github.com/Instabug/Instabug-React-Native\#snapshot/11.0.1-MOB-8986`

**Comment by Abhishek2250** [comment]
@DavidMina96 I'm not getting the build error now. Thanks for the update.
Are you guys going to release new version having this fix?

**Comment by mhtchawlaAntino** [comment]
Still facing the same issue in 11.0.2, also tried in 11.0.1. But no solution to me yet. Tried updating react-native.config.js as @DavidMina96 suggested but nothing seems to work.

**Comment by mhtchawlaAntino** [comment]
my react config - 

`const path = require("path");

module.exports = {
  project: {
    ios: {},
    android: {},
  },
  assets: ["./src/assets/fonts"],
  dependency: {
    platforms: {
      ios: {
        scriptPhases: [
          {
            name: "[instabug-reactnative] Upload Sourcemap",
            path: "./ios/upload_sourcemap.sh",
            execution_position: "after_compile",
          },
        ],
      },
      android: {},
    },
    hooks: {
      postlink: `node ${path.resolve(__dirname, "link_bridge.js")}`,
    },
  },
  commands: [
    {
      name: "add-instabug",
      func: () => {
        require("./link_gradle");
      },
    },
    {
      name: "remove-instabug",
      func: () => {
        require("./unlink_gradle");
      },
    },
  ],
};
`

**Comment by DavidMina96** [comment]
@mhtchawlaAntino RN 0.69 support isn't included in an official release yet. Could you please clarify if you've tried installing the snapshot shared earlier and are still facing an issue? If that's the case, would you please share the error you're getting to look into it?

**Comment by mhtchawlaAntino** [comment]
Yes I tried the snapshot also but error remained same as of @Abhishek2250 even after that, so i had to downgrade my project app to 0.68.0

**Comment by DavidMina96** [comment]
@mhtchawlaAntino Apologies for any inconvenience this may be causing. Would you please reach out to us at support@instabug.com so that we can further investigate the issue in a debugging call?
