### ISSUE TITLE
[Network]: Cannot read property 'length' of null

### ISSUE THREAD

**Issue by tgensol** [Instabug/Instabug-React-Native#733]
Hi there,

We are seeing lots of errors from your library : 

<img width="1231" alt="Capture d’écran 2022-06-27 à 14 07 52" src="https://user-images.githubusercontent.com/7864896/175937571-4a6b973f-9726-4602-afda-04e1c5582aff.png">

It looks like it happens when the network do not reply with a 200 and with `XMLHttpRequest error`, happening in both iOS and Android

Thank you !

**11.0.1**
### React Native, iOS and Android Versions
**0.67.2**

**Comment by DavidMina96** [comment]
@tgensol Thank you for reporting this; we're looking into it and will get back to you.

**Comment by DavidMina96** [comment]
Thank you for your patience, @tgensol! We've worked on a fix that resolves this error, and it's planned to be out in our next release. We'll also be happy to provide you with a snapshot version to use until then, so please feel free to let me know if you prefer so.

**Comment by tgensol** [comment]
@DavidMina96 Could be perfect yeah, can you create a patch ? So we can deploy the fix in a new version thank you !

**Comment by DavidMina96** [comment]
@tgensol You got it! Here's a snapshot with the fix, which you can install using this command:
`npm install https://github.com/Instabug/Instabug-React-Native\#snapshot/11.0.1-MOB-9082`

Please feel free to share with us your feedback :)

**Comment by tgensol** [comment]
We are deploying it today thank you

**Comment by leethree** [comment]
@DavidMina96 I forgot to mention we are using v10.13.0. We haven't been able to upgrade to v11 yet. But I just manually applied your fix and it works.

**Comment by DavidMina96** [comment]
The fix is released in v11.0.2. 🚀
