### ISSUE TITLE
Getting build error on Android for RN v0.69

### ISSUE THREAD

**Issue by Daniyaalbeg** [Instabug/Instabug-React-Native#753]
### Steps to Reproduce the Problem
Upgrade RN to 0.69.5 from 0.68. 
run: react-native run-android

### Expected Behavior
App to complete building without error

### Actual Behavior
Building app for android crashes with the following error:
```
MainApplication.java:72: error: cannot find symbol
         .Builder("CODE", MainApplication.this)
         ^
  symbol:   class Builder
  location: class RNInstabugReactnativePackage
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
1 error
```

### Instabug integration code

`Instabug.start('CODE', [Instabug.invocationEvent.shake])
`in App.tsx 

In MainApplication.java
```
@Override
  public void onCreate() {
    super.onCreate();
    // If you opted-in for the New Architecture, we enable the TurboModule system
    ReactFeatureFlags.useTurboModules = BuildConfig.IS_NEW_ARCHITECTURE_ENABLED;
    SoLoader.init(this, /* native exopackage */ false);
    initializeFlipper(this, getReactNativeHost().getReactInstanceManager());
    new RNInstabugReactnativePackage
         .Builder("CODE", MainApplication.this)
         .setInvocationEvent("shake")
         .setPrimaryColor("#126B6E")
         .setFloatingEdge("left")
         .setFloatingButtonOffsetFromTop(250)
         .build();
  }
```

### SDK Version

v11.0.2

### React Native, iOS and Android Versions
RN v0.69.5

**Comment by TheBuggedYRN** [comment]
This is due to migrating from Instabug v10 to Instabug v11.

You need to initialize Instabug from JS not Java, by removing the above code from your `MainApplication.java` and using `Instabug.start` in your `App.js` for both Android and iOS.

For more info, check our [migration guide](https://docs.instabug.com/docs/react-native-migration-guide#migrate-the-initialization-code-to-js).
