### ISSUE TITLE
instabug shellScript clashes with react-native-version (iOS)

### ISSUE THREAD

**Issue by breezertwo** [Instabug/Instabug-React-Native#771]
Im opening this here because i tracked an issue with `react-native-version` down to the shell script added by instabug buildphase (`[CP-User] [instabug-reactnative] Upload Sourcemap`).
Im not familiar with shell scripts so I can't exactly pin the error and maybe someone here can help/fix it. 
Something is wrong with an escape character. 
If I remove the instabug shell script from project.pbxproj the versioning succeeds . 

As a workaround I put the content into an external file and link it in build phases

Was working with`instabug-reactnative: 10.13.0`

### Steps to Reproduce the Problem
* create new project: `npx react-native init example `
* add  `"instabug-reactnative": "^11.0.2"` via npm/yarn
* run `pod install`
* run `npx react-native-version --target android,ios --generate-build`

### Expected Behavior
Updated versions in all iOS (&android files

### Actual Behavior
> [RNV] Versioning Android...
> [RNV] Android updated
> [RNV] Versioning iOS...
> [RNV] `SyntaxError: Expected "\"", "\\'", "\\\"", "\\n", or [^\\"] but "\\" found`.

### SDK Version
11

### React Native, iOS and Android Versions
11.0.2

**Comment by TheBuggedYRN** [comment]
Thanks @breezertwo for reporting this!
We will be looking into it and get back to you.

**Comment by TheBuggedYRN** [comment]
In #726 (which was released in `v11.0.1`) we included the shell script itself instead of its path. This helps solving many issue with auto-linking.

After looking into the issue you reported, it seems like a common issue with `react-native-version`, a quick fix, that seem to work, will be to run the command in legacy mode, to parse the iOS files correctly:

```shell
npx react-native-version --target android,ios --generate-build -L
```

Feel free to re-open if this doesn't solve your issue!

**Comment by breezertwo** [comment]
Thanks for the fast reply. 
Legacy mode would help me, but in my team not everybody has a Mac (Legacy Mode is only for macOS)

So this doesn't solve it for me.

**Comment by sterlingwes** [comment]
This is still a bug in my view as well. Especially since there doesn't appear to be a way to stop this package from automatically adding the build phase scripts short of patching the package podfile, which I've had to do so that I can have more control over the upload scripts which I don't want to run on every build scheme I have... kinda crazy this is configured automatically.

**Comment by TheBuggedYRN** [comment]
@sterlingwes While auto-uploading is the default behaviour, you can still disable it by setting the environment variable `INSTABUG_SOURCEMAPS_UPLOAD_DISABLE` to `false` when building your app.

**Comment by sterlingwes** [comment]
I'd rather the build phase script not be added if they're not going to be used. This would solve both issues

**Comment by sterlingwes** [comment]
For anyone else who happens on this won't fix issue, here's the patch i'm applying with [patch-package](https://npmjs.com/patch-package):

```diff
diff --git a/node_modules/instabug-reactnative/react-native.config.js b/node_modules/instabug-reactnative/react-native.config.js
index 6f6dad7..0b7dcd7 100644
--- a/node_modules/instabug-reactnative/react-native.config.js
+++ b/node_modules/instabug-reactnative/react-native.config.js
@@ -1,18 +1,18 @@
-const path = require('path');
+// const path = require('path')
 
 module.exports = {
   dependency: {
     platforms: {
       ios: {
-        scriptPhases: [
-          {
-            name: '[instabug-reactnative] Upload Sourcemap',
-            path: './ios/upload_sourcemap.sh',
-            execution_position: 'after_compile',
-          },
-        ],
+        // scriptPhases: [
+        //   {
+        //     name: '[instabug-reactnative] Upload Sourcemap',
+        //     path: './ios/upload_sourcemap.sh',
+        //     execution_position: 'after_compile',
+        //   },
+        // ],
       },
       android: {},
     },
   },
-};
+}
```

Consequence of this is you have to manually do sourcemap uploads in your CI pipeline but i think that flexibility is safer in any case...

**Comment by TheBuggedYRN** [comment]
@sterlingwes We are currently investigating an approach similar to your suggestion. It might take some time to land in a release, since it will be a breaking change.
