### ISSUE TITLE
App crashes on startup after installing instabug RN integration

### ISSUE THREAD

**Issue by rkeiii** [Instabug/Instabug-React-Native#845]
### Steps to Reproduce the Problem
1) Install the instabug RN SDK
2) Fire up the app in iOS or Android emulators

### Expected Behavior
App doesn't crash on startup

### Actual Behavior
App crashes with the following error on startup:
```
transform[stderr]: The exported identifier "Survey" is not declared in Babel's scope tracker
transform[stderr]: as a JavaScript value binding, and "@babel/plugin-transform-typescript"
transform[stderr]: never encountered it as a TypeScript type declaration.
transform[stderr]: It will be treated as a JavaScript value.
transform[stderr]:
transform[stderr]: This problem is likely caused by another plugin injecting
transform[stderr]: "Survey" without registering it in the scope tracker. If you are the author
transform[stderr]:  of that plugin, please use "scope.registerDeclaration(declarationPath)".
 BUNDLE  ./index.js

error: node_modules/instabug-reactnative/src/index.ts: /Users/rkeiii/workspace/BookshareMobileReader/node_modules/instabug-reactnative/src/index.ts: Exporting local "Survey", which is not declared.
  16 |   Report,
  17 |   Trace,
> 18 |   Survey,
     |   ^^^^^^
  19 |   APM,
  20 |   BugReporting,
  21 |   CrashReporting,
```

### Instabug integration code

The following is in my main App.tsx

```
import Instabug from 'instabug-reactnative';
...
  /**
   * Initialize Instabug crash handling service
   */
  useEffect(() => {
    Instabug.start('SECRET_TOKEN', [
      Instabug.invocationEvent.shake,
    ]);
  }, []);
```

### SDK Version

11.5.0

### React Native, iOS and Android Versions

React Native 0.7.0
iOS 15.5
Android 13

### Device Model

Occurs on both emulators

**Comment by DavidMina96** [comment]
Hi @rkeiii, 

Thanks for reporting this issue. Can you please provide your TypeScript version and Babel dependencies versions along with Babel configuration file? This will be of help to reproduce the issue and identify the fix accordingly.

**Comment by rkeiii** [comment]
Hi @DavidMina96 

Thanks for the reply and here's that info you requested.

Babel versions in package.json
```
    "@babel/core": "^7.12.9",
    "@babel/plugin-proposal-logical-assignment-operators": "^7.16.7",
    "@babel/runtime": "^7.12.5",
```

TypeScript version in package.json
```
"typescript": "^4.3.5"
```

My .babelrc.js
```
module.exports = {
  presets: ['module:metro-react-native-babel-preset'],
  plugins: [
    [
      'module-resolver',
      {
        alias: {
          stream: 'stream-browserify',
          path: 'path-webpack',
        },
      },
    ],
    'transform-inline-environment-variables',
    '@babel/plugin-proposal-logical-assignment-operators',
  ],
};

```

My babel.config.js
```
module.exports = {
  presets: ['module:metro-react-native-babel-preset'],
};

```

Let me know if there's anything else that'd be helpful.

**Comment by DavidMina96** [comment]
Thank you @rkeiii for providing this information. Using the same configuration wasn't enough to surface the issue yet on our side, so in order to reach a quick resolution here, would it be possible that you share with us a minimal project that reproduces the issue? Appreciate your cooperation :)

**Comment by tomwanzek** [comment]
@DavidMina96 I can confirm that the reported bug replicates for us.

The fix should be to fixable as follows. In the [index.ts]() file change the re-exports to:

```typescript
export {
  Report,
  Trace,
  APM,
  BugReporting,
  CrashReporting,
  FeatureRequests,
  NetworkLogger,
  Replies,
  Surveys,
};

export type {
  Survey
};
```
Note that `Survey` is only and `interface` and it gets correctly imported with `import type`. However, by implication it can only be re-exported as `export type` as well.

Hope this helps, and we can get to a quick patch release 😄 . We urgently want to upgrade and love the fact that this project is now TypeScript first 🙇

**Comment by DavidMina96** [comment]
@tomwanzek Thanks a lot for your contribution with this issue fix (and for your wonderful feedback re our package too). Such feedback is what keeps us enhancing our package continually to be up to our customers' expectations and beyond. 🙏 

For anyone facing this error, I'm happy to share that a patch release `v11.5.1` should now be out, which includes the fix for this issue.  🚀 

I'll be closing the issue accordingly, but please feel free to re-open it at any time if needs be.
