### ISSUE TITLE
Not working on Android

### ISSUE THREAD

**Issue by Abhishek2250** [Instabug/Instabug-React-Native#885]
### Steps to Reproduce the Problem
Latetst version is not working for Android. This is working on iOS

### Expected Behavior
Should initialise the instabug

### Actual Behavior
Not initialising

### Instabug integration code

Instabug.isRunningLive((isLive) => {
  if (isLive) {
    Instabug.start("Live Key", [Instabug.invocationEvent.shake]);
  } else {
    Instabug.start("beta key", [Instabug.invocationEvent.shake]);
  }
  Instabug.setPrimaryColor("#1D82DC");
  BugReporting.setFloatingButtonEdge(Instabug.floatingButtonEdge.left, 250);
});

### SDK Version

11.6.0
Also tested on 11.0.1

### React Native, iOS and Android Versions
react native: 0.68.1
iOS: 16.0
Android: 12

### Device Model
Pixel 3(Android 12)
OnePlus 5T(Android 12)

Thanks

**Comment by TheBuggedYRN** [comment]
Thanks @Abhishek2250 for reporting this!

Currently the `Instabug.isRunningLive` only works on iOS as it's mentioned [here](https://github.com/Instabug/Instabug-React-Native/blob/b509f53787b7676bdced59019b4a93ce4100ccf5/src/modules/Instabug.ts#L424-L435).

In the meantime, it's recommended to use **environment variables** to distinguish between Beta and Production environments as the mentioned API is really old one and it might get deprecated in the future.
