### ISSUE TITLE
[Bug] Project dist entry points missing/unaligned since 11.9.0

### ISSUE THREAD

**Issue by tomwanzek** [Instabug/Instabug-React-Native#930]
### Steps to Reproduce the Problem

* Upgrade a typescript-based project to use Instabug RN to 11.9.0

### Expected Behavior

* Project can be compiled with typescript compiler finding the instabug modules/exports

### Actual Behavior

* Compilation fails to compile because of:

`Cannot find module 'instabug-reactnative' or its corresponding type declarations.`

The issue manifests, it appears, as the `instabug-reactnative` version 11.9.0 `package.json` contains:

``` json
"main": "dist/index",
"types": "dist/index.d.ts"
```

However, the `dist` directory actually does not contain these entry points. Instead, they are found under `dist/src/...` and the 

`/dist` directory also includes a subdirectory `/tests`, which  is likely unintentional

In short, it seems, the build -> distribution pipeline is misaligned in terms of what gets moved to `/dist` and where.

By implication, we used to have an import of 

```typescript
import type { NetworkData } from "instabug-reactnative/dist/utils/XhrNetworkInterceptor";
```

which is broken for the same reason.

Preferably, we should be able to `import type { NetworkData } from  "instabug-reactnative"` to begin with. I.e. there should be re-exports to the top-level `index` file, so it can be used more "offically" in network obfuscator logic.

### Instabug integration code

Not needed, see explanation under **"Expected Behavior"**

### SDK Version

Issue introduced with version 11.9.0.

### React Native, iOS and Android Versions

Affects react native level irrespective of native versions

### Device Model

n/a

**Comment by DavidMina96** [comment]
Hi @tomwanzek, 

Thank you for reporting this issue and providing a detailed description as always. We'll look into it and get back to you.

**Comment by DavidMina96** [comment]
@tomwanzek Glad to inform you, and anyone else who is facing this issue, that a new version `11.9.1` is now released, which addresses the compilation error and re-exports the `NetworkData` type as well. 🎉 

Thanks again for catching this issue early on and reporting it. Please feel free to let us know if you have any further feedback anytime.

**Comment by tomwanzek** [comment]
@DavidMina96 Wonderful 🥇 Thanks for the quick fix 🙇 Lovely to get `NetworkData` from top-level now.
