### ISSUE TITLE
Disable uploading source map

### ISSUE THREAD

**Issue by Tobbb** [Instabug/Instabug-React-Native#968]
Currently the process of disabling source map uploads differs quite a lot from android and iOS. it would be nice to find a common workflow that works for both

iOS is using INSTABUG_SOURCEMAPS_UPLOAD_DISABLE and android uses bundle variable instabugUploadEnable.

my suggestion would be to use ENV variable for both cases :)

**Comment by a7medev** [comment]
Hi @Tobbb!
Thanks for your suggestion. We have added it to our backlog, we don't have an ETA for it though.
