### ISSUE TITLE
Android 13: Application begin asking photo and video access on open app

### ISSUE THREAD

**Issue by retyui** [Instabug/Instabug-React-Native#973]
### Steps to Reproduce the Problem

Use the latest `"instabug-reactnative": "^11.10.0",` pkg version on Android.

### Expected Behavior

Ask permission only when it's needed (on shake, tap on float button). 

Read best practices: https://developer.android.com/guide/topics/permissions/overview#best-practices

### Actual Behavior

Permission dialog appear on app start 

<img width=320 src="https://user-images.githubusercontent.com/4661784/235205641-f1fd2840-c6f6-4a42-8ca4-63c8b655553f.png"/>

### Instabug integration code

```tsx
  const instabugToken = '123'
  const invocationModes = [Instabug.invocationEvent.shake, Instabug.invocationEvent.screenshot, Instabug.invocationEvent.floatingButton];

  Instabug.start(instabugToken, invocationModes);
  Instabug.setWelcomeMessageMode(Instabug.welcomeMessageMode.disabled);
```

### SDK Version

the latest 

### React Native, iOS and Android Versions

Android 13

### Device Model

all

**Comment by a7medev** [comment]
Hi @retyui! This is an expected behavior since you are using the screenshot invocation event which requires access to media storage on Android.

**Comment by retyui** [comment]
@a7medev oh I see , that make seance....
