### ISSUE TITLE
Jacoco breaks on react native 0.72

### ISSUE THREAD

**Issue by Tobbb** [Instabug/Instabug-React-Native#994]
### Steps to Reproduce the Problem

on react native 0.72
run ./gradlew clean in android folder 

### Expected Behavior

successful build

### Actual Behavior

FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* Where:
Script '/xxxxx/node_modules/instabug-reactnative/android/jacoco.gradle' line: 14

Could not set unknown property 'enabled' for Report html of type org.gradle.api.reporting.internal.TaskGeneratedSingleDirectoryReport.
### SDK Version

"instabug-reactnative": "^11.12.0",
### [Optional] Project That Reproduces the Issue

removing 

```
  reports {
    html.enabled true
    xml.enabled true
  }
```
  
  in Jacoco.gradle solves it 
  
  or
  
  `  reports {
    html.required=true
    xml.required=true
  }`
  
  https://community.sonarsource.com/t/report-enabled-and-report-destination-are-deprecated-and-will-be-removed-in-gradle-8-0/50491

**Comment by asamiz** [comment]
Hello @Tobbb, sorry for the late reply, we are looking into this.

**Comment by asamiz** [comment]
Hello @Tobbb, changes were made and will be included in the next release. 🚀
I will close this issue, thank you for your contribution!
